# Generated by Django 1.11.26 on 2020-04-15 15:42

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("reso", "0003_auto_20200128_1940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalresohome",
            name="Basement",
            field=models.CharField(
                choices=[
                    (1, "Slab"),
                    (2, "Open crawl space"),
                    (3, "Enclosed crawl space"),
                    (4, "Conditioned basement"),
                    (5, "Unconditioned basement"),
                    (6, "More than one type"),
                    (7, "Apartment above conditioned space"),
                    (8, "Conditioned crawl space"),
                ],
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalresohome",
            name="Cooling",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Air conditioner"),
                    (2, "Air-source heat pump"),
                    (3, "Ground-source heat pump"),
                    (4, "Evaporative cooler"),
                    (90, "ARI 330/Closed Loop Ground-source heat pump"),
                    (91, "ARI 325/Open Loop Ground-source heat pump"),
                    (92, "Dual Fuel heat Pump"),
                    (33, "Integrated Space Water Heater"),
                ],
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalresohome",
            name="GreenBuildingVerificationType",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Certified Passive House"),
                    (2, "ENERGY STAR Certified Homes"),
                    (3, "EnerPHit"),
                    (4, "HERS Index Score"),
                    (5, "Home Energy Score"),
                    (6, "Home Energy Upgrade Certificate of Energy Efficiency Improvements"),
                    (7, "Home Energy Upgrade Certificate of Energy Efficiency Performance"),
                    (8, "Home Performance with ENERGY STAR"),
                    (9, "Indoor airPLUS"),
                    (10, "LEED For Homes"),
                    (11, "Living Building Challenge"),
                    (12, "NGBS New Construction"),
                    (13, "NGBS Small Projects Remodel"),
                    (14, "NGBS Whole-Home Remodel"),
                    (15, "PHIUS+"),
                    (16, "WaterSense"),
                    (17, "Zero Energy Ready Home"),
                ],
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalresohome",
            name="Heating",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Fuel-fired air distribution heater"),
                    (2, "Fuel-fired hydronic distribution heater"),
                    (3, "Fuel-fired unit heater"),
                    (4, "Fuel-fired unvented unit heater"),
                    (5, "Electric baseboard or radiant heater"),
                    (6, "Electric air distribution"),
                    (7, "Electric hydronic distribution"),
                    (8, "Air-source heat pump"),
                    (9, "Ground-source heat pump"),
                    (90, "ARI 330/Closed Loop Ground-source heat pump"),
                    (91, "ARI 325/Open Loop Ground-source heat pump"),
                    (92, "Dual Fuel heat Pump"),
                    (33, "Integrated Space Water Heater"),
                ],
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="resohome",
            name="Basement",
            field=models.CharField(
                choices=[
                    (1, "Slab"),
                    (2, "Open crawl space"),
                    (3, "Enclosed crawl space"),
                    (4, "Conditioned basement"),
                    (5, "Unconditioned basement"),
                    (6, "More than one type"),
                    (7, "Apartment above conditioned space"),
                    (8, "Conditioned crawl space"),
                ],
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="resohome",
            name="Cooling",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Air conditioner"),
                    (2, "Air-source heat pump"),
                    (3, "Ground-source heat pump"),
                    (4, "Evaporative cooler"),
                    (90, "ARI 330/Closed Loop Ground-source heat pump"),
                    (91, "ARI 325/Open Loop Ground-source heat pump"),
                    (92, "Dual Fuel heat Pump"),
                    (33, "Integrated Space Water Heater"),
                ],
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="resohome",
            name="GreenBuildingVerificationType",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Certified Passive House"),
                    (2, "ENERGY STAR Certified Homes"),
                    (3, "EnerPHit"),
                    (4, "HERS Index Score"),
                    (5, "Home Energy Score"),
                    (6, "Home Energy Upgrade Certificate of Energy Efficiency Improvements"),
                    (7, "Home Energy Upgrade Certificate of Energy Efficiency Performance"),
                    (8, "Home Performance with ENERGY STAR"),
                    (9, "Indoor airPLUS"),
                    (10, "LEED For Homes"),
                    (11, "Living Building Challenge"),
                    (12, "NGBS New Construction"),
                    (13, "NGBS Small Projects Remodel"),
                    (14, "NGBS Whole-Home Remodel"),
                    (15, "PHIUS+"),
                    (16, "WaterSense"),
                    (17, "Zero Energy Ready Home"),
                ],
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="resohome",
            name="Heating",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Fuel-fired air distribution heater"),
                    (2, "Fuel-fired hydronic distribution heater"),
                    (3, "Fuel-fired unit heater"),
                    (4, "Fuel-fired unvented unit heater"),
                    (5, "Electric baseboard or radiant heater"),
                    (6, "Electric air distribution"),
                    (7, "Electric hydronic distribution"),
                    (8, "Air-source heat pump"),
                    (9, "Ground-source heat pump"),
                    (90, "ARI 330/Closed Loop Ground-source heat pump"),
                    (91, "ARI 325/Open Loop Ground-source heat pump"),
                    (92, "Dual Fuel heat Pump"),
                    (33, "Integrated Space Water Heater"),
                ],
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
    ]
