# Generated by Django 1.11.26 on 2020-07-01 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reso", "0006_merge_20200626_1514"),
        ("reso", "0005_auto_20200630_1724"),
    ]

    operations = []
