# Generated by Django 4.0.7 on 2022-09-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reso", "0008_alter_historicalresogreenverification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resogreenverification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
