# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("customer_eto", "0001_initial"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="home_status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="home.EEPProgramHomeStatus",
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="home_status",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="home.EEPProgramHomeStatus"
            ),
        ),
        migrations.AddField(
            model_name="etoaccount",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eto_account",
                to="company.Company",
            ),
        ),
    ]
