# Generated by Django 1.11.16 on 2018-10-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0002_auto_20181008_1815"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fasttracksubmission",
            options={
                "ordering": ("id",),
                "permissions": (("view_fasttracksubmission", "View ProjectTracking Submission"),),
                "verbose_name": "ProjectTracking Submission",
            },
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
