# Generated by Django 1.11.17 on 2019-06-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_auto_20181010_2316"),
        ("home", "0008_remove_home_document_model"),
        ("subdivision", "0003_auto_20190531_1224"),
        ("customer_eto", "0005_create_hillsboro_communities"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermitAndOccupancySettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reeds_crossing_compliance_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "eps_20",
                                "Energy Performance Score (EPS) \u201c20%\u201d with Specific Elements",
                            ),
                            (
                                "eps_30",
                                "Energy Performance Score (EPS) \u201c30%\u201d with Specific Elements",
                            ),
                            (
                                "eps_40",
                                "Energy Performance Score (EPS) \u201c40%\u201d with Specific Elements",
                            ),
                            ("ea_silver", "Earth Advantage Silver with Specific Elements"),
                            (
                                "ngbs_standard",
                                "National Green Building Standard (NGBS) with Specific Elements",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "rosedale_parks_compliance_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ea", "Earth Advantage"),
                            ("ngbs", "National Green Building Standard (NGBS)"),
                            ("eps", "EPS"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.Company",
                    ),
                ),
                (
                    "subdivision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subdivision.Subdivision",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.Home",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownedpermitandoccupancy_set",
                        to="company.Company",
                    ),
                ),
            ],
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="permitandoccupancysettings",
            unique_together=set(
                [("owner", "home"), ("owner", "company"), ("owner", "subdivision")]
            ),
        ),
    ]
