# Generated by Django 1.11.17 on 2019-06-21 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0004_auto_20190621_0327"),
        ("customer_eto", "0006_add_permitandoccupancysettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitandoccupancysettings",
            name="signed_building_permit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="permitandoccupancysettings",
            name="signed_certificate_of_occupancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
    ]
