# Generated by Django 1.11.17 on 2019-06-21 13:39

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0007_auto_20190621_0327"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitandoccupancysettings",
            name="data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
    ]
