# Generated by Django 1.11.26 on 2020-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0008_add_data_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasttracksubmission",
            name="energy_smart_homes_eps_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="energy_smart_homes_solar_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="net_zero_energy_smart_home_project_id",
            field=models.CharField(
                blank=True,
                help_text="Project Tracker assigned ID after submission to the Energy Smart Home Program",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="net_zero_eps_incentive",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Net Zero EPS Incentive",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="net_zero_solar_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="solar_project_id",
            field=models.CharField(
                blank=True,
                help_text="Project Tracker assigned ID after submission to the Solar Program",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="energy_smart_homes_eps_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="energy_smart_homes_solar_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="net_zero_energy_smart_home_project_id",
            field=models.CharField(
                blank=True,
                help_text="Project Tracker assigned ID after submission to the Energy Smart Home Program",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="net_zero_eps_incentive",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Net Zero EPS Incentive",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="net_zero_solar_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="solar_project_id",
            field=models.CharField(
                blank=True,
                help_text="Project Tracker assigned ID after submission to the Solar Program",
                max_length=20,
                null=True,
            ),
        ),
    ]
