# Generated by Django 1.11.26 on 2020-05-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0009_netzero"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasttracksubmission",
            name="percent_improvement_kwh",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="percent_improvement_therms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="percent_improvement_kwh",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="percent_improvement_therms",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
