# Generated by Django 2.2 on 2020-08-11 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0011_auto_20200811_0839"),
        ("customer_eto", "0011_auto_20200728_1245"),
    ]

    operations = []
