# Generated by Django 3.1.9 on 2021-06-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0012_merge_20200811_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasttracksubmission",
            name="original_energy_smart_homes_eps_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="original_energy_smart_homes_solar_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="original_net_zero_eps_incentive",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Net Zero EPS Incentive",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="original_net_zero_solar_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="original_energy_smart_homes_eps_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="original_energy_smart_homes_solar_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="original_net_zero_eps_incentive",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Net Zero EPS Incentive",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="original_net_zero_solar_incentive",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
