# Generated by Django 3.2.6 on 2021-08-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0013_auto_20210608_1735"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasttracksubmission",
            name="achieved_total_credits",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="code_credit_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="eligible_gas_points",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="fireplace_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="required_credits_to_meet_code",
            field=models.FloatField(default=0.0, help_text="WA Code Credits"),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="thermostat_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="achieved_total_credits",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="code_credit_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="eligible_gas_points",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="fireplace_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="required_credits_to_meet_code",
            field=models.FloatField(default=0.0, help_text="WA Code Credits"),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="thermostat_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="etoaccount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="permitandoccupancysettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
