# Generated by Django 3.2.7 on 2021-10-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0014_auto_20210824_2208"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasttracksubmission",
            name="electric_cost_per_month",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="improved_total_kwh",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="improved_total_therms",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="natural_gas_cost_per_month",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="projected_carbon_consumption_electric",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="projected_carbon_consumption_natural_gas",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="pv_kwh",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="solar_hot_water_kwh",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="solar_hot_water_therms",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="electric_cost_per_month",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="improved_total_kwh",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="improved_total_therms",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="natural_gas_cost_per_month",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="projected_carbon_consumption_electric",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="projected_carbon_consumption_natural_gas",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="pv_kwh",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="solar_hot_water_kwh",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="solar_hot_water_therms",
            field=models.FloatField(default=0.0),
        ),
    ]
