# Generated by Django 3.2.9 on 2021-12-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0015_auto_20211011_2309"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasttracksubmission",
            name="original_kwh_savings",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="original_mbtu_savings",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="original_therm_savings",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="rigid_insulation_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="sealed_attic_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="triple_pane_window_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="original_kwh_savings",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="original_mbtu_savings",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="original_therm_savings",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="rigid_insulation_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="sealed_attic_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="triple_pane_window_incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
