# Generated by Django 4.0.7 on 2022-09-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0019_auto_20220601_1713"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalfasttracksubmission",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ProjectTracking Submission",
                "verbose_name_plural": "historical ProjectTracking Submissions",
            },
        ),
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="kwh_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="mbtu_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="original_kwh_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="original_mbtu_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="original_therm_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="therm_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="kwh_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="mbtu_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="original_kwh_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="original_mbtu_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="original_therm_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="therm_savings",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
