# Generated by Django 4.0.7 on 2022-09-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0020_alter_historicalfasttracksubmission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasttracksubmission",
            name="estimated_annual_energy_costs_code",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="estimated_monthly_energy_costs_code",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="estimated_annual_energy_costs_code",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="estimated_monthly_energy_costs_code",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
    ]
