# Generated by Django 4.0.8 on 2022-11-30 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "customer_eto",
            "0022_remove_fasttracksubmission_net_zero_energy_smart_home_project_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fasttracksubmission",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="submission_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="submit_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("STARTED", "Started"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("RETRY", "Retry"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fasttracksubmission",
            name="submit_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pt_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="created_date",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="modified_date",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="submission_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="submit_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("STARTED", "Started"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("RETRY", "Retry"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfasttracksubmission",
            name="submit_user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
