# Generated by Django 4.0.8 on 2022-11-30 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0023_fasttracksubmission_created_date_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE customer_eto_fasttracksubmission SET created_date=NULL, modified_date=NULL"
        )
    ]
