# Generated by Django 4.0.8 on 2022-11-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0024_fasttracksubmission_set_dates_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="submission_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="submission_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
