# Generated by Django 4.0.8 on 2022-11-30 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0025_alter_fasttracksubmission_submission_count_and_more"),
    ]

    operations = [
        migrations.RunSQL("UPDATE customer_eto_fasttracksubmission SET submission_count = 0")
    ]
