# Generated by Django 4.0.8 on 2022-12-15 10:57

from django.db import migrations
from django.db.models import Q


def set_status_count_for_pushed_items(apps, schema_editor):
    fast_track_model = apps.get_model("customer_eto", "FastTrackSubmission")

    fast_track_model.objects.filter(project_id__isnull=False).filter(~Q(project_id="")).update(
        submit_status="SUCCESS", submission_count=1
    )


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0026_fasttracksubmission_set_submission_count"),
    ]

    operations = [
        migrations.RunPython(set_status_count_for_pushed_items),
    ]
