# Generated by Django 4.1.7 on 2023-03-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_eto", "0028_alter_fasttracksubmission_project_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fasttracksubmission",
            name="submit_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("PENDING", "Pending"),
                    ("STARTED", "Started"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("RETRY", "Retry"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfasttracksubmission",
            name="submit_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("PENDING", "Pending"),
                    ("STARTED", "Started"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("RETRY", "Retry"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
