# Generated by Django 1.11.16 on 2018-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eepprogram",
            name="workflow_default_settings",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="workflow_default_settings",
            field=models.JSONField(default=dict),
        ),
    ]
