# Generated by Django 1.11.16 on 2018-11-30 19:05

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0004_collection_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eepprogram",
            name="workflow_default_settings",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="workflow_default_settings",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
    ]
