# Generated by Django 1.11.17 on 2019-04-15 13:31

from django.db import migrations


def set_collection_from_program(home_status):
    # homestatus.set_collection_from_program()

    from django_input_collection.models.utils import clone_collection_request

    collection_request = home_status.eep_program.collection_request
    cloned = clone_collection_request(collection_request)
    home_status.collection_request = cloned
    home_status.save()


# pylint: disable=invalid-name
def forward(apps, schema_editor):
    EEPProgram = apps.get_model("eep_program", "EEPProgram")

    from ..program_builder.eto_legacy import Eto2018, Eto2017, Eto2016

    convert = {
        "eto-2018-qa": Eto2018,
        "eto-2017-qa": Eto2017,
        "eto-2016-qa": Eto2016,
    }

    num_programs = len(convert)
    for i, (slug, ProgramBuilderClass) in enumerate(convert.items()):
        program = EEPProgram.objects.get(slug=slug)

        home_statuses = program.homestatuses.filter(collection_request=None).select_related(
            "eep_program"
        )
        total = home_statuses.count()

        builder = ProgramBuilderClass()
        builder.build("qa")
        for j, home_status in enumerate(home_statuses):
            set_collection_from_program(home_status)
            # raise Exception('stop')
        # raise Exception('break')
    # raise Exception('finished')


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0008_shallow_migrate_to_cr"),
    ]

    operations = []
