# Generated by Django 1.11.17 on 2019-03-05 18:26

# NOTE: This migration exists because the ProgramBuilder code doesn't yet know how to detect
# updates to object pks, which the measure codes are.


from django.db import migrations


structure_map = {
    "has-solar-pv": "solar",
    "has-smart-thermostat": "smart-thermostat-brand",
    "equipment-primary-heating-type": "primary-heating-equipment-type",
    "equipment-heat-pump-water-heater-serial-number": "heat-pump-water-heater-serial-number",
    "inspection-notes": "notes",
}


def forwards__structure_measure_names(apps, schema_editor):
    Measure = apps.get_model("django_input_collection", "Measure")
    CollectionInstrument = apps.get_model("django_input_collection", "CollectionInstrument")

    to_migrate = Measure.objects.filter(id__in=structure_map.keys())
    for measure_id in to_migrate.values_list("id", flat=True):
        new_measure, _ = Measure.objects.get_or_create(id=structure_map[measure_id])
        CollectionInstrument.objects.filter(measure_id=measure_id).update(measure=new_measure)

    # Delete old orphaned measures
    to_migrate.delete()


def backwards__unstructure_measure_names(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0009_qa_shallow_migrate_to_cr"),
    ]

    operations = [
        migrations.RunPython(
            forwards__structure_measure_names, backwards__unstructure_measure_names
        ),
    ]
