# Generated by Django 1.11.17 on 2019-08-14 23:47

from django.db import migrations


def forward(apps, schema_editor):
    from axis.eep_program.program_builder.programs.home_builder_association.built_green_wa import (
        BuiltGreenWAPerformance,
        BuiltGreenWAPrescriptive,
    )

    program_builder = BuiltGreenWAPerformance()
    program_builder.build("rater")

    program_builder = BuiltGreenWAPrescriptive()
    program_builder.build("rater")

    Type = apps.get_model("annotation.Type")
    Type.objects.filter(slug__in=program_builder.annotations).exclude(
        slug="total-built-green-points"
    ).update(is_required=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0004_auto_20190826_2024"),
        ("eep_program", "0012_eepprogram_metrics"),
    ]

    operations = [migrations.RunPython(forward, noop)]
