# Generated by Django 1.11.17 on 2019-08-14 23:47

from django.db import migrations


def forward(apps, schema_editor):
    from ..program_builder.wa_code_study import WACodeStudy

    program_builder = WACodeStudy()
    program_builder.build("rater")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0013_built_green_wa"),
    ]

    operations = []
