# Generated by Django 1.11.17 on 2019-08-14 23:47

from django.db import migrations


def forward(apps, schema_editor):
    from ..program_builder.phius import Phius

    program_builder = Phius()
    program_builder.build("rater")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0014_wa_code_study"),
    ]

    operations = []
