# Generated by Django 1.11.17 on 2019-08-14 23:47

from django.db import migrations


def forward(apps, schema_editor):
    from ..program_builder.resnet_registry_data import ResnetRegistryData

    program_builder = ResnetRegistryData()
    program_builder.build("rater")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0015_phius_update"),
    ]

    operations = []
