# Generated by Django 1.11.26 on 2020-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0016_resnet_registry_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="eepprogram",
            name="require_energy_modeler",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eepprogram",
            name="require_field_inspector",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="require_energy_modeler",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="require_field_inspector",
            field=models.BooleanField(default=False),
        ),
    ]
