# Generated by Django 2.2 on 2020-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0017_auto_20200312_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="eepprogram",
            name="is_multi_family",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that this program is using for Multi Family homes",
            ),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="is_multi_family",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that this program is using for Multi Family homes",
            ),
        ),
    ]
