# Generated by Django 3.1.3 on 2021-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0018_auto_20200805_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="eepprogram",
            name="require_architect_assigned_to_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eepprogram",
            name="require_architect_relationship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eepprogram",
            name="require_communityowner_assigned_to_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eepprogram",
            name="require_communityowner_relationship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eepprogram",
            name="require_developer_assigned_to_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eepprogram",
            name="require_developer_relationship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="require_architect_assigned_to_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="require_architect_relationship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="require_communityowner_assigned_to_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="require_communityowner_relationship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="require_developer_assigned_to_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleepprogram",
            name="require_developer_relationship",
            field=models.BooleanField(default=False),
        ),
    ]
