# Generated by Django 3.1.6 on 2021-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0019_auto_20210205_0946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eepprogram",
            name="allow_ekotrope_input",
            field=models.BooleanField(
                default=False, verbose_name="DEPRECATED Enable Ekotrope attachments"
            ),
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="allow_rem_input",
            field=models.BooleanField(
                default=True, verbose_name="DEPRECATED Enable REM/Rate™ attachments"
            ),
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="require_ekotrope_data",
            field=models.BooleanField(
                default=False, verbose_name="Require Ekotrope Data (Exclusive)"
            ),
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="require_input_data",
            field=models.BooleanField(
                default=True, verbose_name="Require simulation data (Rem SQL OR Eko)"
            ),
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="require_model_file",
            field=models.BooleanField(
                default=False, verbose_name="Require REM/Rate™ Model BLG File"
            ),
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="require_rem_data",
            field=models.BooleanField(
                default=False, verbose_name="Require REM/Rate™ SQL Data (Exclusive)"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="allow_ekotrope_input",
            field=models.BooleanField(
                default=False, verbose_name="DEPRECATED Enable Ekotrope attachments"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="allow_rem_input",
            field=models.BooleanField(
                default=True, verbose_name="DEPRECATED Enable REM/Rate™ attachments"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="require_ekotrope_data",
            field=models.BooleanField(
                default=False, verbose_name="Require Ekotrope Data (Exclusive)"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="require_input_data",
            field=models.BooleanField(
                default=True, verbose_name="Require simulation data (Rem SQL OR Eko)"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="require_model_file",
            field=models.BooleanField(
                default=False, verbose_name="Require REM/Rate™ Model BLG File"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="require_rem_data",
            field=models.BooleanField(
                default=False, verbose_name="Require REM/Rate™ SQL Data (Exclusive)"
            ),
        ),
    ]
