# Generated by Django 3.1.6 on 2021-04-01 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0020_auto_20210323_1625"),
        ("eep_program", "0021_auto_20210318_1548"),
    ]

    operations = []
