# Generated by Django 3.2.14 on 2022-07-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0022_merge_20210401_1458"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaleepprogram",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Program",
                "verbose_name_plural": "historical Programs",
            },
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="allow_metro_sampling",
            field=models.BooleanField(default=True, verbose_name="Allow RESNET Metro Sampling"),
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="allow_sampling",
            field=models.BooleanField(default=True, verbose_name="Allow RESNET Sampling"),
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="eepprogram",
            name="require_resnet_sampling_provider",
            field=models.BooleanField(
                default=False, verbose_name="Require RESNET Sampling Provider"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="allow_metro_sampling",
            field=models.BooleanField(default=True, verbose_name="Allow RESNET Metro Sampling"),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="allow_sampling",
            field=models.BooleanField(default=True, verbose_name="Allow RESNET Sampling"),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogram",
            name="require_resnet_sampling_provider",
            field=models.BooleanField(
                default=False, verbose_name="Require RESNET Sampling Provider"
            ),
        ),
    ]
