# Generated by Django 4.1.5 on 2023-01-24 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0023_auto_20220720_2313"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eepprogram",
            name="require_builder_epa_is_active",
        ),
        migrations.RemoveField(
            model_name="eepprogram",
            name="require_rater_epa_is_active",
        ),
        migrations.RemoveField(
            model_name="historicaleepprogram",
            name="require_builder_epa_is_active",
        ),
        migrations.RemoveField(
            model_name="historicaleepprogram",
            name="require_rater_epa_is_active",
        ),
    ]
