# Generated by Django 1.11.16 on 2018-10-08 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("floorplan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemRateAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=32, null=True)),
                ("password", models.CharField(blank=True, max_length=613, null=True)),
                (
                    "resnet_user_id",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="RESNET User ID"
                    ),
                ),
                (
                    "resnet_password",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="RESNET Password"
                    ),
                ),
                ("account_type", models.CharField(blank=True, max_length=32, null=True)),
                ("expires", models.DateField(blank=True, null=True)),
                ("created_on", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("last_validated", models.DateTimeField(blank=True, editable=False, null=True)),
                ("latest_notes", models.TextField(blank=True, editable=False, null=True)),
                (
                    "task_id",
                    models.CharField(blank=True, editable=False, max_length=255, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="company.Company"
                    ),
                ),
            ],
            options={
                "verbose_name": "REM/Rate Account Detail",
            },
        ),
        migrations.CreateModel(
            name="RemRateLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("trigger", models.CharField(max_length=64)),
                ("log", models.CharField(max_length=128)),
                ("time", models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="RemRateUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=128, unique=True)),
                ("password", models.CharField(blank=True, max_length=613, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("last_used", models.DateTimeField(auto_now=True, verbose_name="Last updated")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remrate_user_ids",
                        to="company.Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "REM/Rate User",
            },
        ),
        migrations.CreateModel(
            name="RemXML",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("blg_version", models.CharField(max_length=32)),
                (
                    "xml_version",
                    models.CharField(
                        choices=[
                            ("14.6.2 ", "14.6.2 "),
                            ("14.6.3", "14.6.3"),
                            ("14.6.4", "14.6.4"),
                            ("15.0 ", "15.0 "),
                            ("15.1 ", "15.1 "),
                            ("15.2 ", "15.2 "),
                            ("15.3", "15.3"),
                            ("15.4", "15.4"),
                            ("15.5", "15.5"),
                            ("15.6", "15.6"),
                        ],
                        max_length=32,
                    ),
                ),
                ("xml", models.TextField()),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xml_conversions",
                        to="company.Company",
                    ),
                ),
                (
                    "floorplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xml_conversions",
                        to="floorplan.Floorplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "REM/Rate XML Conversion",
            },
        ),
        migrations.AddField(
            model_name="remrateaccount",
            name="export_user_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="remrate.RemRateUser",
            ),
        ),
    ]
