# Generated by Django 1.11.26 on 2020-04-23 12:57

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("remrate", "0002_remxml_simulation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remrateuser",
            name="password",
            field=axis.core.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
