# Generated by Django 3.2.11 on 2022-02-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate", "0003_auto_20200423_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remrateaccount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="remratelog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="remrateuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="RemXML",
        ),
    ]
