# Generated by Django 1.11.17 on 2019-07-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampleset", "0002_auto_20181010_2316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsampleset",
            name="is_metro_sampled",
            field=models.BooleanField(
                default=False,
                help_text="Tracks last known state of this flag\n                                           as calculated by its member homestatuses.",
            ),
        ),
        migrations.AlterField(
            model_name="sampleset",
            name="is_metro_sampled",
            field=models.BooleanField(
                default=False,
                help_text="Tracks last known state of this flag\n                                           as calculated by its member homestatuses.",
            ),
        ),
        migrations.AlterField(
            model_name="samplesethomestatus",
            name="is_test_home",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this home is\n                                       providing answers or receiving them.",
            ),
        ),
    ]
