# Generated by Django 1.11.16 on 2018-10-08 18:15

import axis.floorplan.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ekotrope", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Floorplan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the floorplan.", max_length=64, null=True
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Enter the numerical identifier for the floorplan.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "square_footage",
                    models.IntegerField(
                        help_text="Enter the square footage of the floorplan.", null=True
                    ),
                ),
                (
                    "remrate_data_file",
                    models.FileField(
                        blank=True,
                        help_text='Click on "Select file" and select a file from the file browser.  Once selected, click on "Change" to select a new file or "Remove" to delete the file.',
                        max_length=512,
                        null=True,
                        upload_to=axis.floorplan.models.content_blgfile_name,
                    ),
                ),
                ("component_serialization", models.TextField(blank=True, default=dict)),
                ("simulation_result", models.TextField(blank=True, default=dict)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("preliminary", "Preliminary"), ("final", "Final")],
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="Rating Type",
                    ),
                ),
                ("is_custom_home", models.BooleanField(default=False)),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text='Enter a comment for the floorplan if desired and click on "Submit" to save the comment.',
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(editable=False)),
                ("modified_date", models.DateTimeField()),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name", "number"),
                "verbose_name": "Floorplan",
                "permissions": (
                    ("view_floorplan", "Ability to view a floor plan"),
                    ("can_simulate", "Ability to simulate"),
                ),
            },
        ),
        migrations.CreateModel(
            name="FloorplanDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "document",
                    models.FileField(
                        max_length=512, upload_to=axis.floorplan.models.content_floorplan_name
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalFloorplan",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the floorplan.", max_length=64, null=True
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Enter the numerical identifier for the floorplan.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "square_footage",
                    models.IntegerField(
                        help_text="Enter the square footage of the floorplan.", null=True
                    ),
                ),
                (
                    "remrate_data_file",
                    models.TextField(
                        blank=True,
                        help_text='Click on "Select file" and select a file from the file browser.  Once selected, click on "Change" to select a new file or "Remove" to delete the file.',
                        max_length=512,
                        null=True,
                    ),
                ),
                ("component_serialization", models.TextField(blank=True, default=dict)),
                ("simulation_result", models.TextField(blank=True, default=dict)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("preliminary", "Preliminary"), ("final", "Final")],
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="Rating Type",
                    ),
                ),
                ("is_custom_home", models.BooleanField(default=False)),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text='Enter a comment for the floorplan if desired and click on "Submit" to save the comment.',
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(editable=False)),
                ("modified_date", models.DateTimeField()),
                ("slug", models.SlugField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "ekotrope_houseplan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ekotrope.HousePlan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="company.Company",
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical Floorplan",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFloorplanDocument",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("document", models.TextField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="company.Company",
                    ),
                ),
                (
                    "floorplan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.Floorplan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical floorplan document",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "floorplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="floorplan.Floorplan"
                    ),
                ),
            ],
            options={
                "ordering": ("system_type",),
            },
        ),
        migrations.CreateModel(
            name="SystemType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, max_length=128, null=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="company.Company"
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="system",
            name="system_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="floorplan.SystemType"
            ),
        ),
    ]
