# Generated by Django 1.11.16 on 2018-11-30 19:05

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("floorplan", "0004_auto_20181010_2316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floorplan",
            name="component_serialization",
            field=axis.core.fields.AxisJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="floorplan",
            name="simulation_result",
            field=axis.core.fields.AxisJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="component_serialization",
            field=axis.core.fields.AxisJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="simulation_result",
            field=axis.core.fields.AxisJSONField(blank=True, default=dict),
        ),
    ]
