# Generated by Django 1.11.17 on 2019-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floorplan", "0005_auto_20181130_1905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floorplan",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="floorplan",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="created_date",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="modified_date",
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
