# Generated by Django 1.11.17 on 2019-05-25 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("floorplan", "0006_auto_20190531_1224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="floorplandocument",
            name="company",
        ),
        migrations.RemoveField(
            model_name="floorplandocument",
            name="floorplan",
        ),
        migrations.RemoveField(
            model_name="historicalfloorplandocument",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalfloorplandocument",
            name="floorplan",
        ),
        migrations.RemoveField(
            model_name="historicalfloorplandocument",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="floorplan",
            name="documents",
        ),
        migrations.DeleteModel(
            name="FloorplanDocument",
        ),
        migrations.DeleteModel(
            name="HistoricalFloorplanDocument",
        ),
    ]
