# Generated by Django 1.11.17 on 2019-08-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("floorplan", "0007_remove_floorplan_document_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="remrate_target",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Type the first few letters of the name of the REM/Rate data set or subdivision and select the correct REM/Rate data set from the list presented.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="remrate_data.Simulation",
            ),
        ),
    ]
