# Generated by Django 1.11.17 on 2019-09-25 19:00

import axis.floorplan.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("floorplan", "0008_auto_20190826_2024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floorplan",
            name="remrate_data_file",
            field=models.FileField(
                blank=True,
                help_text='Click on "Select file" and select a file from the file browser.  Once selected, click on "Change" to select a new file or "Remove" to delete the file.',
                max_length=512,
                null=True,
                upload_to=axis.floorplan.models.content_blgfile_name,
                verbose_name="REM/Rate\u2122 File",
            ),
        ),
        migrations.AlterField(
            model_name="floorplan",
            name="remrate_target",
            field=models.OneToOneField(
                blank=True,
                help_text="Type the first few letters of the name of the REM/Rate data set or subdivision and select the correct REM/Rate data set from the list presented.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="remrate_data.Simulation",
                verbose_name="REM/Rate\u2122 Data",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="remrate_data_file",
            field=models.TextField(
                blank=True,
                help_text='Click on "Select file" and select a file from the file browser.  Once selected, click on "Change" to select a new file or "Remove" to delete the file.',
                max_length=512,
                null=True,
                verbose_name="REM/Rate\u2122 File",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="remrate_target",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Type the first few letters of the name of the REM/Rate data set or subdivision and select the correct REM/Rate data set from the list presented.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="remrate_data.Simulation",
                verbose_name="REM/Rate\u2122 Data",
            ),
        ),
    ]
