# Generated by Django 2.2 on 2020-08-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulation", "0002_auto_20200812_2248"),
        ("floorplan", "0012_merge_20200811_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="simulation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="simulation.Simulation",
            ),
        ),
        migrations.AddField(
            model_name="historicalfloorplan",
            name="simulation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="simulation.Simulation",
            ),
        ),
    ]
