# Generated by Django 3.1.3 on 2021-01-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floorplan", "0013_auto_20200814_1818"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floorplan",
            name="simulation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="simulation.simulation",
                verbose_name="Simulation Result",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="simulation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="simulation.simulation",
                verbose_name="Simulation Result",
            ),
        ),
    ]
