# -*- coding: utf-8 -*-
# Generated by Django 4.0.6 on 2022-08-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floorplan", "0014_auto_20210104_1851"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemtype",
            name="company",
        ),
        migrations.AlterModelOptions(
            name="historicalfloorplan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Floorplan",
                "verbose_name_plural": "historical Floorplans",
            },
        ),
        migrations.RemoveField(
            model_name="floorplan",
            name="systems",
        ),
        migrations.AlterField(
            model_name="floorplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalfloorplan",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="System",
        ),
        migrations.DeleteModel(
            name="SystemType",
        ),
    ]
