# Generated by Django 4.1.7 on 2023-02-22 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("floorplan", "0015_remove_systemtype_company_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="floorplan",
            unique_together=set(),
        ),
    ]
