# Generated by Django 1.11.26 on 2020-05-18 17:28

from django.db import migrations, models, transaction

#: The 48 contiguous states, plus the District of Columbia.
CONTIGUOUS_STATES = (
    ("AL", "Alabama"),
    ("AZ", "Arizona"),
    ("AR", "Arkansas"),
    ("CA", "California"),
    ("CO", "Colorado"),
    ("CT", "Connecticut"),
    ("DE", "Delaware"),
    ("DC", "District of Columbia"),
    ("FL", "Florida"),
    ("GA", "Georgia"),
    ("ID", "Idaho"),
    ("IL", "Illinois"),
    ("IN", "Indiana"),
    ("IA", "Iowa"),
    ("KS", "Kansas"),
    ("KY", "Kentucky"),
    ("LA", "Louisiana"),
    ("ME", "Maine"),
    ("MD", "Maryland"),
    ("MA", "Massachusetts"),
    ("MI", "Michigan"),
    ("MN", "Minnesota"),
    ("MS", "Mississippi"),
    ("MO", "Missouri"),
    ("MT", "Montana"),
    ("NE", "Nebraska"),
    ("NV", "Nevada"),
    ("NH", "New Hampshire"),
    ("NJ", "New Jersey"),
    ("NM", "New Mexico"),
    ("NY", "New York"),
    ("NC", "North Carolina"),
    ("ND", "North Dakota"),
    ("OH", "Ohio"),
    ("OK", "Oklahoma"),
    ("OR", "Oregon"),
    ("PA", "Pennsylvania"),
    ("RI", "Rhode Island"),
    ("SC", "South Carolina"),
    ("SD", "South Dakota"),
    ("TN", "Tennessee"),
    ("TX", "Texas"),
    ("UT", "Utah"),
    ("VT", "Vermont"),
    ("VA", "Virginia"),
    ("WA", "Washington"),
    ("WV", "West Virginia"),
    ("WI", "Wisconsin"),
    ("WY", "Wyoming"),
)


@transaction.atomic
def create_us_states(apps, schema_editor):
    print("Create US States")
    USState = apps.get_model("geographic", "USState")
    db_alias = schema_editor.connection.alias

    us_states = []
    for state in CONTIGUOUS_STATES:
        us_states.append(USState(abbr=state[0], name=state[1]))

    USState.objects.using(db_alias).bulk_create(us_states)


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0002_auto_20190531_1224"),
    ]

    operations = [
        migrations.CreateModel(
            name="USState",
            fields=[
                ("abbr", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["abbr"],
                "verbose_name": "US State",
                "verbose_name_plural": "US States",
            },
        ),
        migrations.RunPython(create_us_states),
    ]
