# Generated by Django 3.1.8 on 2021-06-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0003_usstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="legal_statistical_area_description",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="city",
            name="place_fips",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("place_fips", "county")},
        ),
    ]
