# Generated by Django 1.11.16 on 2018-10-08 18:15

import axis.ekotrope.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[axis.ekotrope.validators.validate_id],
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500)),
                ("data", models.TextField(default=dict)),
                ("import_failed", models.BooleanField(default=False)),
                ("import_error", models.CharField(blank=True, max_length=500, null=True)),
                ("import_traceback", models.TextField(blank=True, null=True)),
                ("import_request", models.CharField(blank=True, max_length=500, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="EkotropeAuthDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="HousePlan",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[axis.ekotrope.validators.validate_id],
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500)),
                ("data", models.TextField(default=dict)),
                ("import_failed", models.BooleanField(default=False)),
                ("import_error", models.CharField(blank=True, max_length=500, null=True)),
                ("import_traceback", models.TextField(blank=True, null=True)),
                ("import_request", models.CharField(blank=True, max_length=500, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[axis.ekotrope.validators.validate_id],
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500)),
                ("data", models.TextField(default=dict)),
                ("import_failed", models.BooleanField(default=False)),
                ("import_error", models.CharField(blank=True, max_length=500, null=True)),
                ("import_traceback", models.TextField(blank=True, null=True)),
                ("import_request", models.CharField(blank=True, max_length=500, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="company.Company"
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddField(
            model_name="houseplan",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ekotrope.Project"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="houseplan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="ekotrope.HousePlan"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ekotrope.Project"
            ),
        ),
    ]
