# Generated by Django 1.11.16 on 2018-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ekotrope", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="houseplan",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="project",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
