# Generated by Django 1.11.16 on 2018-12-02 18:46

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ekotrope", "0003_auto_20181123_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="houseplan",
            name="data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="project",
            name="data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
    ]
