# Generated by Django 1.11.17 on 2019-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ekotrope", "0004_auto_20181202_1846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ekotropeauthdetails",
            name="username",
            field=models.CharField(max_length=64),
        ),
    ]
