# Generated by Django 1.11.26 on 2020-04-27 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ekotrope", "0005_auth_name_increase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ekotropeauthdetails",
            options={"verbose_name_plural": "Ekotrope Auth Details"},
        ),
    ]
