# Generated by Django 4.0.7 on 2022-09-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ekotrope", "0006_auto_20200427_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ekotropeauthdetails",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
