# Generated by Django 4.0.8 on 2022-11-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rpcvirtualmachine",
            options={"verbose_name": "Virtual Machine"},
        ),
        migrations.AlterField(
            model_name="hirlrpcupdaterrequest",
            name="rpc_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rpc.rpcsession",
            ),
        ),
        migrations.AlterField(
            model_name="rpcsession",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
