# Generated by Django 4.0.8 on 2022-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0002_alter_rpcvirtualmachine_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlrpcupdaterrequest",
            name="document",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
