# Generated by Django 4.0.8 on 2022-12-05 13:15

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0003_hirlrpcupdaterrequest_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlrpcupdaterrequest",
            name="async_document",
        ),
        migrations.AddField(
            model_name="hirlrpcupdaterrequest",
            name="result_document",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="hirlrpcupdaterrequest",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("success", "Success"),
                    ("error", "Error"),
                ],
                default="in_progress",
                max_length=50,
            ),
        ),
    ]
