# Generated by Django 4.0.8 on 2022-12-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0006_alter_hirlrpcupdaterrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlrpcupdaterrequest",
            name="task_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="rpcvirtualmachine",
            name="rdp_file",
            field=models.FileField(
                blank=True,
                help_text=".rdp file to connect via Microsoft Remote Desktop",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="rpcvirtualmachine",
            name="rdp_password",
            field=models.TextField(
                blank=True, help_text="Password to connect via Microsoft Remote Desktop"
            ),
        ),
    ]
