# Generated by Django 4.0.8 on 2023-01-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0007_hirlrpcupdaterrequest_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlrpcupdaterrequest",
            name="scoring_path",
            field=models.CharField(
                choices=[
                    ("2020_ngbs", "2020 New Construction"),
                    ("2020_ngbs_remodel", "2020 Remodel"),
                    ("2015_ngbs", "2015 New Construction"),
                ],
                default="2020_ngbs",
                max_length=48,
            ),
        ),
    ]
