# Generated by Django 4.0.8 on 2023-01-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0008_hirlrpcupdaterrequest_scoring_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlrpcupdaterrequest",
            name="project_type",
            field=models.CharField(
                choices=[("single_family", "Single Family"), ("multifamily", "Multifamily")],
                default="single_family",
                max_length=48,
            ),
        ),
    ]
