# Generated by Django 1.11.26 on 2020-01-23 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hes", "0002_auto_20191129_2256"),
    ]

    operations = [
        migrations.AddField(
            model_name="hessimulationstatus",
            name="northeast_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="northeast_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AddField(
            model_name="hessimulationstatus",
            name="northwest_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="northwest_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AddField(
            model_name="hessimulationstatus",
            name="southeast_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="southeast_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AddField(
            model_name="hessimulationstatus",
            name="southwest_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="southwest_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AddField(
            model_name="historicalhessimulationstatus",
            name="northeast_orientation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AddField(
            model_name="historicalhessimulationstatus",
            name="northwest_orientation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AddField(
            model_name="historicalhessimulationstatus",
            name="southeast_orientation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AddField(
            model_name="historicalhessimulationstatus",
            name="southwest_orientation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulation",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("north", "North"),
                    ("northeast", "Northeast"),
                    ("east", "East"),
                    ("southeast", "Southeast"),
                    ("south", "South"),
                    ("southwest", "Southwest"),
                    ("west", "West"),
                    ("northwest", "Northwest"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="worst_case_orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("north", "North"),
                    ("northeast", "Northeast"),
                    ("east", "East"),
                    ("southeast", "Southeast"),
                    ("south", "South"),
                    ("southwest", "Southwest"),
                    ("west", "West"),
                    ("northwest", "Northwest"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhessimulation",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("north", "North"),
                    ("northeast", "Northeast"),
                    ("east", "East"),
                    ("southeast", "Southeast"),
                    ("south", "South"),
                    ("southwest", "Southwest"),
                    ("west", "West"),
                    ("northwest", "Northwest"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhessimulationstatus",
            name="worst_case_orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("north", "North"),
                    ("northeast", "Northeast"),
                    ("east", "East"),
                    ("southeast", "Southeast"),
                    ("south", "South"),
                    ("southwest", "Southwest"),
                    ("west", "West"),
                    ("northwest", "Northwest"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
