# Generated by Django 1.11.26 on 2020-04-15 15:40

import axis.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hes", "0003_auto_20200123_2117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hescredentials",
            name="password",
            field=axis.core.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="hescredentials",
            name="username",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="historicalhescredentials",
            name="password",
            field=axis.core.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalhescredentials",
            name="username",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
