# Generated by Django 1.11.26 on 2020-07-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hes", "0004_auto_20200415_1540"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="east_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="east_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="north_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="north_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="northeast_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="northeast_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="northwest_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="northwest_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="south_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="south_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="southeast_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="southeast_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="southwest_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="southwest_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="west_orientation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="west_status",
                to="hes.HESSimulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="worst_case_simulation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worst_case_status",
                to="hes.HESSimulation",
            ),
        ),
    ]
