# Generated by Django 3.1.3 on 2020-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hes", "0005_auto_20200702_1803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hessimulation",
            name="cooling_present",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhessimulation",
            name="cooling_present",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
