# Generated by Django 3.2.14 on 2022-07-20 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("simulation", "0036_historicalwatersystem_qty_recirculation_shower_heads_and_more"),
        ("hes", "0007_auto_20220222_2245"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalhescredentials",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical hes credentials",
                "verbose_name_plural": "historical hes credentialss",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhessimulation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical hes simulation",
                "verbose_name_plural": "historical hes simulations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhessimulationstatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical HES Simulation",
                "verbose_name_plural": "historical HES Simulations",
            },
        ),
        migrations.RemoveField(
            model_name="hessimulation",
            name="company",
        ),
        migrations.RemoveField(
            model_name="hessimulation",
            name="rem_simulation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="building_id",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="company",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="is_certified",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="northeast_orientation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="northwest_orientation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="southeast_orientation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="southwest_orientation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="state_changed_at",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="status",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulation",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulation",
            name="rem_simulation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="building_id",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="is_certified",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="northeast_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="northwest_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="southeast_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="southwest_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="state_changed_at",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="status",
        ),
        migrations.AddField(
            model_name="hessimulationstatus",
            name="simulation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hes_score_statuses",
                to="simulation.simulation",
            ),
        ),
        migrations.AddField(
            model_name="historicalhessimulationstatus",
            name="simulation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="simulation.simulation",
            ),
        ),
        migrations.AlterField(
            model_name="hessimulation",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("north", "North"),
                    ("northeast", "Northeast"),
                    ("east", "East"),
                    ("southeast", "Southeast"),
                    ("south", "South"),
                    ("southwest", "Southwest"),
                    ("west", "West"),
                    ("northwest", "Northwest"),
                    ("unknown", "Unknown"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hessimulationstatus",
            name="worst_case_orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("north", "North"),
                    ("northeast", "Northeast"),
                    ("east", "East"),
                    ("southeast", "Southeast"),
                    ("south", "South"),
                    ("southwest", "Southwest"),
                    ("west", "West"),
                    ("northwest", "Northwest"),
                    ("unknown", "Unknown"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhescredentials",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhessimulation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhessimulation",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("north", "North"),
                    ("northeast", "Northeast"),
                    ("east", "East"),
                    ("southeast", "Southeast"),
                    ("south", "South"),
                    ("southwest", "Southwest"),
                    ("west", "West"),
                    ("northwest", "Northwest"),
                    ("unknown", "Unknown"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhessimulationstatus",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhessimulationstatus",
            name="worst_case_orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("north", "North"),
                    ("northeast", "Northeast"),
                    ("east", "East"),
                    ("southeast", "Southeast"),
                    ("south", "South"),
                    ("southwest", "Southwest"),
                    ("west", "West"),
                    ("northwest", "Northwest"),
                    ("unknown", "Unknown"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
