# Generated by Django 4.0.7 on 2022-10-10 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hes", "0008_auto_20220720_2310"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="hpxml",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="hpxml",
        ),
    ]
