# Generated by Django 4.0.8 on 2022-11-08 15:12 and directly thereafter lovingly customized by Benjamin S

from django.db import migrations, models, connection
import django.db.models.deletion


def get_status_remap_sql(sim_status_table: str, sim_table: str):
    return f"""
        UPDATE {sim_status_table} hes_sim_status

    INNER JOIN {sim_table} hes_sim
            ON hes_sim.id IN (
               hes_sim_status.north_orientation_id,
               hes_sim_status.south_orientation_id,
               hes_sim_status.east_orientation_id,
               hes_sim_status.west_orientation_id
             )

           SET hes_sim.simulation_status_id = hes_sim_status.id
    """


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_alter_eepprogramhomestatus_home_and_more"),
        ("hes", "0009_remove_hessimulationstatus_hpxml_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hessimulation",
            name="simulation_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hes_simulations",
                to="hes.hessimulationstatus",
            ),
        ),
        migrations.AddField(
            model_name="historicalhessimulation",
            name="simulation_status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hes.hessimulationstatus",
            ),
        ),
        # We are reversing the relationship here, so instead of hes_hessimulationstatus holding four fields each pointing
        # to one hes_hessimulation, we instead have an hes_hessimulationstatus ID in hes_hessimulation - that lets us
        # have any number of orientations instead of the four that previously were supported. To avoid losing data,
        # here we have to set that new foreign key in hes_hessimulation before the old fields that used to define
        # the relationship in the opposite direction are dropped.
        migrations.RunSQL(get_status_remap_sql("hes_hessimulationstatus", "hes_hessimulation")),
        migrations.RunSQL(
            get_status_remap_sql("hes_historicalhessimulationstatus", "hes_historicalhessimulation")
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="east_orientation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="north_orientation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="south_orientation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="west_orientation",
        ),
        migrations.RemoveField(
            model_name="hessimulationstatus",
            name="worst_case_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="east_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="north_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="south_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="west_orientation",
        ),
        migrations.RemoveField(
            model_name="historicalhessimulationstatus",
            name="worst_case_orientation",
        ),
        migrations.AlterUniqueTogether(
            name="hessimulation",
            unique_together={("simulation_status", "orientation")},
        ),
    ]
