"""Django AEC Models - Theses are the source data coming in on the rate database."""


import logging

from django.db import models

__author__ = "Steven Klass"
__date__ = "06/09/2019 13:51"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = [
    "Steven Klass",
]

log = logging.getLogger(__name__)


class IECC(models.Model):
    """Results of IECC Data"""

    result_number = models.IntegerField(null=True, blank=True, db_column="LBLDGRUNNO")
    rating_number = models.CharField(max_length=93, db_column="SRATENO", blank=True)
    F98IERHCN = models.FloatField(null=True, blank=True, db_column="F98IERHCN")
    F98IERCCN = models.FloatField(null=True, blank=True, db_column="F98IERCCN")
    F98IERDCN = models.FloatField(null=True, blank=True, db_column="F98IERDCN")
    F98IERLACN = models.FloatField(null=True, blank=True, db_column="F98IERLACN")
    F98IERPVCN = models.FloatField(null=True, blank=True, db_column="F98IERPVCN")
    F98IERTCN = models.FloatField(null=True, blank=True, db_column="F98IERTCN")
    F98IEDHCN = models.FloatField(null=True, blank=True, db_column="F98IEDHCN")
    F98IEDCCN = models.FloatField(null=True, blank=True, db_column="F98IEDCCN")
    F98IEDDCN = models.FloatField(null=True, blank=True, db_column="F98IEDDCN")
    F98IEDLACN = models.FloatField(null=True, blank=True, db_column="F98IEDLACN")
    F98IEDPVCN = models.FloatField(null=True, blank=True, db_column="F98IEDPVCN")
    F98IEDTCN = models.FloatField(null=True, blank=True, db_column="F98IEDTCN")
    B98IECC = models.FloatField(null=True, blank=True, db_column="B98IECC")
    F98IECCRUO = models.FloatField(null=True, blank=True, db_column="F98IECCRUO")
    F98IECCDUO = models.FloatField(null=True, blank=True, db_column="F98IECCDUO")
    B98IECCDUP = models.BooleanField(null=True, blank=True, db_column="B98IECCDUP")
    B98IECCUOP = models.BooleanField(null=True, blank=True, db_column="B98IECCUOP")
    F00IERHCN = models.FloatField(null=True, blank=True, db_column="F00IERHCN")
    F00IERCCN = models.FloatField(null=True, blank=True, db_column="F00IERCCN")
    F00IERDCN = models.FloatField(null=True, blank=True, db_column="F00IERDCN")
    F00IERLACN = models.FloatField(null=True, blank=True, db_column="F00IERLACN")
    F00IERPVCN = models.FloatField(null=True, blank=True, db_column="F00IERPVCN")
    F00IERTCN = models.FloatField(null=True, blank=True, db_column="F00IERTCN")
    F00IEDHCN = models.FloatField(null=True, blank=True, db_column="F00IEDHCN")
    F00IEDCCN = models.FloatField(null=True, blank=True, db_column="F00IEDCCN")
    F00IEDDCN = models.FloatField(null=True, blank=True, db_column="F00IEDDCN")
    F00IEDLACN = models.FloatField(null=True, blank=True, db_column="F00IEDLACN")
    F00IEDPVCN = models.FloatField(null=True, blank=True, db_column="F00IEDPVCN")
    F00IEDTCN = models.FloatField(null=True, blank=True, db_column="F00IEDTCN")
    B00IECC = models.FloatField(null=True, blank=True, db_column="B00IECC")
    F00IECCRUO = models.FloatField(null=True, blank=True, db_column="F00IECCRUO")
    F00IECCDUO = models.FloatField(null=True, blank=True, db_column="F00IECCDUO")
    B00IECCDUP = models.BooleanField(null=True, blank=True, db_column="B00IECCDUP")
    B00IECCUOP = models.BooleanField(null=True, blank=True, db_column="B00IECCUOP")
    F01IERHCN = models.FloatField(null=True, blank=True, db_column="F01IERHCN")
    F01IERCCN = models.FloatField(null=True, blank=True, db_column="F01IERCCN")
    F01IERDCN = models.FloatField(null=True, blank=True, db_column="F01IERDCN")
    F01IERLACN = models.FloatField(null=True, blank=True, db_column="F01IERLACN")
    F01IERPVCN = models.FloatField(null=True, blank=True, db_column="F01IERPVCN")
    F01IERTCN = models.FloatField(null=True, blank=True, db_column="F01IERTCN")
    F01IEDHCN = models.FloatField(null=True, blank=True, db_column="F01IEDHCN")
    F01IEDCCN = models.FloatField(null=True, blank=True, db_column="F01IEDCCN")
    F01IEDDCN = models.FloatField(null=True, blank=True, db_column="F01IEDDCN")
    F01IEDLACN = models.FloatField(null=True, blank=True, db_column="F01IEDLACN")
    F01IEDPVCN = models.FloatField(null=True, blank=True, db_column="F01IEDPVCN")
    F01IEDTCN = models.FloatField(null=True, blank=True, db_column="F01IEDTCN")
    B01IECC = models.FloatField(null=True, blank=True, db_column="B01IECC")
    F01IECCRUO = models.FloatField(null=True, blank=True, db_column="F01IECCRUO")
    F01IECCDUO = models.FloatField(null=True, blank=True, db_column="F01IECCDUO")
    B01IECCDUP = models.BooleanField(null=True, blank=True, db_column="B01IECCDUP")
    B01IECCUOP = models.BooleanField(null=True, blank=True, db_column="B01IECCUOP")
    F03IERHCN = models.FloatField(null=True, blank=True, db_column="F03IERHCN")
    F03IERCCN = models.FloatField(null=True, blank=True, db_column="F03IERCCN")
    F03IERDCN = models.FloatField(null=True, blank=True, db_column="F03IERDCN")
    F03IERLACN = models.FloatField(null=True, blank=True, db_column="F03IERLACN")
    F03IERPVCN = models.FloatField(null=True, blank=True, db_column="F03IERPVCN")
    F03IERTCN = models.FloatField(null=True, blank=True, db_column="F03IERTCN")
    F03IEDHCN = models.FloatField(null=True, blank=True, db_column="F03IEDHCN")
    F03IEDCCN = models.FloatField(null=True, blank=True, db_column="F03IEDCCN")
    F03IEDDCN = models.FloatField(null=True, blank=True, db_column="F03IEDDCN")
    F03IEDLACN = models.FloatField(null=True, blank=True, db_column="F03IEDLACN")
    F03IEDPVCN = models.FloatField(null=True, blank=True, db_column="F03IEDPVCN")
    F03IEDTCN = models.FloatField(null=True, blank=True, db_column="F03IEDTCN")
    B03IECC = models.FloatField(null=True, blank=True, db_column="B03IECC")
    F03IECCRUO = models.FloatField(null=True, blank=True, db_column="F03IECCRUO")
    F03IECCDUO = models.FloatField(null=True, blank=True, db_column="F03IECCDUO")
    B03IECCDUP = models.BooleanField(null=True, blank=True, db_column="B03IECCDUP")
    B03IECCUOP = models.BooleanField(null=True, blank=True, db_column="B03IECCUOP")
    F04IERHCT = models.FloatField(null=True, blank=True, db_column="F04IERHCT")
    F04IERCCT = models.FloatField(null=True, blank=True, db_column="F04IERCCT")
    F04IERDCT = models.FloatField(null=True, blank=True, db_column="F04IERDCT")
    F04IERLACT = models.FloatField(null=True, blank=True, db_column="F04IERLACT")
    F04IERPVCT = models.FloatField(null=True, blank=True, db_column="F04IERPVCT")
    F04IERSVCT = models.FloatField(null=True, blank=True, db_column="F04IERSVCT")
    F04IERTCT = models.FloatField(null=True, blank=True, db_column="F04IERTCT")
    F04IEDHCT = models.FloatField(null=True, blank=True, db_column="F04IEDHCT")
    F04IEDCCT = models.FloatField(null=True, blank=True, db_column="F04IEDCCT")
    F04IEDDCT = models.FloatField(null=True, blank=True, db_column="F04IEDDCT")
    F04IEDLACT = models.FloatField(null=True, blank=True, db_column="F04IEDLACT")
    F04IEDPVCT = models.FloatField(null=True, blank=True, db_column="F04IEDPVCT")
    F04IEDSVCT = models.FloatField(null=True, blank=True, db_column="F04IEDSVCT")
    F04IEDTCT = models.FloatField(null=True, blank=True, db_column="F04IEDTCT")
    B04IECC = models.FloatField(null=True, blank=True, db_column="B04IECC")
    F04IECCRUA = models.FloatField(null=True, blank=True, db_column="F04IECCRUA")
    F04IECCDUA = models.FloatField(null=True, blank=True, db_column="F04IECCDUA")
    B04IECCDUP = models.BooleanField(null=True, blank=True, db_column="B04IECCDUP")
    B04IECCUAP = models.BooleanField(null=True, blank=True, db_column="B04IECCUAP")
    bPass04IECC = models.BooleanField(default=False, db_column="bPass04IECC")
    F06IERHCT = models.FloatField(null=True, blank=True, db_column="F06IERHCT")
    F06IERCCT = models.FloatField(null=True, blank=True, db_column="F06IERCCT")
    F06IERDCT = models.FloatField(null=True, blank=True, db_column="F06IERDCT")
    F06IERLACT = models.FloatField(null=True, blank=True, db_column="F06IERLACT")
    F06IERPVCT = models.FloatField(null=True, blank=True, db_column="F06IERPVCT")
    F06IERSVCT = models.FloatField(null=True, blank=True, db_column="F06IERSVCT")
    F06IERTCT = models.FloatField(null=True, blank=True, db_column="F06IERTCT")
    F06IEDHCT = models.FloatField(null=True, blank=True, db_column="F06IEDHCT")
    F06IEDCCT = models.FloatField(null=True, blank=True, db_column="F06IEDCCT")
    F06IEDDCT = models.FloatField(null=True, blank=True, db_column="F06IEDDCT")
    F06IEDLACT = models.FloatField(null=True, blank=True, db_column="F06IEDLACT")
    F06IEDPVCT = models.FloatField(null=True, blank=True, db_column="F06IEDPVCT")
    F06IEDSVCT = models.FloatField(null=True, blank=True, db_column="F06IEDSVCT")
    F06IEDTCT = models.FloatField(null=True, blank=True, db_column="F06IEDTCT")
    B06IECC = models.FloatField(null=True, blank=True, db_column="B06IECC")
    F06IECCRUA = models.FloatField(null=True, blank=True, db_column="F06IECCRUA")
    F06IECCDUA = models.FloatField(null=True, blank=True, db_column="F06IECCDUA")
    B06IECCDUP = models.BooleanField(null=True, blank=True, db_column="B06IECCDUP")
    B06IECCUAP = models.BooleanField(null=True, blank=True, db_column="B06IECCUAP")
    bPass06IECC = models.BooleanField(default=False, db_column="bPass06IECC")
    F09IERHCT = models.FloatField(null=True, blank=True, db_column="F09IERHCT")
    F09IERCCT = models.FloatField(null=True, blank=True, db_column="F09IERCCT")
    F09IERDCT = models.FloatField(null=True, blank=True, db_column="F09IERDCT")
    F09IERLACT = models.FloatField(null=True, blank=True, db_column="F09IERLACT")
    F09IERPVCT = models.FloatField(null=True, blank=True, db_column="F09IERPVCT")
    F09IERSVCT = models.FloatField(null=True, blank=True, db_column="F09IERSVCT")
    F09IERTCT = models.FloatField(null=True, blank=True, db_column="F09IERTCT")
    F09IEDHCT = models.FloatField(null=True, blank=True, db_column="F09IEDHCT")
    F09IEDCCT = models.FloatField(null=True, blank=True, db_column="F09IEDCCT")
    F09IEDDCT = models.FloatField(null=True, blank=True, db_column="F09IEDDCT")
    F09IEDLACT = models.FloatField(null=True, blank=True, db_column="F09IEDLACT")
    F09IEDPVCT = models.FloatField(null=True, blank=True, db_column="F09IEDPVCT")
    F09IEDSVCT = models.FloatField(null=True, blank=True, db_column="F09IEDSVCT")
    F09IEDTCT = models.FloatField(null=True, blank=True, db_column="F09IEDTCT")
    B09IECC = models.FloatField(null=True, blank=True, db_column="B09IECC")
    F09IECCRUA = models.FloatField(null=True, blank=True, db_column="F09IECCRUA")
    F09IECCDUA = models.FloatField(null=True, blank=True, db_column="F09IECCDUA")
    B09IECCDUP = models.BooleanField(null=True, blank=True, db_column="B09IECCDUP")
    B09IECCUAP = models.BooleanField(null=True, blank=True, db_column="B09IECCUAP")
    bPass09IECC = models.BooleanField(default=False, db_column="bPass09IECC")
    F12IERHCT = models.FloatField(null=True, blank=True, db_column="F12IERHCT")
    F12IERCCT = models.FloatField(null=True, blank=True, db_column="F12IERCCT")
    F12IERDCT = models.FloatField(null=True, blank=True, db_column="F12IERDCT")
    F12IERLACT = models.FloatField(null=True, blank=True, db_column="F12IERLACT")
    F12IERPVCT = models.FloatField(null=True, blank=True, db_column="F12IERPVCT")
    F12IERSVCT = models.FloatField(null=True, blank=True, db_column="F12IERSVCT")
    F12IERTCT = models.FloatField(null=True, blank=True, db_column="F12IERTCT")
    F12IEDHCT = models.FloatField(null=True, blank=True, db_column="F12IEDHCT")
    F12IEDCCT = models.FloatField(null=True, blank=True, db_column="F12IEDCCT")
    F12IEDDCT = models.FloatField(null=True, blank=True, db_column="F12IEDDCT")
    F12IEDLACT = models.FloatField(null=True, blank=True, db_column="F12IEDLACT")
    F12IEDPVCT = models.FloatField(null=True, blank=True, db_column="F12IEDPVCT")
    F12IEDSVCT = models.FloatField(null=True, blank=True, db_column="F12IEDSVCT")
    F12IEDTCT = models.FloatField(null=True, blank=True, db_column="F12IEDTCT")
    B12IECC = models.FloatField(null=True, blank=True, db_column="B12IECC")
    F12IECCRUA = models.FloatField(null=True, blank=True, db_column="F12IECCRUA")
    F12IECCDUA = models.FloatField(null=True, blank=True, db_column="F12IECCDUA")
    B12IECCDUP = models.BooleanField(null=True, blank=True, db_column="B12IECCDUP")
    B12IECCUAP = models.BooleanField(null=True, blank=True, db_column="B12IECCUAP")
    bPass12IECC = models.BooleanField(default=False, db_column="bPass12IECC")
    F15IERHCT = models.FloatField(null=True, blank=True, db_column="F15IERHCT")
    F15IERCCT = models.FloatField(null=True, blank=True, db_column="F15IERCCT")
    F15IERDCT = models.FloatField(null=True, blank=True, db_column="F15IERDCT")
    F15IERLACT = models.FloatField(null=True, blank=True, db_column="F15IERLACT")
    F15IERPVCT = models.FloatField(null=True, blank=True, db_column="F15IERPVCT")
    F15IERSVCT = models.FloatField(null=True, blank=True, db_column="F15IERSVCT")
    F15IERTCT = models.FloatField(null=True, blank=True, db_column="F15IERTCT")
    F15IEDHCT = models.FloatField(null=True, blank=True, db_column="F15IEDHCT")
    F15IEDCCT = models.FloatField(null=True, blank=True, db_column="F15IEDCCT")
    F15IEDDCT = models.FloatField(null=True, blank=True, db_column="F15IEDDCT")
    F15IEDLACT = models.FloatField(null=True, blank=True, db_column="F15IEDLACT")
    F15IEDPVCT = models.FloatField(null=True, blank=True, db_column="F15IEDPVCT")
    F15IEDSVCT = models.FloatField(null=True, blank=True, db_column="F15IEDSVCT")
    F15IEDTCT = models.FloatField(null=True, blank=True, db_column="F15IEDTCT")
    B15IECC = models.BooleanField(null=True, blank=True, db_column="B15IECC")
    F15IECCRUA = models.FloatField(null=True, blank=True, db_column="F15IECCRUA")
    F15IECCDUA = models.FloatField(null=True, blank=True, db_column="F15IECCDUA")
    B15IECCDUP = models.BooleanField(null=True, blank=True, db_column="B15IECCDUP")
    B15IECCUAP = models.BooleanField(null=True, blank=True, db_column="B15IECCUAP")
    bPass15IECC = models.BooleanField(default=False, db_column="bPass15IECC")

    f18IERHCT = models.FloatField(null=True, blank=True, db_column="f18IERHCT")
    f18IERCCT = models.FloatField(null=True, blank=True, db_column="f18IERCCT")
    f18IERDCT = models.FloatField(null=True, blank=True, db_column="f18IERDCT")
    f18IERLACT = models.FloatField(null=True, blank=True, db_column="f18IERLACT")
    f18IERPVCT = models.FloatField(null=True, blank=True, db_column="f18IERPVCT")
    f18IERSVCT = models.FloatField(null=True, blank=True, db_column="f18IERSVCT")
    f18IERTCT = models.FloatField(null=True, blank=True, db_column="f18IERTCT")
    f18IEDHCT = models.FloatField(null=True, blank=True, db_column="f18IEDHCT")
    f18IEDCCT = models.FloatField(null=True, blank=True, db_column="f18IEDCCT")
    f18IEDDCT = models.FloatField(null=True, blank=True, db_column="f18IEDDCT")
    f18IEDLACT = models.FloatField(null=True, blank=True, db_column="f18IEDLACT")
    f18IEDPVCT = models.FloatField(null=True, blank=True, db_column="f18IEDPVCT")
    f18IEDSVCT = models.FloatField(null=True, blank=True, db_column="f18IEDSVCT")
    f18IEDTCT = models.FloatField(null=True, blank=True, db_column="f18IEDTCT")
    b18IECC = models.BooleanField(null=True, blank=True, db_column="b18IECC")
    f18IECCRUA = models.FloatField(null=True, blank=True, db_column="f18IECCRUA")
    f18IECCDUA = models.FloatField(null=True, blank=True, db_column="f18IECCDUA")
    b18IECCDuP = models.FloatField(null=True, blank=True, db_column="b18IECCDuP")
    b18IECCuAP = models.FloatField(null=True, blank=True, db_column="b18IECCuAP")
    bPass18IECC = models.BooleanField(null=True, blank=True, db_column="bPass18IECC")

    iecc18_reference_mv_cost = models.FloatField(null=True, blank=True, db_column="f18IERMVCT")
    iecc18_design_mv_cost = models.FloatField(null=True, blank=True, db_column="f18IEDMVCT")

    f21IERHCT = models.FloatField(null=True, blank=True, db_column="f21IERHCT")
    f21IERCCT = models.FloatField(null=True, blank=True, db_column="f21IERCCT")
    f21IERDCT = models.FloatField(null=True, blank=True, db_column="f21IERDCT")
    f21IERLACT = models.FloatField(null=True, blank=True, db_column="f21IERLACT")
    f21IERMVCT = models.FloatField(null=True, blank=True, db_column="f21IERMVCT")
    f21IERPVCT = models.FloatField(null=True, blank=True, db_column="f21IERPVCT")
    f21IERSVCT = models.FloatField(null=True, blank=True, db_column="f21IERSVCT")
    f21IERTCT = models.FloatField(null=True, blank=True, db_column="f21IERTCT")
    f21IEDHCT = models.FloatField(null=True, blank=True, db_column="f21IEDHCT")
    f21IEDCCT = models.FloatField(null=True, blank=True, db_column="f21IEDCCT")
    f21IEDDCT = models.FloatField(null=True, blank=True, db_column="f21IEDDCT")
    f21IEDLACT = models.FloatField(null=True, blank=True, db_column="f21IEDLACT")
    f21IEDMVCT = models.FloatField(null=True, blank=True, db_column="f21IEDMVCT")
    f21IEDPVCT = models.FloatField(null=True, blank=True, db_column="f21IEDPVCT")
    f21IEDSVCT = models.FloatField(null=True, blank=True, db_column="f21IEDSVCT")
    f21IEDTCT = models.FloatField(null=True, blank=True, db_column="f21IEDTCT")
    b21IECC = models.BooleanField(null=True, blank=True, db_column="b21IECC")
    f21IECCRUA = models.FloatField(null=True, blank=True, db_column="f21IECCRUA")
    f21IECCDUA = models.FloatField(null=True, blank=True, db_column="f21IECCDUA")
    b21IECCDuP = models.BooleanField(null=True, blank=True, db_column="b21IECCDuP")
    b21IECCuAP = models.BooleanField(null=True, blank=True, db_column="b21IECCuAP")
    bPass21IECC = models.BooleanField(null=True, default=False, db_column="bPass21IECC")

    class Meta:
        db_table = "IECC"
        managed = False
