DELIMITER $$
DROP TRIGGER IF EXISTS `after_simulation_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_utilityrates_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_seasonalrate_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_block_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_building_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_project_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_bldginfo_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_foundationwalltype_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_foundationwall_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_slabtype_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_slab_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_compositeinsulation_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_heatpath_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_ceilingtype_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_roof_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_walltype_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_abovegradewall_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_framefloortype_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_framefloor_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_joist_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_doortype_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_door_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_windowtype_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_window_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_skylight_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_generalmechanicalequipment_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_heater_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_airconditioner_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_hotwaterheater_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_groundsourceheatpump_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_airsourceheatpump_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_dualfuelheatpump_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_integratedspacewaterheater_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_dehumidifier_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_sharedequipment_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_waterloopheatpump_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_installedequipment_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_gshpwell_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_hotwaterdistribution_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_hvaccommissioning_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_ductsystem_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_duct_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_infiltration_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_ventilation_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_lightsandappliance_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_lainst_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_mandreq_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_doechallenge_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_addmass_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_solarsystem_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_photovoltaic_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_sunspace_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_ssmass_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_sscmnwal_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_sswindow_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_sssklght_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_resnetdisc_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_esrequire_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_fuelsummary_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_economicparam_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_result_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_compliance_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_regionalcode_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_hers_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_energystar_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_iecc_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_costrate_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_accmeas_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_rejmeas_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_econ_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_simpinp_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_nevmeas_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_florida_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_hercinfo_copy_trigger` $$
DROP TRIGGER IF EXISTS `after_site_copy_trigger` $$
DELIMITER ;
