"""__init__.py: Django customer_appraisal_institute package container"""


__author__ = "Steven Klass"
__version__ = "78.1.0"
__version_info__ = (78, 1, 0)
__date__ = "6/2/13 9:01 AM"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = ["Steven Klass", "Michael Jeffrey"]
__license__ = "See the file LICENSE.txt for licensing information."

GEEA_FAKE_DATA = {
    # recurring
    "client_file_num": "123456789",
    "appraisal_file_num": "987654321",
    "Client": "Test McTesterson",
    "Subject Property": "1234 Test Drive",
    "Completed by": "By",
    "Completed Title": "Title",
    "Completed Date": "11/22/1999",
    # Page 1
    "City": "one",
    "state": "two",
    "zipcode": "three",
    "Indoor airPLUS": True,
    "WaterSense": True,
    "ENERGY STAR": True,
    "Zero Energy Ready Home ZERH": True,
    "NGBS Bronze": True,
    "NGBS Silver": True,
    "NGBS Gold": True,
    "NGBS Emerald": True,
    "Living Building Certified": True,
    "Petal Certification": True,
    "PHI Low Energy": True,
    "Enerphit": True,
    "Passive House": True,
    "PHIUS 2015": True,
    "LEED Certified": True,
    "LEED Silver": True,
    "LEED Gold": True,
    "LEED Platinum": True,
    "Green Certification Other": "four",
    "Green Certification Date Verified Day": "five",
    "Green Certification Date Verified Month": "six",
    "Green Certification Date Verified Year": "seven",
    "Green Certification Version": "eight",
    "Green Certification Organization URL": "nine",
    "Green Certification Verification reviewed on site": True,
    "Green Certification Verification attached to this report": True,
    "HERS Rating": "eleven",
    "Sampling Rating": True,
    "Projected Rating": True,
    "Confirmed Rating": True,
    "HERS Estimated energy savings per year": "twelve",
    "HERS Estimated energy savings per kwh": "thirteen",
    "HERS rate dated Month": "fourteen",
    "HERS rate dated Day": "fifteen",
    "HERS rate dated Year": "sixteen",
    "DOE Score": "seventeen",
    "DOE Official Score": True,
    "DOE Unofficial Score": True,
    "DOE Estimated energy savings per year": "eighteen",
    "DOE Estimated energy savings per kwh": "nineteen",
    "DOE rate dated Month": "twenty",
    "DOE rate dated Day": "twenty one",
    "DOE rate dated Year": "twenty two",
    "Other Energy Score Range Start": "twenty three",
    "Other Energy Score Range End": "twenty four",
    "Other Energy Score": "twenty five",
    "Other Estimated energy savings per year": "twenty six",
    "Other Estimated energy savings per kwh": "twenty seven",
    "Other rate dated Month": "twenty eight",
    "Other rate dated Day": "twenty nine",
    "Other rate dated Year": "thirty",
    "Other Energy Label System": "one hundred twenty nine",
    "Energy Label Date Verified Month": "thirty one",
    "Energy Label Date Verified Day": "thirty two",
    "Energy Label Date Verified Year": "thirty three",
    "Energy Label Score or Rating Version": "thirty four",
    "Energy Label Organization URL RESNET": True,
    "Energy Label Organization URL Home Energy Score": True,
    "Energy Label Organization URL Other": True,
    "Energy Label Organization URL Other Value": "thirty five",
    "Energy Label Verification reviewed on site": True,
    "Energy Label Verification attached to this report": True,
    "Energy Related Improvements": "one hundred twenty eight",
    "Cost of Improvements": "thirty six",
    "Verified Energy Improvements Date Verified Month": "thirty seven",
    "Verified Energy Improvements Date Verified Day": "thirty eight",
    "Verified Energy Improvements Date Verified Year": "thirty nine",
    "Verified Energy Improvements Score or Rating Version": "forty",
    "Verified Energy Improvements Organization URL energystar": True,
    "Verified Energy Improvements Organization URL Other": True,
    "Verified Energy Improvements Organization URL Other Value": "forty one",
    "Verified Energy Improvements Verification reviewed on site": True,
    "Verified Energy Improvements Verification attached to this report": True,
    # Page 2
    "Fiberglass BlownIn": True,
    "Foam Insulation": True,
    "Cellulose": True,
    "Fiberglass Batt Insulation": True,
    "RValue": True,
    "RValue Wall": "forty two",
    "RValue Ceiling": "forty three",
    "Insulation Other": True,
    "Insulation Other Describe": "forty four",
    "Envelope Tightness": "forty five",
    "CFM25": True,
    "CFM25 Value": "forty six",
    "CFM50": True,
    "CFM50 Value": "forty seven",
    "ACH50": True,
    "ACH50 Value": "forty eight",
    "ACH Natural": True,
    "ACH Natural Value": "forty nine",
    "Windows ENERGY STAR": True,
    "Windows Low E": True,
    "Windows High Impact": True,
    "Windows Storm": True,
    "Windows Double Pane": True,
    "Windows Triple Pane": True,
    "Windows Tinted": True,
    "Windows Solar Shades": True,
    "Num of Skylights": "fifty",
    "Num of Solar Tubes": "fifty one",
    "Day Lighting Other": "fifty two",
    "Day Lighting LEDS": "fifty three",
    "Appliances ENERGY STAR Dishwasher": True,
    "Appliances ENERGY STAR Refrigerator": True,
    "Appliances ENERGY STAR WasherDryer": True,
    "Appliances ENERGY STAR Other": True,
    "Appliances ENERGY STAR Other Value": "fifty four",
    "Appliances Source Propane": True,
    "Appliances Source Electric": True,
    "Appliances Source Natural Gas": True,
    "Appliances Source Other": True,
    "Appliances Source Other Value": "fifty five",
    "Water Heater ENERGY STAR": True,
    "Water Heater Size": "fifty six",
    "Water Heater Tankless": True,
    "Water Heater Solar": True,
    "Water Heater Heat Pump": True,
    "Water Heater Coil": True,
    "High Efficiency HVAC": True,
    "High Efficiency HVAC SEER": "fifty seven",
    "High Efficiency HVAC Efficiency Rating": "fifty eight",
    "High Efficiency HVAC AFUE": "fifty nine",
    "Heat Pump Efficiency Rating": True,
    "Heat Pump Efficiency Rating COP": "sixty",
    "Heat Pump Efficiency Rating HSPF": "sixty one",
    "Heat Pump Efficiency Rating SEER": "sixty two",
    "Heat Pump Efficiency Rating EER": "sixty three",
    "Thermostat Controllers": True,
    "Programmable Thermostat": True,
    "Auxiliary heat source": True,
    "Radiant Floor Heat": True,
    "Geothermal": True,
    "Electric Vehicle Ready": True,
    "Indoor Environmental Quality ERV or HRV": True,
    "Indoor Environmental Quality Other": True,
    "Indoor Environmental Quality Humidity Monitoring": True,
    "Non Toxic Pest Control": True,
    "Radon System": True,
    "Radon System Active": True,
    "Radon System Passive": True,
    "Reclaimed Water System": True,
    "Reclaimed Water System Describe": "sixty four",
    "Greywater reuse system": True,
    "Water Saving Fixtures": True,
    "Rain Barrels Used in Irrigation": True,
    "Cistern size": "sixty five",
    "Location of cistern": "sixty six",
    "Utility Costs per year": "sixty seven",
    "Utility Costs Start Month": "sixty eight",
    "Utility Costs Start Day": "sixty nine",
    "Utility Costs Start Year": "seventy",
    "Utility Costs End Month": "seventy one",
    "Utility Costs End Day": "seventy two",
    "Utility Costs End Year": "seventy three",
    "Utility Costs Electric": True,
    "Utility Costs Heating": True,
    "Utility Costs Water": True,
    "Utility Costs Other": True,
    "Utility Costs Other Value": "seventy four",
    "Num of Occupants": "seventy five",
    "Efficiency Features Comments": "seventy six",
    # Page 3
    "Type of Ownership Array 1 Leased": True,
    "Type of Ownership Array 1 Owned": True,
    "Type of Ownership Array 1 Solar Loan with UCC Filing": True,
    "Type of Ownership Array 1 Power Purchase Agreement PPA": True,
    "Type of Ownership Array 2 Leased": True,
    "Type of Ownership Array 2 Owned": True,
    "Type of Ownership Array 2 Solar Loan": True,
    "Type of Ownership Array 2 UCC Filing": True,
    "Type of Ownership Array 2 PPA": True,
    "Array 1 System Size": "seventy seven",
    "Array 1 Age of Panels": "seventy eight",
    "Array 1 Energy Production": "seventy nine",
    "Array 1 Source of Energy Production Estimate": "eighty",
    "Array 1 Manufacturer": "eighty one",
    "Array 1 Warranty on Panels": "eighty two",
    "Array 2 System Size": "eighty three",
    "Array 2 Age of Panels": "eighty four",
    "Array 2 Energy Production": "eighty five",
    "Array 2 Source of Energy Production Estimate": "eighty six",
    "Array 2 Manufacturer": "eighty seven",
    "Array 2 Warranty on Panels": "eighty eight",
    "Array 1 Location": "eighty nine",
    "Array 1 Fixed Mount": True,
    "Array 1 Tracking Mount": True,
    "Array 1 Tilt Slope": "ninety",
    "Array 1 Azimuth": "ninety one",
    "Array 2 Location": "ninety two",
    "Array 2 Tilt Slope": "ninety three",
    "Array 2 Azimuth": "ninety four",
    "Array 2 Orientation": "ninety five",
    "Array 1 Number of Inverters": "ninety six",
    "Array 1 Age": "ninety seven",
    "Array 1 Wattage": "ninety eight",
    "Array 1 Inverter Manufacturer": "ninety nine",
    "Array 1 Warranty Term": "one hundred",
    "Array 2 Number of Inverters": "one hundred one",
    "Array 2 Age": "one hundred two",
    "Array 2 Wattage": "one hundred three",
    "Array 2 Inverter Manufacturer": "one hundred four",
    "Array 2 Warranty Term": "one hundred five",
    "Battery Type Lithium-ion": True,
    "Battery Type Lithium-ion Polymer": True,
    "Battery Type Lead Acid": True,
    "Battery Type Lead Calcium": True,
    "Battery Type AGM": True,
    "Battery Type GEL": True,
    "Battery Manufacturer": "one hundred six",
    "Battery Storage Capacity": "one hundred seven",
    "Battery Warranty": "one hundred eight",
    "Battery Age": "one hundred nine",
    "Name of Utility Company": "one hundred ten",
    "Charge from Utility per kwh": "one hundred eleven",
    "Type of System Active Direct": True,
    "Type of System Active Indirect": True,
    "Type of System Inactive Integral collector": True,
    "Type of System Inactive Thermosyphon": True,
    "Storage Tank Size": "one hundred twelve",
    "Collector Type Flat-Plat": True,
    "Collector Type Integral": True,
    "Collector Type Evacuated-Tube Solar": True,
    "System Age": "one hundred thirteen",
    "Backup System Conventional Water Heater": True,
    "Backup System Tankless On Demand": True,
    "Backup System Tankless Heat Pump": True,
    "Warranty Term": "one hundred fourteen",
    "Solar Energy Factor": "one hundred fifteen",
    "Solar Manufacturer": "one hundred sixteen",
    "Solar Panels Comments": "one hundred seventeen",
    # Page 4
    "Walk Score Source walkscore": True,
    "Walk Score Source Other": True,
    "Walk Score Source Other Value": "one hundred nineteen",
    "Public Transportation Bus": True,
    "Public Transportation Bus Distance": "one hundred twenty",
    "Public Transportation Train": True,
    "Public Transportation Train Distance": "one hundred twenty one",
    "Public Transportation Subway": True,
    "Public Transportation Subway Distance": "one hundred twenty two",
    "Site Orientation East West": True,
    "Site Orientation North South": True,
    "Site Landscaping Water Efficient": True,
    "Site Landscaping Natural": True,
    "Site Landscaping PondLake on site": True,
    "Site Landscaping Rain Garden": True,
    "Location Comments": "one hundred twenty three",
    "Incentives Federal": "one hundred twenty four",
    "Incentives State": "one hundred twenty five",
    "Incentives Local": "one hundred twenty six",
    "Incentives Comments": "one hundred twenty seven",
}
