# Generated by Django 4.0.7 on 2022-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relationship", "0002_historicalrelationship_history_change_reason_foo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalrelationship",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Association",
                "verbose_name_plural": "historical Associations",
            },
        ),
        migrations.AlterField(
            model_name="historicalrelationship",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalrelationship",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
