# Generated by Django 4.0.7 on 2022-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relationship", "0003_alter_historicalrelationship_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
