# Generated by Django 4.2.1 on 2023-05-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gbr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greenbuildingregistry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not yet started", "Not Started"),
                    ("Imported from HES HPXML", "Legacy Import"),
                    ("Address created and valid", "Property Valid"),
                    ("Address creation failed", "Property Invalid"),
                    ("GBR Service Unavailable", "Service Unavailable"),
                    ("GBR Throttled", "Service Throttled"),
                    ("Assessment Created", "Assessment Created"),
                    ("Assessment Creation Failed", "Assessment Invalid"),
                ],
                default="Not yet started",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgreenbuildingregistry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not yet started", "Not Started"),
                    ("Imported from HES HPXML", "Legacy Import"),
                    ("Address created and valid", "Property Valid"),
                    ("Address creation failed", "Property Invalid"),
                    ("GBR Service Unavailable", "Service Unavailable"),
                    ("GBR Throttled", "Service Throttled"),
                    ("Assessment Created", "Assessment Created"),
                    ("Assessment Creation Failed", "Assessment Invalid"),
                ],
                default="Not yet started",
                max_length=32,
            ),
        ),
    ]
