# Generated by Django 1.11.16 on 2018-10-08 18:15

import axis.core.fields
from django.db import migrations, models
import django.db.models.deletion

import django_states.fields
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertifiableObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("type", models.CharField(max_length=25)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("settings", models.TextField(default=dict)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Certifiable Object",
            },
        ),
        migrations.CreateModel(
            name="CertifiableObjectRemoteIdentifier",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[("trc", "TRC UUID")],
                        help_text="A queryable label for an off-site type.",
                        max_length=20,
                    ),
                ),
                (
                    "id",
                    axis.core.fields.UUIDField(
                        blank=True,
                        help_text="Represents an off-site ID of the given type.",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCertifiableObject",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("type", models.CharField(max_length=25)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("settings", models.TextField(default=dict)),
                ("created_date", models.DateTimeField(blank=True, editable=False)),
                ("modified_date", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical Certifiable Object",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWorkflowStatus",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("state", django_states.fields.StateField(default=None, max_length=100)),
                ("data", models.TextField(default=dict)),
                ("created_date", models.DateTimeField(blank=True, editable=False)),
                ("modified_date", models.DateTimeField(blank=True, editable=False)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical workflow status",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWorkflowStatusStateLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    django_states.fields.StateField(
                        default=b"transition_initiated", max_length=100, verbose_name="state id"
                    ),
                ),
                ("from_state", models.CharField(max_length=100)),
                ("to_state", models.CharField(max_length=100)),
                ("serialized_kwargs", models.TextField(blank=True)),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="transition started at"
                    ),
                ),
            ],
            options={
                "verbose_name": "historical workflow status transition",
            },
        ),
        migrations.CreateModel(
            name="TRCProjectData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "lead_contact_date",
                    models.DateField(blank=True, null=True, verbose_name="Lead Contact Date"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TRCProjectSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("new", "New Construction"), ("retrofit", "Retrofit")],
                        max_length=25,
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "config_path",
                    models.FilePathField(
                        allow_folders=True,
                        match="^[^_].*(?<!\\.pyc)$",
                        path="/Users/isamu/Projects/Pivotal/axis/axis/certification/configs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state", django_states.fields.StateField(default=None, max_length=100)),
                ("data", models.TextField(default=dict)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Workflow Statuses",
            },
        ),
        migrations.CreateModel(
            name="WorkflowStatusAssociation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_contributor", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                ("public_token", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkflowStatusRemoteIdentifier",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[("trc", "TRC UUID")],
                        help_text="A queryable label for an off-site type.",
                        max_length=20,
                    ),
                ),
                (
                    "id",
                    axis.core.fields.UUIDField(
                        blank=True,
                        help_text="Represents an off-site ID of the given type.",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStatusStateLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    django_states.fields.StateField(
                        default=b"transition_initiated", max_length=100, verbose_name="state id"
                    ),
                ),
                ("from_state", models.CharField(max_length=100)),
                ("to_state", models.CharField(max_length=100)),
                ("serialized_kwargs", models.TextField(blank=True)),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="transition started at"
                    ),
                ),
                (
                    "on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_history",
                        to="certification.WorkflowStatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow status transition",
            },
        ),
    ]
