# Generated by Django 1.11.16 on 2018-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0002_auto_20181008_1815"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certifiableobject",
            name="settings",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalcertifiableobject",
            name="settings",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalworkflowstatus",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="workflowstatus",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
