# Generated by Django 1.11.17 on 2019-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0006_auto_20190528_1529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="config_path",
            field=models.FilePathField(
                allow_folders=True,
                match="^[^_].*(?<!\\.pyc)$",
                path="/Users/artemhruzd/Development/Pivotal/axis/axis/certification/configs",
            ),
        ),
    ]
