# Generated by Django 1.11.17 on 2019-08-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0007_auto_20190530_1854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcertifiableobject",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="certification.CertifiableObject",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="config_path",
            field=models.FilePathField(
                allow_folders=True,
                match="^[^_].*(?<!\\.pyc)$",
                path="/Users/steven/Development/Pivotal/axis-sandbox-0/axis/axis/certification/configs",
            ),
        ),
    ]
