# Generated by Django 1.11.26 on 2020-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0008_auto_20190826_2024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="config_path",
            field=models.FilePathField(
                allow_folders=True,
                match="^[^_].*(?<!\\.pyc)$",
                path="/Users/artemhruzd/Development/Pivotal/axis/axis/certification/configs",
            ),
        ),
    ]
