# Generated by Django 2.2 on 2020-11-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0009_auto_20200415_1540"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="config_path",
            field=models.FilePathField(
                allow_folders=True,
                match="^[^_].*(?<!\\.pyc)$",
                path="/home/kanak/work/pivotal/axis/axis/certification/configs",
            ),
        ),
    ]
