# Generated by Django 2.2 on 2020-12-04 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0011_auto_20201201_1317"),
        ("certification", "0011_auto_20201203_1708"),
    ]

    operations = []
