# Generated by Django 2.2 on 2020-12-04 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0012_merge_20201204_1044"),
        ("certification", "0011_auto_20201125_1831"),
    ]

    operations = []
