# Generated by Django 4.0.7 on 2022-09-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0015_alter_historicalcertifiableobject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certifiableobject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workflowstatus",
            name="certifiable_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="certification.certifiableobject"
            ),
        ),
        migrations.AlterField(
            model_name="workflowstatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
