# Generated by Django 4.0.7 on 2022-10-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0016_alter_certifiableobject_id_alter_workflow_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="config_path",
            field=models.FilePathField(
                allow_folders=True,
                match="^[^_].*(?<!\\.pyc)$",
                path="/Users/artemhruzd/Development/Pivotal/axis/axis/certification/configs",
            ),
        ),
    ]
