# Generated by Django 4.0.8 on 2022-11-11 09:44

from axis.certification.models import get_configs_dir
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0017_alter_workflow_config_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="config_path",
            field=models.FilePathField(
                allow_folders=True,
                match="^[^_].*(?<!\\.pyc)$",
                path=get_configs_dir,
            ),
        ),
    ]
