# Generated by Django 1.11.17 on 2019-08-26 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0002_auto_20181010_2316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="assigner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigner",
            ),
        ),
    ]
