# Generated by Django 1.11.26 on 2020-01-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0004_auto_20200107_2012"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltask",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="historicaltask",
            old_name="last_update",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="historicaltasktype",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="historicaltasktype",
            old_name="last_update",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="last_update",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="tasktype",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tasktype",
            old_name="last_update",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="historicaltasktype",
            name="object_id",
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasktype",
            name="object_id",
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
