# Generated by Django 1.11.26 on 2020-01-13 11:30

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0005_auto_20200110_1629"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltasktype",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="tasktype",
            name="object_id",
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="approval_state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New (Unapproved)"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="approval_state_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="approval_state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New (Unapproved)"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="approval_state_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
