# Generated by Django 1.11.26 on 2020-01-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0007_auto_20200113_1631"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="home_address",
            field=models.CharField(
                blank=True,
                help_text="This field is populating when task is using Home model as content type object",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="home_address",
            field=models.CharField(
                blank=True,
                help_text="This field is populating when task is using Home model as content type object",
                max_length=255,
            ),
        ),
    ]
