# Generated by Django 1.11.26 on 2020-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0008_auto_20200127_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="approval_annotation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="approval_annotation",
            field=models.TextField(blank=True),
        ),
    ]
