# Generated by Django 1.11.26 on 2020-01-27 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0009_auto_20200127_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="status_annotation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="status_approver",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Status approver",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status_annotation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="status_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_status_approver",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Status approver",
            ),
        ),
    ]
