# Generated by Django 1.11.26 on 2020-01-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0010_auto_20200127_1636"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
