# Generated by Django 1.11.26 on 2020-04-15 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0011_auto_20200127_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
    ]
