# Generated by Django 4.0.7 on 2022-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0012_auto_20200415_1540"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalconstructionstatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical construction status",
                "verbose_name_plural": "historical Construction Status",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltask",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical task",
                "verbose_name_plural": "historical tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltasktype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical task type",
                "verbose_name_plural": "historical task types",
            },
        ),
        migrations.AlterField(
            model_name="constructionstatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructionstatus",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalconstructionstatus",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltasktype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltasktype",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
