# Generated by Django 4.0.7 on 2022-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0013_alter_historicalconstructionstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionstage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
