# Generated by Django 4.0.7 on 2022-10-10 17:49

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def move_content_type_qa_to_fk(apps, schema_editor):
    home_class = apps.get_model("home", "Home")
    task_class = apps.get_model("scheduling", "Task")
    ct = ContentType.objects.get_for_model(home_class)
    for task in task_class.objects.filter(content_type__pk=ct.id):
        try:
            home = home_class.objects.get(id=task.object_id)
        except Exception:
            print(f"Error for: {task.id}")
            continue
        try:
            task.home = home
            task.save()
        except Exception:
            print(f"Error for: {task.id} {home}")
            continue


def reverse_move_content_type(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0015_historicaltask_home_task_home"),
    ]

    operations = [
        migrations.RunPython(move_content_type_qa_to_fk, reverse_code=reverse_move_content_type),
    ]
