# Generated by Django 4.0.8 on 2023-01-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0017_remove_historicaltask_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltask",
            name="time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="time",
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="date",
            field=models.DateTimeField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(verbose_name="Date"),
        ),
    ]
