# Generated by Django 4.0.8 on 2023-01-18 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0018_remove_historicaltask_time_remove_task_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltask",
            name="date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="date",
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 18, 11, 29, 46, 321306, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 18, 11, 29, 52, 806774, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
