# Generated by Django 4.0.8 on 2023-01-23 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0020_alter_tasktype_options_historicaltasktype_priority_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ("-priority", "-name")},
        ),
    ]
