# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geographic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geocoder", "0001_initial"),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcommunity",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.City",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="climate_zone",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.ClimateZone",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="county",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.County",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="geocode_response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.GeocodeResponse",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="metro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.Metro",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunity",
            name="place",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.Place",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="city",
            field=models.ForeignKey(
                help_text='Type the first few letters of the name of the city of the location and select the correct city/state/county combination from the list presented. If the correct city is not available, click "Add New" to add a city to the database.',
                on_delete=django.db.models.deletion.CASCADE,
                to="geographic.City",
                verbose_name="City/State/County",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="climate_zone",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geographic.ClimateZone",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="county",
            field=models.ForeignKey(
                help_text=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="geographic.County",
                verbose_name="County",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="geocode_response",
            field=models.ForeignKey(
                blank=True,
                help_text="The response this place was constructed from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geocoder.GeocodeResponse",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="metro",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geographic.Metro",
                verbose_name="Metro",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="community_set",
                to="geographic.Place",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="community",
            unique_together=set([("name", "city")]),
        ),
    ]
