# Generated by Django 1.11.17 on 2019-08-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_historicalcommunity_history_change_reason_foo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcommunity",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Type the first few letters of the name of the city of the location and select the correct city/state/county combination from the list presented. If the correct city is not available, click "Add New" to add a city to the database.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.City",
                verbose_name="City/State/County",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunity",
            name="climate_zone",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.ClimateZone",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunity",
            name="county",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.County",
                verbose_name="County",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunity",
            name="geocode_response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The response this place was constructed from.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.GeocodeResponse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunity",
            name="metro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.Metro",
                verbose_name="Metro",
            ),
        ),
    ]
