# Generated by Django 2.2 on 2020-07-28 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_auto_20190826_2024"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="community",
            options={
                "ordering": ("name",),
                "verbose_name": "Community",
                "verbose_name_plural": "Communities",
            },
        ),
    ]
