# Generated by Django 4.0.6 on 2022-08-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0006_auto_20220719_1459"),
        ("community", "0006_merge_20200811_1942"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcommunity",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Community",
                "verbose_name_plural": "historical Communities",
            },
        ),
        migrations.AlterField(
            model_name="community",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geographic.county",
                verbose_name="County",
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="geographic.place",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunity",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcommunity",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
