# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="Value")),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(blank=True, max_length=30)),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={"ordering": ("type__name",)},
        ),
        migrations.CreateModel(
            name="HistoricalAnnotation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="Value")),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("last_update", models.DateTimeField(blank=True, editable=False)),
                ("field_name", models.CharField(blank=True, max_length=30)),
                ("is_public", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical annotation",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("multiple-choice", "Multiple Choice"),
                            ("date", "Date"),
                            ("integer", "Whole Number"),
                            ("float", "Decimal Number"),
                        ],
                        help_text="Specifies the format of annotations made with this type.",
                        max_length=50,
                    ),
                ),
                ("is_unique", models.BooleanField(default=False)),
                (
                    "valid_multiplechoice_values",
                    models.CharField(blank=True, max_length=500, verbose_name="Possible values"),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("slug", models.SlugField(editable=False, unique=True)),
                (
                    "applicable_content_types",
                    models.ManyToManyField(
                        to="contenttypes.ContentType", verbose_name="Applicable Types"
                    ),
                ),
            ],
            options={"ordering": ("name",), "verbose_name": "Annotation Type"},
        ),
    ]
