# Generated by Django 1.11.17 on 2019-08-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0003_historicalannotation_history_change_reason_foo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalannotation",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="annotation.Type",
                verbose_name="Annotation Type",
            ),
        ),
    ]
