# Generated by Django 2.2 on 2020-08-11 08:39

import axis.annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0004_auto_20190826_2024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="applicable_content_types",
            field=models.ManyToManyField(
                limit_choices_to={"id__in": axis.annotation.models._limit_choices_to},
                to="contenttypes.ContentType",
                verbose_name="Applicable Types",
            ),
        ),
    ]
