# Generated by Django 2.2 on 2020-08-11 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0005_auto_20200811_0839"),
        ("annotation", "0005_auto_20200619_1744"),
    ]

    operations = []
