# Generated by Django 2.2 on 2020-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0006_merge_20200811_1942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="applicable_content_types",
            field=models.ManyToManyField(
                to="contenttypes.ContentType", verbose_name="Applicable Types"
            ),
        ),
    ]
