# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("levenshtein_distance", models.PositiveIntegerField()),
                ("profile_delta", models.IntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.ContentType"
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ProtoObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                (
                    "selected_object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("data", models.TextField(default=dict)),
                ("data_profile", models.CharField(max_length=128)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("import_failed", models.BooleanField(default=False)),
                ("import_error", models.CharField(blank=True, max_length=500, null=True)),
                ("import_traceback", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.ContentType"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="proto_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proto.ProtoObject"
            ),
        ),
    ]
