# Generated by Django 4.0.7 on 2022-09-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proto", "0003_auto_20181130_1905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
