# Generated by Django 4.0.7 on 2022-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proto", "0004_alter_candidate_id_alter_protoobject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protoobject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
