# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geographic", "0001_initial"),
        ("customer_neea", "0001_initial"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardprotocolcalculator",
            name="home_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.EEPProgramHomeStatus"
            ),
        ),
        migrations.AddField(
            model_name="pnwzone",
            name="county",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="geographic.County"
            ),
        ),
        migrations.AddField(
            model_name="legacyneeapartneraxisbridge",
            name="partner",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="axis_company",
                to="customer_neea.LegacyNEEAPartner",
            ),
        ),
    ]
