# Generated by Django 1.11.16 on 2018-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0002_auto_20181008_1815"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardprotocolcalculator",
            name="reports",
            field=models.JSONField(default=dict),
        ),
    ]
