# Generated by Django 1.11.26 on 2020-01-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_validationdata_remove"),
        ("customer_neea", "0004_auto_20181130_1905"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("levenshtein_distance", models.PositiveIntegerField()),
                ("profile_delta", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NEEACertification",
            fields=[
                ("import_failed", models.BooleanField(default=False)),
                ("import_error", models.CharField(blank=True, max_length=500, null=True)),
                ("import_traceback", models.TextField(blank=True, null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now=True)),
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("registry_id", models.CharField(blank=True, max_length=100)),
                ("street_line1", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip", models.CharField(blank=True, max_length=100)),
                ("date_registered", models.CharField(blank=True, max_length=100)),
                ("home_type", models.CharField(blank=True, max_length=100)),
                ("software", models.CharField(blank=True, max_length=100)),
                ("software_version", models.CharField(blank=True, max_length=100)),
                ("construction_year", models.CharField(blank=True, max_length=100)),
                ("conditioned_area", models.CharField(blank=True, max_length=100)),
                ("conditioned_volume", models.CharField(blank=True, max_length=100)),
                ("conditioned_floors", models.CharField(blank=True, max_length=100)),
                ("number_bedrooms", models.CharField(blank=True, max_length=100)),
                ("hers_index", models.CharField(blank=True, max_length=100)),
                ("registration_type", models.CharField(blank=True, max_length=100)),
                ("total_energy_use", models.CharField(blank=True, max_length=100)),
                ("total_energy_cost", models.CharField(blank=True, max_length=100)),
                ("num_cooling_systems", models.CharField(blank=True, max_length=100)),
                ("num_heating_systems", models.CharField(blank=True, max_length=100)),
                ("cooling_energy_use", models.CharField(blank=True, max_length=100)),
                ("cost_cooling", models.CharField(blank=True, max_length=100)),
                ("cooling_rated_output", models.CharField(blank=True, max_length=100)),
                ("num_hotwatersystems", models.CharField(blank=True, max_length=100)),
                ("hot_waterenergyuse", models.CharField(blank=True, max_length=100)),
                ("cost_hotwater", models.CharField(blank=True, max_length=100)),
                ("lighting_appenergyuse", models.CharField(blank=True, max_length=100)),
                ("cost_lighting", models.CharField(blank=True, max_length=100)),
                ("on_site_generation", models.CharField(blank=True, max_length=100)),
                ("annual_electricity", models.CharField(blank=True, max_length=100)),
                ("annual_gas", models.CharField(blank=True, max_length=100)),
                ("agw_wall_construction_type", models.CharField(blank=True, max_length=100)),
                ("ach50", models.CharField(blank=True, max_length=100)),
                ("ventilation_type", models.CharField(blank=True, max_length=100)),
                ("duct_leakage", models.CharField(blank=True, max_length=100)),
                ("duct_leakage_total", models.CharField(blank=True, max_length=100)),
                ("duct_leakage_tightness_test", models.CharField(blank=True, max_length=100)),
                ("duct_leakage_units", models.CharField(blank=True, max_length=100)),
                ("high_efficiency_lights_percent", models.CharField(blank=True, max_length=100)),
                ("furnace_fuel", models.CharField(blank=True, max_length=100)),
                ("water_heater_type", models.CharField(blank=True, max_length=100)),
                ("water_heater_fuel", models.CharField(blank=True, max_length=100)),
                ("ducts_conditioned", models.CharField(blank=True, max_length=100)),
                ("is_zerh", models.CharField(blank=True, max_length=100)),
                ("energy_star_version", models.CharField(blank=True, max_length=100)),
                (
                    "candidates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="neea_certification_candidates",
                        through="customer_neea.Candidate",
                        to="home.Home",
                    ),
                ),
                (
                    "home",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_neea_certification",
                        to="home.Home",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "permissions": (("view_certification", "View Certification"),),
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="certification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer_neea.NEEACertification"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_neea_candidates",
                to="home.Home",
            ),
        ),
    ]
