# Generated by Django 1.11.26 on 2020-01-08 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0005_auto_20200107_2130"),
    ]

    operations = [
        migrations.RenameField(
            model_name="neeacertification",
            old_name="zip",
            new_name="zipcode",
        ),
    ]
