# Generated by Django 1.11.26 on 2020-01-08 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0006_auto_20200108_1652"),
    ]

    operations = [
        migrations.RenameField(
            model_name="neeacertification",
            old_name="state",
            new_name="state_abbreviation",
        ),
    ]
