# Generated by Django 1.11.26 on 2020-01-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0008_auto_20200108_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neeacertification",
            name="certification_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
