# Generated by Django 1.11.26 on 2020-01-08 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0009_auto_20200108_1745"),
    ]

    operations = [
        migrations.RenameField(
            model_name="neeacertification",
            old_name="cost_hotwater",
            new_name="cost_hot_water",
        ),
        migrations.RenameField(
            model_name="neeacertification",
            old_name="hot_waterenergyuse",
            new_name="hot_water_energy_use",
        ),
        migrations.RenameField(
            model_name="neeacertification",
            old_name="lighting_appenergyuse",
            new_name="lighting_app_energy_use",
        ),
        migrations.RenameField(
            model_name="neeacertification",
            old_name="num_hotwatersystems",
            new_name="num_hot_water_systems",
        ),
    ]
