# Generated by Django 2.2 on 2020-07-28 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0011_historicalneeacertification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="neeacertification",
            options={},
        ),
    ]
