# Generated by Django 3.1.3 on 2020-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0013_merge_20200811_1942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardprotocolcalculator",
            name="has_incentive",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
