# Generated by Django 3.1.8 on 2021-05-04 20:12

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    StandardProtocolCalculator = apps.get_model("customer_neea", "StandardProtocolCalculator")
    Company = apps.get_model("company", "Company")
    import datetime
    from axis.customer_neea.rtf_calculator.base import RTFInputException
    from axis.customer_neea.rtf_calculator.calculator import NEEAV2Calculator

    for sp in StandardProtocolCalculator.objects.filter(incentive_paying_organization__isnull=True):
        input_values = sp.home_status.get_input_values(user_role="rater")
        answers = {measure.replace("neea-", ""): value for measure, value in input_values.items()}

        try:
            calculator = NEEAV2Calculator(home_status_id=sp.home_status.id, **answers)
            slug = calculator.incentives.incentive_paying_organization
            incentive_paying_organization = Company.objects.get(slug=slug) if slug else None
            # These all rolled around 8/20/19
            if slug in [
                "clark-pud",
                "sno-pud",
                "benton-rea",
                "puget-sound-energy",
                "central-electric",
                "pacific-power",
                "idaho-power",
                "inland-power",
            ]:
                try:
                    if sp.last_updated < datetime.datetime(2019, 8, 20).replace(
                        tzinfo=datetime.timezone.utc
                    ):
                        incentive_paying_organization = None
                except TypeError:
                    print("Skipping %s" % sp.id)
                    incentive_paying_organization = None
            # These all rolled around 9/30/19
            elif slug in ["utility-city-of-richland"]:
                try:
                    if sp.last_updated < datetime.datetime(2019, 9, 30):
                        incentive_paying_organization = None
                except TypeError:
                    print("Skipping %s" % sp.id)
                    incentive_paying_organization = None
            # sp.incentive_paying_organization = Company.objects.get(slug=slug)
            if incentive_paying_organization:
                sp.incentive_paying_organization = incentive_paying_organization
                sp.save()
            print(sp.id, incentive_paying_organization)

        except RTFInputException as issues:
            pass


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0022_auto_20210115_1627"),
        ("customer_neea", "0014_auto_20201230_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardprotocolcalculator",
            name="incentive_paying_organization",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="company.company"
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
