# Generated by Django 3.1.8 on 2021-05-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0015_standardprotocolcalculator_incentive_paying_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ac_efficiency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ac_output_capacity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ag_wall_cavity_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ag_wall_continuous_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ag_wall_framing_factor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ag_wall_insulation_grade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ag_wall_insulation_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ag_wall_uo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ceiling_cavity_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ceiling_continuous_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ceiling_insulation_depth",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ceiling_insulation_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ceiling_uo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="dishwasher_k_whyr",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="dryer_energy_factor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="dryer_energy_factor_gas",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="floor_cavity_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="floor_continuous_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="foundation_batt_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="foundation_insulation_grade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="foundation_rigid_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="foundation_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="foundation_wall_uo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="furnace_output_capacity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="heating_efficiency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="heating_efficiency_units",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="heating_rated_output",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="heating_system_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="opp_net",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="overall_enclosure_ua",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="purchased_energy_fraction",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="radiant_barrier",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="refrigerator_k_wh",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ventilation_fan_wattage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ventilation_rate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="ventilation_run_time",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="washer_ler",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="water_heater_capacity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="window_shgc",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalneeacertification",
            name="window_u_factor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ac_efficiency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ac_output_capacity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ag_wall_cavity_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ag_wall_continuous_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ag_wall_framing_factor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ag_wall_insulation_grade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ag_wall_insulation_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ag_wall_uo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ceiling_cavity_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ceiling_continuous_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ceiling_insulation_depth",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ceiling_insulation_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ceiling_uo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="dishwasher_k_whyr",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="dryer_energy_factor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="dryer_energy_factor_gas",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="floor_cavity_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="floor_continuous_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="foundation_batt_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="foundation_insulation_grade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="foundation_rigid_insulation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="foundation_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="foundation_wall_uo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="furnace_output_capacity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="heating_efficiency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="heating_efficiency_units",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="heating_rated_output",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="heating_system_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="opp_net",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="overall_enclosure_ua",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="purchased_energy_fraction",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="radiant_barrier",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="refrigerator_k_wh",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ventilation_fan_wattage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ventilation_rate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="ventilation_run_time",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="washer_ler",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="water_heater_capacity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="window_shgc",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="neeacertification",
            name="window_u_factor",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
