# Generated by Django 3.2.4 on 2021-07-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_neea", "0016_auto_20210525_2126"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardprotocolcalculator",
            name="estar_clothes_washer_installed",
            field=models.CharField(
                choices=[
                    ("washer_top_load", "ENERGY STAR with top load"),
                    ("washer_side_load", "ENERGY STAR with side load"),
                    (None, "None"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standardprotocolcalculator",
            name="estar_refrigerators_installed",
            field=models.CharField(
                choices=[
                    ("refrigerator_bottom_freezer", "ENERGY STAR with bottom-mounted freezer"),
                    ("refrigerator_side_freezer", "ENERGY STAR with side-mounted freezer"),
                    ("refrigerator_other_freezer", "ENERGY STAR with other freezer type"),
                    (None, "None"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalneeacertification",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="legacyneeapartneraxisbridge",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="neeacertification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pnwzone",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="standardprotocolcalculator",
            name="estar_front_load_clothes_washer_installed",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="standardprotocolcalculator",
            name="estar_std_refrigerators_installed",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="standardprotocolcalculator",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
