# Generated by Django 4.0.7 on 2022-09-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_alter_eepprogramhomestatus_home_and_more"),
        ("customer_neea", "0017_auto_20210714_1457"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalneeacertification",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical neea certification",
                "verbose_name_plural": "historical neea certifications",
            },
        ),
        migrations.AlterField(
            model_name="candidate",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_candidates",
                to="home.home",
            ),
        ),
        migrations.AlterField(
            model_name="historicalneeacertification",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="neeacertification",
            name="home",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_certification",
                to="home.home",
            ),
        ),
        migrations.AlterField(
            model_name="standardprotocolcalculator",
            name="estar_clothes_washer_installed",
            field=models.CharField(
                choices=[
                    ("washer_top_load", "ENERGY STAR® with top load"),
                    ("washer_side_load", "ENERGY STAR® with front load"),
                    (None, "None"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="standardprotocolcalculator",
            name="estar_refrigerators_installed",
            field=models.CharField(
                choices=[
                    ("refrigerator_bottom_freezer", "ENERGY STAR® with bottom-mounted freezer"),
                    ("refrigerator_side_freezer", "ENERGY STAR® with side-mounted freezer"),
                    ("refrigerator_other_freezer", "ENERGY STAR® with other freezer type"),
                    (None, "None"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
