# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geographic", "0001_initial"),
        ("checklist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="climate_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geographic.ClimateZone",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_choice",
            field=models.ManyToManyField(to="checklist.QuestionChoice"),
        ),
    ]
