# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checklist", "0002_auto_20181008_1815"),
        ("auth", "0008_alter_user_username_max_length"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qaanswer",
            name="home",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.Home"),
        ),
        migrations.AddField(
            model_name="qaanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="checklist.Question"
            ),
        ),
        migrations.AddField(
            model_name="qaanswer",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalqaanswer",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalqaanswer",
            name="home",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="home.Home",
            ),
        ),
        migrations.AddField(
            model_name="historicalqaanswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="checklist.Question",
            ),
        ),
        migrations.AddField(
            model_name="historicalqaanswer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="home",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="home.Home",
            ),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="checklist.Question",
            ),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_checklist_related",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="questions",
            field=models.ManyToManyField(to="checklist.Question"),
        ),
        migrations.AddField(
            model_name="answerimage",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="checklist.Answer",
            ),
        ),
        migrations.AddField(
            model_name="answerdocument",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="checklist.Answer",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="home",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.Home"),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="checklist.Question"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
