# Generated by Django 1.11.16 on 2018-10-10 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checklist", "0003_auto_20181008_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalanswer",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalqaanswer",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
