# Generated by Django 1.11.16 on 2018-10-30 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_collection_request"),
        ("django_input_collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checklist", "0004_auto_20181010_2316"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectedInput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "user_role",
                    models.CharField(
                        blank=True,
                        choices=[("qa", "QA"), ("rater", "Rater"), ("other", "[Other]")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_failure", models.BooleanField(default=False)),
                ("failure_is_reviewed", models.BooleanField(default=False)),
                (
                    "collection_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectedinput_set",
                        to="django_input_collection.CollectionRequest",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.Home"),
                ),
                (
                    "home_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.EEPProgramHomeStatus"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectedinput_set",
                        to="django_input_collection.CollectionInstrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
