# Generated by Django 1.11.16 on 2018-11-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_input_collection", "0001_initial"),
        ("checklist", "0005_collectedinput"),
    ]

    operations = [
        migrations.CreateModel(
            name="AxisSuggestedResponse",
            fields=[
                (
                    "suggestedresponse_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_input_collection.SuggestedResponse",
                    ),
                ),
                ("is_considered_failure", models.BooleanField(default=False)),
                ("comment_required", models.BooleanField(default=False)),
                ("document_required", models.BooleanField(default=False)),
                ("photo_required", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("django_input_collection.suggestedresponse",),
        ),
    ]
