# Generated by Django 1.11.17 on 2018-12-11 16:58

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0006_axissuggestedresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectedinput",
            name="data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
    ]
