# Generated by Django 1.11.17 on 2019-01-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0007_auto_20181211_1658"),
    ]

    operations = [
        migrations.CreateModel(
            name="AxisBoundSuggestedResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_considered_failure", models.BooleanField(default=False)),
                ("comment_required", models.BooleanField(default=False)),
                ("document_required", models.BooleanField(default=False)),
                ("photo_required", models.BooleanField(default=False)),
                (
                    "collection_instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bound_suggested_responses",
                        to="django_input_collection.CollectionInstrument",
                    ),
                ),
                (
                    "suggested_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_input_collection.SuggestedResponse",
                    ),
                ),
            ],
        ),
    ]
