# Generated by Django 1.11.17 on 2019-02-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0009_move_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AxisSuggestedResponse",
        ),
    ]
