# Generated by Django 1.11.17 on 2019-02-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_input_collection", "0008_auto_20190206_1901"),
        ("checklist", "0010_drop_axissuggestedresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectedinput",
            name="collector_class",
            field=models.CharField(default="unknown", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectedinput",
            name="collector_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collectedinput",
            name="collector_id",
            field=models.CharField(default="unknown", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectedinput",
            name="collector_version",
            field=models.CharField(default="unknown", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectedinput",
            name="version",
            field=models.CharField(default="unknown", max_length=128),
            preserve_default=False,
        ),
    ]
