# Generated by Django 1.11.17 on 2019-02-06 19:11

from django.db import migrations, models


def forward__delete_duplicate_responses(apps, schema_editor):
    SuggestedResponse = apps.get_model("django_input_collection.SuggestedResponse")
    BoundSuggestedResponse = apps.get_model("checklist.AxisBoundSuggestedResponse")
    for answer_value in list(SuggestedResponse.objects.values_list("data", flat=True).distinct()):
        queryset = SuggestedResponse.objects.filter(data=answer_value)
        good = queryset.first()
        bad = queryset.exclude(pk=good.pk)
        bad_bound = BoundSuggestedResponse.objects.filter(suggested_response__in=bad)
        bad_bound.update(suggested_response=good)
        bad.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0011_auto_20190206_1911"),
    ]

    operations = [
        migrations.RunPython(forward__delete_duplicate_responses),
    ]
