# Generated by Django 1.11.17 on 2019-02-06 19:11

from django.db import migrations, models


def forward__delete_duplicate_cases(apps, schema_editor):
    Case = apps.get_model("django_input_collection.Case")
    ConditionGroup = apps.get_model("django_input_collection.ConditionGroup")
    for match_type, match_data in list(
        Case.objects.values_list("match_type", "match_data").distinct()
    ):
        queryset = Case.objects.filter(match_type=match_type, match_data=match_data)
        good = queryset.first()
        bad = queryset.exclude(pk=good.pk)
        ConditionGroup.cases.through.objects.filter(case__in=bad).delete()
        bad.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0012_fix_dupe_suggestedresponses"),
    ]

    operations = [
        migrations.RunPython(forward__delete_duplicate_cases),
    ]
