# Generated by Django 1.11.17 on 2019-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0017_data_migrate_to_cr2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="created_date",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="modified_date",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalqaanswer",
            name="created_date",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalqaanswer",
            name="modified_date",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="qaanswer",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="qaanswer",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="questionchoice",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="questionchoice",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
