# Generated by Django 1.11.17 on 2019-05-25 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0018_auto_20190531_1224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answerdocument",
            name="answer",
        ),
        migrations.DeleteModel(
            name="AnswerDocument",
        ),
    ]
