# Generated by Django 3.1.3 on 2020-12-30 12:18

import axis.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0019_remove_answer_document_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="email_sent",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="collectedinput",
            name="data",
            field=axis.core.fields.AxisJSONField(),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="email_sent",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalqaanswer",
            name="email_sent",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="qaanswer",
            name="email_sent",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
