# Generated by Django 1.11.17 on 2019-03-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_auto_20181010_2316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[
                    ("debug", "DEBUG"),
                    ("info", "Info"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("system", "System"),
                ],
                default="info",
                max_length=10,
                verbose_name="Severity",
            ),
        ),
    ]
