# Generated by Django 3.1.3 on 2021-01-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0004_auto_20201230_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="modern_message",
            field=models.CharField(
                blank=True,
                help_text="Populated automatically in case of message has been populated through Modern Message",
                max_length=255,
            ),
        ),
    ]
