# Generated by Django 3.1.6 on 2021-02-26 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0005_message_modern_message"),
        ("messaging", "0005_auto_20210224_1038"),
    ]

    operations = []
