# Generated by Django 3.1.8 on 2021-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0006_merge_20210226_0942"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="email_content",
            field=models.TextField(blank=True, null=True, verbose_name="Email Content"),
        ),
    ]
