# Generated by Django 3.1.12 on 2021-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0007_message_email_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="email_subject",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Email Subject"
            ),
        ),
    ]
