# Generated by Django 4.1.7 on 2023-03-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0033_auto_20230224_1051"),
        ("messaging", "0009_alter_historicaldigestpreference_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.company",
            ),
        ),
    ]
