# Generated by Django 4.2.1 on 2023-06-19 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0010_message_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="alert_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(db_index=True, verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="message",
            name="date_alerted",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Alerted"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="message",
            name="date_sent",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Emailed"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="email_content",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Email Content"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="email_read",
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="email_subject",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True, verbose_name="Email Subject"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[
                    ("debug", "DEBUG"),
                    ("info", "Info"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("system", "System"),
                ],
                db_index=True,
                default="info",
                max_length=10,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="If not set then it is System Message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(db_index=True, max_length=200, verbose_name="Subject"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["date_created", "id"], name="messaging_m_date_cr_6dc2a1_idx"
            ),
        ),
    ]
