# Generated by Django 4.2.1 on 2023-06-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0011_alter_message_alert_read_alter_message_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="message",
            name="email_content",
            field=models.TextField(blank=True, null=True, verbose_name="Email Content"),
        ),
    ]
