# Generated by Django 4.2.2 on 2023-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0012_alter_message_content_alter_message_email_content"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="messaging_m_date_cr_6dc2a1_idx",
        ),
        migrations.AlterField(
            model_name="message",
            name="alert_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="date_alerted",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Alerted"),
        ),
        migrations.AlterField(
            model_name="message",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="message",
            name="date_sent",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Emailed"),
        ),
        migrations.AlterField(
            model_name="message",
            name="email_read",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="email_subject",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Email Subject"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[
                    ("debug", "DEBUG"),
                    ("info", "Info"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("system", "System"),
                ],
                default="info",
                max_length=10,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Subject"),
        ),
    ]
