# Generated by Django 1.11.26 on 2020-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0003_auto_20200128_1940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqastatusstatelog",
            name="from_state",
            field=models.CharField(
                choices=[
                    (b"received", "Received"),
                    (b"in_progress", "In Progress"),
                    (b"correction_required", "Correction Required"),
                    (b"complete", "Complete"),
                    (b"correction_received", "Correction Received"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalqastatusstatelog",
            name="to_state",
            field=models.CharField(
                choices=[
                    (b"received", "Received"),
                    (b"in_progress", "In Progress"),
                    (b"correction_required", "Correction Required"),
                    (b"complete", "Complete"),
                    (b"correction_received", "Correction Received"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qastatusstatelog",
            name="from_state",
            field=models.CharField(
                choices=[
                    (b"received", "Received"),
                    (b"in_progress", "In Progress"),
                    (b"correction_required", "Correction Required"),
                    (b"complete", "Complete"),
                    (b"correction_received", "Correction Received"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qastatusstatelog",
            name="to_state",
            field=models.CharField(
                choices=[
                    (b"received", "Received"),
                    (b"in_progress", "In Progress"),
                    (b"correction_required", "Correction Required"),
                    (b"complete", "Complete"),
                    (b"correction_received", "Correction Received"),
                ],
                max_length=100,
            ),
        ),
    ]
