# Generated by Django 1.11.26 on 2020-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0004_auto_20200415_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqarequirement",
            name="type",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("field", "Field"),
                    ("program_review", "Program Review"),
                    ("rough_inspection_qa", "Rough Inspection QA"),
                    ("rough_inspection_desktop_audit", "Rough Inspection Desktop Audit"),
                    ("rough_inspection_virtual_audit", "Rough Inspection Virtual Audit"),
                    ("final_inspection_qa", "Final Inspection QA"),
                    ("final_inspection_desktop_audit", "Final Inspection Desktop Audit"),
                    ("final_inspection_virtual_audit", "Final Inspection Virtual Audit"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="historicalqastatusstatelog",
            name="from_state",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("in_progress", "In Progress"),
                    ("correction_required", "Correction Required"),
                    ("correction_received", "Correction Received"),
                    ("complete", "Complete"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalqastatusstatelog",
            name="to_state",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("in_progress", "In Progress"),
                    ("correction_required", "Correction Required"),
                    ("correction_received", "Correction Received"),
                    ("complete", "Complete"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qarequirement",
            name="type",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("field", "Field"),
                    ("program_review", "Program Review"),
                    ("rough_inspection_qa", "Rough Inspection QA"),
                    ("rough_inspection_desktop_audit", "Rough Inspection Desktop Audit"),
                    ("rough_inspection_virtual_audit", "Rough Inspection Virtual Audit"),
                    ("final_inspection_qa", "Final Inspection QA"),
                    ("final_inspection_desktop_audit", "Final Inspection Desktop Audit"),
                    ("final_inspection_virtual_audit", "Final Inspection Virtual Audit"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="qastatusstatelog",
            name="from_state",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("in_progress", "In Progress"),
                    ("correction_required", "Correction Required"),
                    ("correction_received", "Correction Received"),
                    ("complete", "Complete"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qastatusstatelog",
            name="to_state",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("in_progress", "In Progress"),
                    ("correction_required", "Correction Required"),
                    ("correction_received", "Correction Received"),
                    ("complete", "Complete"),
                ],
                max_length=100,
            ),
        ),
    ]
