# Generated by Django 1.11.26 on 2020-07-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0007_merge_20200701_0829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqarequirement",
            name="type",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("field", "Field"),
                    ("program_review", "Program Review"),
                    ("rough_inspection_qa", "Rough Inspection"),
                    ("rough_inspection_virtual_audit", "Rough Inspection Virtual Audit"),
                    ("final_inspection_qa", "Final Inspection"),
                    ("desktop_audit", "Desktop Audit"),
                    ("final_inspection_virtual_audit", "Final Inspection Virtual Audit"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="qarequirement",
            name="type",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("field", "Field"),
                    ("program_review", "Program Review"),
                    ("rough_inspection_qa", "Rough Inspection"),
                    ("rough_inspection_virtual_audit", "Rough Inspection Virtual Audit"),
                    ("final_inspection_qa", "Final Inspection"),
                    ("desktop_audit", "Desktop Audit"),
                    ("final_inspection_virtual_audit", "Final Inspection Virtual Audit"),
                ],
                max_length=64,
            ),
        ),
    ]
