# Generated by Django 3.1.6 on 2021-02-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0127_auto_20210208_1926"),
        ("qa", "0010_merge_20200811_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqastatus",
            name="hirl_certification_level_awarded",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emerald", "Emerald"),
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("bronze", "Bronze"),
                ],
                max_length=100,
                null=True,
                verbose_name="Certification Level Awarded",
            ),
        ),
        migrations.AddField(
            model_name="historicalqastatus",
            name="hirl_commercial_space_confirmed",
            field=models.BooleanField(null=True, verbose_name="Commercial Space Confirmed"),
        ),
        migrations.AddField(
            model_name="historicalqastatus",
            name="hirl_verifier_points_awarded",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Verifier Points Awarded"
            ),
        ),
        migrations.AddField(
            model_name="historicalqastatus",
            name="hirl_verifier_points_reported",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Verifier Points Reported"
            ),
        ),
        migrations.AddField(
            model_name="qastatus",
            name="hirl_badges_awarded",
            field=models.ManyToManyField(
                to="customer_hirl.HIRLGreenEnergyBadge", verbose_name="Badges Awarded"
            ),
        ),
        migrations.AddField(
            model_name="qastatus",
            name="hirl_certification_level_awarded",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emerald", "Emerald"),
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("bronze", "Bronze"),
                ],
                max_length=100,
                null=True,
                verbose_name="Certification Level Awarded",
            ),
        ),
        migrations.AddField(
            model_name="qastatus",
            name="hirl_commercial_space_confirmed",
            field=models.BooleanField(null=True, verbose_name="Commercial Space Confirmed"),
        ),
        migrations.AddField(
            model_name="qastatus",
            name="hirl_verifier_points_awarded",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Verifier Points Awarded"
            ),
        ),
        migrations.AddField(
            model_name="qastatus",
            name="hirl_verifier_points_reported",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Verifier Points Reported"
            ),
        ),
    ]
