# Generated by Django 3.1.6 on 2021-02-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0127_auto_20210208_1926"),
        ("qa", "0011_auto_20210209_1630"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qastatus",
            name="hirl_badges_awarded",
            field=models.ManyToManyField(
                blank=True, to="customer_hirl.HIRLGreenEnergyBadge", verbose_name="Badges Awarded"
            ),
        ),
    ]
