# Generated by Django 3.1.6 on 2021-02-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0131_auto_20210224_1038"),
        ("qa", "0012_auto_20210209_1806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qastatus",
            name="hirl_badges_awarded",
            field=models.ManyToManyField(
                blank=True,
                to="customer_hirl.HIRLGreenEnergyBadge",
                verbose_name="NGBS Green+ Badges Awarded",
            ),
        ),
    ]
