# Generated by Django 3.2.12 on 2022-02-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0014_auto_20210610_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqanote",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalqarequirement",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalqastatus",
            name="created_on",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalqastatus",
            name="hirl_certification_level_awarded",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("emerald", "Emerald"),
                    ("certified", "Certified"),
                    ("conforming", "Conforming"),
                ],
                max_length=100,
                null=True,
                verbose_name="Certification Level Awarded",
            ),
        ),
        migrations.AlterField(
            model_name="historicalqastatus",
            name="hirl_reviewer_wri_value_awarded",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Reviewer WRI Value Awarded"
            ),
        ),
        migrations.AlterField(
            model_name="historicalqastatus",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalqastatus",
            name="last_update",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalqastatusstatelog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="observationtype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="qanote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="qarequirement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="qastatus",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="qastatus",
            name="hirl_certification_level_awarded",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("emerald", "Emerald"),
                    ("certified", "Certified"),
                    ("conforming", "Conforming"),
                ],
                max_length=100,
                null=True,
                verbose_name="Certification Level Awarded",
            ),
        ),
        migrations.AlterField(
            model_name="qastatus",
            name="hirl_reviewer_wri_value_awarded",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Reviewer WRI Value Awarded"
            ),
        ),
        migrations.AlterField(
            model_name="qastatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="qastatus",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="qastatusstatelog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
