# Generated by Django 3.2.12 on 2022-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0015_auto_20220214_2224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqanote",
            name="note",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="qanote",
            name="note",
            field=models.TextField(),
        ),
    ]
