# Generated by Django 4.0.7 on 2022-09-14 19:00

from django.db import migrations, models
import django.db.models.deletion
import django_states.fields


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0016_auto_20220331_1701"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalqanote",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical QA Note",
                "verbose_name_plural": "historical QA Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqarequirement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical QA Requirement",
                "verbose_name_plural": "historical QA Requirements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqastatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical QA Status",
                "verbose_name_plural": "historical QA Statuses",
            },
        ),
        migrations.AlterField(
            model_name="historicalqanote",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqarequirement",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqastatus",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqastatus",
            name="state",
            field=django_states.fields.StateField(
                default="received", max_length=100, verbose_name="state id"
            ),
        ),
        migrations.AlterField(
            model_name="historicalqastatusstatelog",
            name="state",
            field=django_states.fields.StateField(
                default="transition_initiated", max_length=100, verbose_name="state id"
            ),
        ),
        migrations.AlterField(
            model_name="qanote",
            name="qa_status",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="qa.qastatus"
            ),
        ),
        migrations.AlterField(
            model_name="qastatus",
            name="state",
            field=django_states.fields.StateField(
                default="received", max_length=100, verbose_name="state id"
            ),
        ),
        migrations.AlterField(
            model_name="qastatusstatelog",
            name="state",
            field=django_states.fields.StateField(
                default="transition_initiated", max_length=100, verbose_name="state id"
            ),
        ),
    ]
