# Generated by Django 4.0.7 on 2022-09-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0017_alter_historicalqanote_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qanote",
            name="qa_status",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="qa.qastatus"),
        ),
    ]
