# Generated by Django 4.0.8 on 2022-11-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0018_alter_qanote_qa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqastatus",
            name="hirl_land_development_certification_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one_star", "One Star"),
                    ("two_stars", "Two Stars"),
                    ("three_stars", "Three Stars"),
                    ("four_stars", "Four Stars"),
                ],
                max_length=100,
                null=True,
                verbose_name="Land Development Certification Level Awarded",
            ),
        ),
        migrations.AddField(
            model_name="qastatus",
            name="hirl_land_development_certification_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one_star", "One Star"),
                    ("two_stars", "Two Stars"),
                    ("three_stars", "Three Stars"),
                    ("four_stars", "Four Stars"),
                ],
                max_length=100,
                null=True,
                verbose_name="Land Development Certification Level Awarded",
            ),
        ),
    ]
