# Generated by Django 4.0.8 on 2022-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0019_historicalqastatus_hirl_land_development_certification_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalqastatus",
            name="hirl_land_development_certification_level",
        ),
        migrations.RemoveField(
            model_name="qastatus",
            name="hirl_land_development_certification_level",
        ),
        migrations.AlterField(
            model_name="historicalqastatus",
            name="hirl_certification_level_awarded",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("emerald", "Emerald"),
                    ("certified", "Certified"),
                    ("conforming", "Conforming"),
                    ("one_star", "One Star"),
                    ("two_stars", "Two Star"),
                    ("three_stars", "Three Star"),
                    ("four_stars", "Four Star"),
                ],
                max_length=100,
                null=True,
                verbose_name="Certification Level Awarded",
            ),
        ),
        migrations.AlterField(
            model_name="qastatus",
            name="hirl_certification_level_awarded",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("emerald", "Emerald"),
                    ("certified", "Certified"),
                    ("conforming", "Conforming"),
                    ("one_star", "One Star"),
                    ("two_stars", "Two Star"),
                    ("three_stars", "Three Star"),
                    ("four_stars", "Four Star"),
                ],
                max_length=100,
                null=True,
                verbose_name="Certification Level Awarded",
            ),
        ),
    ]
