# Generated by Django 1.11.17 on 2019-08-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0004_auto_20190621_0327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcustomerdocument",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.Company",
                verbose_name="Sharing company",
            ),
        ),
    ]
