# Generated by Django 1.11.26 on 2020-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0006_auto_20200128_1940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynchronousprocesseddocument",
            name="final_status",
            field=models.CharField(
                choices=[
                    ("FAILURE", "FAILURE"),
                    ("RETRY", "RETRY"),
                    ("REVOKED", "REVOKED"),
                    ("SUCCESS", "SUCCESS"),
                    ("RECEIVED", "RECEIVED"),
                    ("STARTED", "STARTED"),
                    ("UNACKNOWLEDGED", "UNACKNOWLEDGED"),
                    ("PENDING", "PENDING"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
