# Generated by Django 1.11.26 on 2020-07-01 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0009_merge_20200626_1514"),
        ("filehandling", "0008_auto_20200630_1724"),
    ]

    operations = []
