# Generated by Django 4.0.7 on 2022-09-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0011_alter_customerdocument_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
