# Generated by Django 4.1.7 on 2023-04-03 11:03

import axis.filehandling.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0013_customerdocument_login_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdocument",
            name="document",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=axis.filehandling.models.content_name,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomerdocument",
            name="document",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
