# Generated by Django 1.11.17 on 2019-10-30 13:15

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="owner",
            new_name="owner_company",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="brand",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="calibration_company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="calibration_cycle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serial",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="equipmentsponsorstatus",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
