# Generated by Django 1.11.17 on 2019-10-30 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0002_auto_20191030_1315"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipmentsponsorstatus",
            name="approve_date",
        ),
        migrations.AddField(
            model_name="equipmentsponsorstatus",
            name="approve_at",
            field=models.DateTimeField(
                default=datetime.datetime(2019, 10, 30, 19, 19, 32, 63313, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equipmentsponsorstatus",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
    ]
