# Generated by Django 1.11.17 on 2019-10-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0003_auto_20191030_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentsponsorstatus",
            name="approve_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
