# Generated by Django 1.11.17 on 2019-10-30 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0004_auto_20191030_1920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentsponsorstatus",
            name="approver",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
