# Generated by Django 1.11.17 on 2019-11-04 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0006_auto_20191101_1145"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipmentsponsorstatus",
            old_name="approve_at",
            new_name="state_changed_at",
        ),
        migrations.AddField(
            model_name="equipment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2019, 11, 4, 17, 14, 24, 595279, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="equipmentsponsorstatus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2019, 11, 4, 17, 15, 35, 575819, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipmentsponsorstatus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
