# Generated by Django 1.11.17 on 2019-11-11 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0010_auto_20191108_1406"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="model",
            new_name="equipment_model",
        ),
    ]
