# Generated by Django 1.11.17 on 2019-11-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0011_auto_20191111_1631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="brand",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="calibration_company",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="calibration_cycle",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Annual"), (1, "Every 2 years"), (2, "Every 3 years")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_model",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Manometer"), (1, "Blower Door Fan"), (2, "Laser Tape Measure")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="expired_equipment",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to previous expired version of this equipment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.Equipment",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serial",
            field=models.CharField(max_length=255),
        ),
    ]
