# Generated by Django 1.11.26 on 2020-02-18 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0014_auto_20200213_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="assignees",
            field=models.ManyToManyField(
                related_name="equipment_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
    ]
