# Generated by Django 3.2.10 on 2022-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0015_equipment_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="calibration_documentation",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Calibration Documentation"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="equipmentsponsorstatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalequipmentsponsorstatus",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
