# Generated by Django 4.0.7 on 2022-09-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0016_auto_20220201_1019"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalequipmentsponsorstatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical equipment sponsor status",
                "verbose_name_plural": "historical equipment sponsor statuss",
            },
        ),
        migrations.AlterField(
            model_name="historicalequipmentsponsorstatus",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
