# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("builder_agreement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbuilderagreementdocument",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.Company",
            ),
        ),
    ]
