# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("subdivision", "0001_initial"),
        ("builder_agreement", "0003_auto_20181008_1815"),
        ("eep_program", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="subdivision.Subdivision",
            ),
        ),
        migrations.AddField(
            model_name="builderagreementdocument",
            name="builder_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="builder_agreement.BuilderAgreement",
            ),
        ),
        migrations.AddField(
            model_name="builderagreementdocument",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builder_agreement_document",
                to="company.Company",
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="builder_org",
            field=models.ForeignKey(
                help_text="The name of the builder the agreement is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builder_agreements",
                to="company.Company",
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.Company"
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="documents",
            field=models.ManyToManyField(
                help_text="Any supporting documentation that pertains to this builder agreement",
                related_name="builderagreement_supplement_documents",
                through="builder_agreement.BuilderAgreementDocument",
                to="company.Company",
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="eep_programs",
            field=models.ManyToManyField(
                help_text="The name of the Energy Efficiency Programs this agreement will cover.  Incentive payments will check this.",
                to="eep_program.EEPProgram",
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                help_text="The sudivision this agreement will cover.  If this for custom homes you may leave this blank",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subdivision.Subdivision",
            ),
        ),
    ]
