# Generated by Django 1.11.17 on 2019-05-28 15:29

import axis.builder_agreement.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder_agreement", "0006_auto_20190214_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderagreement",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="The hard copy of the builder agreement.",
                max_length=512,
                null=True,
                upload_to=axis.builder_agreement.models.builder_agreement_file_name,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="document",
            field=models.TextField(
                blank=True,
                help_text="The hard copy of the builder agreement.",
                max_length=512,
                null=True,
            ),
        ),
    ]
