# Generated by Django 1.11.17 on 2019-08-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("builder_agreement", "0009_remove_builder_agreement_document_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="builder_org",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The name of the builder the agreement is for",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.Company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The sudivision this agreement will cover.  If this for custom homes you may leave this blank",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="subdivision.Subdivision",
            ),
        ),
    ]
