# Generated by Django 4.0.7 on 2022-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder_agreement", "0012_merge_20200811_1942"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalbuilderagreement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Builder Agreement",
                "verbose_name_plural": "historical Builder Agreements",
            },
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
