# Generated by Django 1.11.17 on 2019-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subdivision", "0002_historicalsubdivision_history_change_reason_foo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="created_date",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="modified_date",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="subdivision",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subdivision",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
