# Generated by Django 1.11.17 on 2019-08-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subdivision", "0003_auto_20190531_1224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="builder_org",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Type the first few letters of the name of the Builder that is building all homes in this subdivision, and select the correct company from the list presented.  If the correct company is not available, click "Add New" to add a new Builder or Builder association.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.BuilderOrganization",
                verbose_name="Builder",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Type the first few letters of the name of the city of the location and select the correct city/state/county combination from the list presented. If the correct city is not available, click "Add New" to add a city to the database.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.City",
                verbose_name="City/State/County",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="climate_zone",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.ClimateZone",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="community",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='A community, also known as a "master-planned community", is a parcel of land in which one or more builders intend to build one or more subdivisions.  Select the community from the list presented.  If the correct community is not available, click "Add New" to add a new community or community association.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="community.Community",
                verbose_name="Community Name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="county",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.County",
                verbose_name="County",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="geocode_response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The response this place was constructed from.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.GeocodeResponse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="metro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.Metro",
                verbose_name="Metro",
            ),
        ),
    ]
