# Generated by Django 1.11.17 on 2019-08-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subdivision", "0004_auto_20190826_2024"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplanapproval",
            name="thermostat_qty",
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
