# Generated by Django 3.2.4 on 2021-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subdivision", "0006_auto_20200128_1940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eepprogramsubdivisionstatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="floorplanapproval",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubdivision",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subdivision",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
