# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("levenshtein_distance", models.PositiveIntegerField()),
                ("profile_delta", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                ("import_failed", models.BooleanField(default=False)),
                ("import_error", models.CharField(blank=True, max_length=500, null=True)),
                ("import_traceback", models.TextField(blank=True, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("project_id", models.CharField(blank=True, max_length=25, null=True)),
                ("checklist", models.CharField(max_length=100)),
                ("scoring_path", models.CharField(max_length=50)),
                ("builder", models.CharField(max_length=100)),
                ("rough_in_location", models.CharField(blank=True, max_length=255, null=True)),
                ("street_line1", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=25, null=True)),
                ("state_abbreviation", models.CharField(max_length=25)),
                ("state", models.CharField(max_length=25)),
                ("zipcode", models.CharField(blank=True, max_length=15, null=True)),
                ("county", models.CharField(blank=True, max_length=50, null=True)),
                ("unit_count", models.IntegerField(default=0)),
                ("certification_level", models.CharField(blank=True, max_length=25, null=True)),
                ("certificate_number", models.IntegerField(blank=True, null=True)),
                ("certificate_sent_date", models.DateField(blank=True, null=True)),
                ("community_project", models.CharField(blank=True, max_length=100, null=True)),
                ("certification_type", models.CharField(blank=True, max_length=25, null=True)),
                ("hers_score", models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                "permissions": (("view_certification", "View Certification"),),
            },
        ),
    ]
