# Generated by Django 1.11.17 on 2019-05-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0005_auto_20190522_0025"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="builderagreement",
            options={"permissions": (("view_builderagreement", "View Builder Agreement"),)},
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="company",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_enrolled_agreements",
                to="company.Company",
            ),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="owner",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_managed_agreements",
                to="company.Company",
            ),
        ),
    ]
