# Generated by Django 1.11.17 on 2019-05-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0006_auto_20190528_1946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderagreement",
            name="certification_program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_agreements",
                to="eep_program.EEPProgram",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="certification_program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="eep_program.EEPProgram",
            ),
        ),
    ]
