# Generated by Django 1.11.17 on 2019-06-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0007_auto_20190529_0806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderagreement",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("singlefamily", "Single family"),
                    ("multifamily", "Multifamily"),
                    ("land_development", "Land Development"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("singlefamily", "Single family"),
                    ("multifamily", "Multifamily"),
                    ("land_development", "Land Development"),
                ],
                max_length=100,
            ),
        ),
    ]
