# Generated by Django 1.11.17 on 2019-06-03 23:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0008_auto_20190603_0623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("signed", "Signed"),
                    ("verified", "Cerified"),
                    ("countersigned", "Countersigned"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("signed", "Signed"),
                    ("verified", "Cerified"),
                    ("countersigned", "Countersigned"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
    ]
