# Generated by Django 1.11.17 on 2019-06-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0011_auto_20190605_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="builderagreement",
            name="countersigned_agreement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="countersigned_agreement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
    ]
