# Generated by Django 1.11.17 on 2019-06-20 04:47

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0013_auto_20190607_1559"),
    ]

    operations = [
        migrations.RenameField(
            model_name="builderagreement",
            old_name="countersigned_agreement",
            new_name="certifying_document",
        ),
        migrations.RenameField(
            model_name="historicalbuilderagreement",
            old_name="countersigned_agreement",
            new_name="certifying_document",
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="certification_program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_hirl_agreements",
                to="eep_program.EEPProgram",
            ),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("signed", "Signed"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Verified"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("signed", "Signed"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Verified"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
    ]
