# Generated by Django 1.11.17 on 2019-07-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0014_auto_20190620_0447"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="builderagreement",
            name="project_type",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="project_type",
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="is_land_development",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="is_multifamily",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="is_singlefamily",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="is_land_development",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="is_multifamily",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="is_singlefamily",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="website",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="website",
            field=models.CharField(max_length=100),
        ),
    ]
