# Generated by Django 1.11.17 on 2019-07-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0015_split_project_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="builderagreement",
            name="website_contact_cell_number",
            field=models.CharField(default="000-000-0000", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="website_contact_email_address",
            field=models.CharField(default="moo@aol.com", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="website_contact_fax_number",
            field=models.CharField(default="000-000-0000", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="website_contact_name",
            field=models.CharField(default="guy", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="website_contact_phone_number",
            field=models.CharField(default="000-000-0000", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="website_contact_title",
            field=models.CharField(default="title", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="website_contact_cell_number",
            field=models.CharField(default="000-000-0000", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="website_contact_email_address",
            field=models.CharField(default="moo@aol.com", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="website_contact_fax_number",
            field=models.CharField(default="000-000-0000", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="website_contact_name",
            field=models.CharField(default="guy", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="website_contact_phone_number",
            field=models.CharField(default="000-000-0000", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="website_contact_title",
            field=models.CharField(default="title", max_length=100),
            preserve_default=False,
        ),
    ]
