# Generated by Django 1.11.17 on 2019-07-23 14:29

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0016_auto_20190718_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="builderagreement",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("signed", "Signed"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Verified"),
                    ("retired", "Retired"),
                    ("signed_fake", "Signed (faked)"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("signed", "Signed"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Verified"),
                    ("retired", "Retired"),
                    ("signed_fake", "Signed (faked)"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
    ]
