# Generated by Django 1.11.17 on 2019-07-31 21:09

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0017_auto_20190723_1429"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="builderagreement",
            name="certification_program",
        ),
        migrations.RemoveField(
            model_name="builderagreement",
            name="is_land_development",
        ),
        migrations.RemoveField(
            model_name="builderagreement",
            name="is_multifamily",
        ),
        migrations.RemoveField(
            model_name="builderagreement",
            name="is_singlefamily",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="certification_program",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="is_land_development",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="is_multifamily",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="is_singlefamily",
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("signed", "Signed"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Verified"),
                    ("retired", "Retired"),
                    ("signed_fake", "signed_fake"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("signed", "Signed"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Verified"),
                    ("retired", "Retired"),
                    ("signed_fake", "signed_fake"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
    ]
