# Generated by Django 1.11.17 on 2019-09-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0018_auto_20190731_2109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.Company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.Company",
            ),
        ),
    ]
