# Generated by Django 1.11.26 on 2019-11-26 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0010_validationdata_remove"),
        ("customer_hirl", "0019_auto_20190925_1900"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCertification",
            fields=[
                ("import_failed", models.BooleanField(default=False)),
                ("import_error", models.CharField(blank=True, max_length=500, null=True)),
                ("import_traceback", models.TextField(blank=True, null=True)),
                ("id", models.IntegerField(db_index=True)),
                ("project_id", models.CharField(blank=True, max_length=25, null=True)),
                ("checklist", models.CharField(max_length=100)),
                ("scoring_path", models.CharField(max_length=50)),
                ("builder", models.CharField(max_length=100)),
                ("rough_in_location", models.CharField(blank=True, max_length=255, null=True)),
                ("street_line1", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=25, null=True)),
                ("state_abbreviation", models.CharField(max_length=25)),
                ("state", models.CharField(max_length=25)),
                ("zipcode", models.CharField(blank=True, max_length=15, null=True)),
                ("county", models.CharField(blank=True, max_length=50, null=True)),
                ("unit_count", models.IntegerField(default=0)),
                ("certification_level", models.CharField(blank=True, max_length=25, null=True)),
                ("certificate_number", models.IntegerField(blank=True, null=True)),
                ("certificate_sent_date", models.DateField(blank=True, null=True)),
                ("community_project", models.CharField(blank=True, max_length=100, null=True)),
                ("certification_type", models.CharField(blank=True, max_length=25, null=True)),
                ("hers_score", models.CharField(blank=True, max_length=25, null=True)),
                ("created_date", models.DateField(blank=True, editable=False)),
                ("modified_date", models.DateField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="home.Home",
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical certification",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="certification",
            name="created_date",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certification",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
    ]
