# Generated by Django 1.11.26 on 2020-01-28 19:40

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0020_auto_20191126_0709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
    ]
