# Generated by Django 1.11.26 on 2020-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0022_historicalverifieragreement_verifieragreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="mailing_address_city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="mailing_address_state",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="mailing_address_street_line1",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="mailing_address_street_line2",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="mailing_address_zipcode",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="shipping_address_city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="shipping_address_state",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="shipping_address_street_line1",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="shipping_address_street_line2",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="shipping_address_zipcode",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="mailing_address_city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="mailing_address_state",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="mailing_address_street_line1",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="mailing_address_street_line2",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="mailing_address_zipcode",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="shipping_address_city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="shipping_address_state",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="shipping_address_street_line1",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="shipping_address_street_line2",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="shipping_address_zipcode",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
