# Generated by Django 1.11.26 on 2020-04-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0002_auto_20190531_1224"),
        ("customer_hirl", "0024_auto_20200420_0933"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvidedService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "permissions": (("view_verifieragreement", "View Verifier Agreement"),),
            },
        ),
        migrations.CreateModel(
            name="ServedArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geographic.Place"
                    ),
                ),
                (
                    "verifier_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer_hirl.VerifierAgreement",
                    ),
                ),
            ],
            options={
                "permissions": (("view_verifieragreement", "View Verifier Agreement"),),
            },
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="provided_service",
            field=models.ManyToManyField(to="customer_hirl.ProvidedService"),
        ),
    ]
