# Generated by Django 1.11.26 on 2020-04-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0007_auto_20200420_1704"),
        ("customer_hirl", "0025_auto_20200420_0958"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servedarea",
            name="place",
        ),
        migrations.RemoveField(
            model_name="servedarea",
            name="verifier_agreement",
        ),
        migrations.RenameField(
            model_name="verifieragreement",
            old_name="provided_service",
            new_name="provided_services",
        ),
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="applicant_place",
        ),
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="mailing_place",
        ),
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="shipping_place",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="applicant_place",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="mailing_place",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="shipping_place",
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="applicant_geocode",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="mailing_geocode",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="shipping_geocode",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="applicant_geocode",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_verifier_agreement_applicant_place",
                to="geocoder.Geocode",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="mailing_geocode",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_verifier_agreement_mailing_place",
                to="geocoder.Geocode",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="shipping_geocode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_verifier_agreement_shipping_place",
                to="geocoder.Geocode",
            ),
        ),
        migrations.DeleteModel(
            name="ServedArea",
        ),
    ]
