# Generated by Django 1.11.26 on 2020-04-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0026_auto_20200420_1704"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="applicant_geocode",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="applicant_geocode",
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="company_officer_email",
            field=models.EmailField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="company_officer_first_name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="company_officer_last_name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="company_officer_phone_number",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="company_officer_email",
            field=models.EmailField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="company_officer_first_name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="company_officer_last_name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="company_officer_phone_number",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
