# Generated by Django 1.11.26 on 2020-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0002_auto_20190531_1224"),
        ("customer_hirl", "0028_auto_20200422_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifieragreement",
            name="counties",
            field=models.ManyToManyField(blank=True, to="geographic.County"),
        ),
    ]
