# Generated by Django 1.11.26 on 2020-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0030_auto_20200422_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalverifieragreement",
            name="administrative_contact_email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalverifieragreement",
            name="applicant_email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalverifieragreement",
            name="applicant_title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalverifieragreement",
            name="company_officer_email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="administrative_contact_email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="applicant_email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="applicant_title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="company_officer_email",
            field=models.EmailField(max_length=100),
        ),
    ]
