# Generated by Django 1.11.26 on 2020-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0031_auto_20200423_1641"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="agreement_expiration_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="agreement_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="agreement_expiration_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="agreement_start_date",
            field=models.DateField(null=True),
        ),
    ]
