# Generated by Django 1.11.26 on 2020-04-27 15:25

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0032_auto_20200427_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
    ]
