# Generated by Django 1.11.26 on 2020-04-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0007_auto_20200415_1542"),
        ("customer_hirl", "0034_auto_20200429_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="certifying_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="certifying_document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
    ]
