# Generated by Django 1.11.26 on 2020-04-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0007_auto_20200415_1542"),
        ("customer_hirl", "0035_auto_20200429_1411"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="certifying_document",
        ),
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="signed_agreement",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="certifying_document",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="signed_agreement",
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="officer_certifying_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="officer_signed_agreement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="verifier_certifying_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="verifier_signed_agreement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="officer_certifying_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="officer_signed_agreement",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="verifier_certifying_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="verifier_signed_agreement",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="mailing_geocode",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="geocoder.Geocode"
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="shipping_geocode",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
    ]
