# Generated by Django 1.11.26 on 2020-04-29 15:08

import axis.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0007_auto_20200415_1542"),
        ("customer_hirl", "0036_auto_20200429_1449"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="data",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="data",
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="hirl_certifying_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="hirl_signed_agreement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="officer_agreement_docusign_data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="verifier_agreement_docusign_data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="hirl_certifying_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="hirl_signed_agreement",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="officer_agreement_docusign_data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="verifier_agreement_docusign_data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
    ]
