# Generated by Django 1.11.26 on 2020-05-01 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_hirl", "0037_auto_20200429_1508"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="company",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="company",
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="verifier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="verifier",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_enrolled_verifier_agreements",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
