# Generated by Django 1.11.26 on 2020-05-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0007_auto_20200415_1542"),
        ("customer_hirl", "0038_auto_20200501_0527"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="insurance_certificate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="insurance_expiration_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="insurance_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="insurance_certificate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="insurance_expiration_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="insurance_start_date",
            field=models.DateField(null=True),
        ),
    ]
