# Generated by Django 1.11.26 on 2020-05-01 13:04

import axis.core.fields
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0039_auto_20200501_0633"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="hirl_agreement_docusign_data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="hirl_agreement_docusign_data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalverifieragreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
    ]
