# Generated by Django 1.11.26 on 2020-05-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0040_auto_20200501_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifieragreement",
            name="insurance_certificate",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.CustomerDocument",
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="mailing_geocode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="geocoder.Geocode"
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="shipping_geocode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
    ]
