# Generated by Django 1.11.26 on 2020-05-06 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0041_auto_20200506_0457"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalverifieragreement",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="verifieragreement",
            name="insurance_certificate",
        ),
    ]
