# Generated by Django 1.11.26 on 2020-05-13 09:09

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0042_auto_20200506_1738"),
    ]

    operations = [
        migrations.RenameField(
            model_name="builderagreement",
            old_name="marketing_contact_name",
            new_name="marketing_contact_first_name",
        ),
        migrations.RenameField(
            model_name="builderagreement",
            old_name="payment_contact_name",
            new_name="marketing_contact_last_name",
        ),
        migrations.RenameField(
            model_name="builderagreement",
            old_name="primary_contact_name",
            new_name="payment_contact_first_name",
        ),
        migrations.RenameField(
            model_name="builderagreement",
            old_name="secondary_contact_name",
            new_name="payment_contact_last_name",
        ),
        migrations.RenameField(
            model_name="builderagreement",
            old_name="website_contact_name",
            new_name="primary_contact_first_name",
        ),
        migrations.RenameField(
            model_name="historicalbuilderagreement",
            old_name="marketing_contact_name",
            new_name="marketing_contact_first_name",
        ),
        migrations.RenameField(
            model_name="historicalbuilderagreement",
            old_name="payment_contact_name",
            new_name="marketing_contact_last_name",
        ),
        migrations.RenameField(
            model_name="historicalbuilderagreement",
            old_name="primary_contact_name",
            new_name="payment_contact_first_name",
        ),
        migrations.RenameField(
            model_name="historicalbuilderagreement",
            old_name="secondary_contact_name",
            new_name="payment_contact_last_name",
        ),
        migrations.RenameField(
            model_name="historicalbuilderagreement",
            old_name="website_contact_name",
            new_name="primary_contact_first_name",
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="primary_contact_last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="secondary_contact_first_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="secondary_contact_last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="website_contact_first_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="website_contact_last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="primary_contact_last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="secondary_contact_first_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="secondary_contact_last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="website_contact_first_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="website_contact_last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalverifieragreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("retired", "Retired"),
                ],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
    ]
