# Generated by Django 1.11.26 on 2020-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0045_coidocument_historicalcoidocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="coidocument",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("document", "Document"), ("image", "Image"), ("", "Other")],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="historicalcoidocument",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("document", "Document"), ("image", "Image"), ("", "Other")],
                max_length=15,
            ),
        ),
    ]
