# Generated by Django 1.11.26 on 2020-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0047_auto_20200515_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coidocument",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coidocument",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcoidocument",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcoidocument",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
