# Generated by Django 1.11.26 on 2020-05-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0003_usstate"),
        ("customer_hirl", "0049_auto_20200518_1453"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verifieragreement",
            name="counties",
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="us_states",
            field=models.ManyToManyField(blank=True, to="geographic.USState"),
        ),
    ]
