# Generated by Django 1.11.26 on 2020-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0051_auto_20200519_0829"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverifieragreement",
            name="agreement_verifier_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="Verifier ID"),
        ),
        migrations.AddField(
            model_name="verifieragreement",
            name="agreement_verifier_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="Verifier ID"),
        ),
    ]
