# Generated by Django 1.11.26 on 2020-06-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0010_auto_20200603_1817"),
        ("customer_hirl", "0052_auto_20200519_0835"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLBuilderOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=30)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.BuilderOrganization",
                    ),
                ),
            ],
        ),
    ]
