# Generated by Django 1.11.26 on 2020-06-04 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0053_hirlbuilderorganization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirlbuilderorganization",
            old_name="company",
            new_name="builder_organization",
        ),
    ]
