# Generated by Django 1.11.26 on 2020-06-04 17:59

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0054_auto_20200604_1655"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlbuilderorganization",
            name="invoice_number",
        ),
        migrations.AddField(
            model_name="hirlbuilderorganization",
            name="data",
            field=axis.core.fields.AxisJSONField(default=dict),
        ),
    ]
