# Generated by Django 1.11.26 on 2020-06-09 12:41

import axis.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0012_auto_20200605_1822"),
        ("customer_hirl", "0055_auto_20200604_1759"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLRaterOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                (
                    "rater_organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="company.RaterOrganization"
                    ),
                ),
            ],
        ),
    ]
