# Generated by Django 2.2 on 2020-08-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0058_auto_20200702_1643"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="builderagreement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="certification",
            options={},
        ),
        migrations.AlterModelOptions(
            name="providedservice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="verifieragreement",
            options={},
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="mailing_geocode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
    ]
