# Generated by Django 1.11.26 on 2020-07-06 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0059_merge_20200701_0829"),
        ("customer_hirl", "0058_auto_20200702_1643"),
    ]

    operations = []
