# Generated by Django 1.11.26 on 2020-07-08 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0060_merge_20200706_1153"),
        ("customer_hirl", "0053_hirlproject_historicalhirlproject"),
    ]

    operations = []
