# Generated by Django 1.11.26 on 2020-07-08 08:38

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_auto_20200311_1141"),
        ("customer_hirl", "0061_merge_20200708_0820"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hirlproject",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="historicalhirlproject",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Project",
            },
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="home",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_project",
                to="home.Home",
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="state",
            field=django_fsm.FSMField(
                choices=[("new", "New"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="home",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="home.Home",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="state",
            field=django_fsm.FSMField(
                choices=[("new", "New"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="new",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="mailing_geocode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
    ]
