# Generated by Django 1.11.26 on 2020-07-08 08:55

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0062_auto_20200708_0838"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="accessory_description",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="accessory_description",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="ngbs_project_id",
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="ngbs_project_id",
            field=models.CharField(db_index=True, default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="state",
            field=django_fsm.FSMField(
                choices=[("new", "New"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="state",
            field=django_fsm.FSMField(
                choices=[("new", "New"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="new",
                max_length=50,
            ),
        ),
    ]
