# Generated by Django 1.11.26 on 2020-07-08 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0063_auto_20200708_0855"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirlproject",
            old_name="ngbs_project_id",
            new_name="hirl_project_id",
        ),
        migrations.RenameField(
            model_name="historicalhirlproject",
            old_name="ngbs_project_id",
            new_name="hirl_project_id",
        ),
    ]
