# Generated by Django 1.11.26 on 2020-07-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0011_merge_20200701_0829"),
        ("customer_hirl", "0066_auto_20200722_1217"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirlproject",
            old_name="builder",
            new_name="builder_organization",
        ),
        migrations.RenameField(
            model_name="historicalhirlproject",
            old_name="builder",
            new_name="builder_organization",
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="project_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="project_geocode",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="home_address_geocode",
            field=models.ForeignKey(
                help_text="Geocode address entered by Verifier on project registration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="home_address_geocode",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Geocode address entered by Verifier on project registration",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
    ]
