# Generated by Django 2.2 on 2020-07-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0067_auto_20200722_1224"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="builderagreement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="certification",
            options={},
        ),
        migrations.AlterModelOptions(
            name="providedservice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="verifieragreement",
            options={},
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="mailing_geocode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="green_energy_badges",
            field=models.ManyToManyField(blank=True, to="customer_hirl.HIRLGreenEnergyBadge"),
        ),
    ]
