# Generated by Django 2.2 on 2020-07-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0011_merge_20200701_0829"),
        ("customer_hirl", "0068_auto_20200728_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="home_address_geocode_response",
            field=models.ForeignKey(
                help_text="Selected by user in case of multiple valid results, automatically when we have one result and empty when geocode do not have valid results",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.GeocodeResponse",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="home_address_geocode_response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Selected by user in case of multiple valid results, automatically when we have one result and empty when geocode do not have valid results",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.GeocodeResponse",
            ),
        ),
    ]
