# Generated by Django 2.2 on 2020-07-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0069_auto_20200729_2058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="home_address_geocode",
            field=models.ForeignKey(
                default=1,
                help_text="Geocode address entered by Verifier on project registration",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="geocoder.Geocode",
            ),
            preserve_default=False,
        ),
    ]
