# Generated by Django 2.2 on 2020-07-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0070_auto_20200729_2110"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="hirl_project_id",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="hirl_project_id",
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="home_address_geocode_response",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected by user in case of multiple valid results, automatically when we have one result and empty when geocode do not have valid results",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.GeocodeResponse",
            ),
        ),
    ]
