# Generated by Django 2.2 on 2020-07-30 19:25

from django.db import migrations


def create_green_energy_badges(apps, schema_editor):
    HIRLGreenEnergyBadge = apps.get_model("customer_hirl", "HIRLGreenEnergyBadge")

    lst = [
        {"name": "Wellness", "slug": "wellness"},
        {"name": "Net Zero Energy", "slug": "net_zero_energy"},
        {"name": "Zero Water", "slug": "zero_water"},
        {"name": "Smart Home", "slug": "smart_home"},
        {"name": "Resilience", "slug": "resilience"},
        {"name": "Universal Design", "slug": "universal_design"},
    ]
    for data in lst:
        HIRLGreenEnergyBadge.objects.get_or_create(name=data["name"], slug=data["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0071_auto_20200730_1307"),
    ]

    operations = [
        migrations.RunPython(create_green_energy_badges),
    ]
