# Generated by Django 2.2 on 2020-08-06 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0072_auto_20200730_1925"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="commercial_space_type",
            field=models.CharField(
                blank=True,
                choices=[("core&shell", "Core & Shell"), ("full", "Full")],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="community_named_on_certificate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="multi_family_building_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="multi_family_number_of_units",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="multi_family_project_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="state_changed_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="total_commercial_space_footage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="commercial_space_type",
            field=models.CharField(
                blank=True,
                choices=[("core&shell", "Core & Shell"), ("full", "Full")],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="community_named_on_certificate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="multi_family_building_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="multi_family_number_of_units",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="multi_family_project_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="state_changed_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2020, 8, 6, 10, 3, 46, 589648, tzinfo=utc),
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="total_commercial_space_footage",
            field=models.FloatField(default=0),
        ),
    ]
