# Generated by Django 2.2 on 2020-08-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0073_auto_20200806_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="is_include_commercial_space",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_include_commercial_space",
            field=models.BooleanField(default=False),
        ),
    ]
