# Generated by Django 2.2 on 2020-08-06 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0074_auto_20200806_1013"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirlproject",
            old_name="total_commercial_space_footage",
            new_name="total_commercial_space",
        ),
        migrations.RenameField(
            model_name="historicalhirlproject",
            old_name="total_commercial_space_footage",
            new_name="total_commercial_space",
        ),
    ]
