# Generated by Django 2.2 on 2020-08-06 16:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0075_auto_20200806_1100"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLResponsibleName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
            ],
            options={
                "verbose_name": "Responsible Name",
                "verbose_name_plural": "Responsible Names",
            },
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="name_to_be_listed_on_commercial_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("same", "Same Name as Residential Builder/Developer"),
                    ("same", "Different Name(s) - email gbverifications"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="project_contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="project_contact_first_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="project_contact_last_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="project_contact_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="name_to_be_listed_on_commercial_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("same", "Same Name as Residential Builder/Developer"),
                    ("same", "Different Name(s) - email gbverifications"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="project_contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="project_contact_first_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="project_contact_last_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="project_contact_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_first_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_last_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="builder_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="builder_first_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="builder_last_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="application_packet_completion",
            field=models.ManyToManyField(
                blank=True,
                related_name="application_packet_responsible_names",
                to="customer_hirl.HIRLResponsibleName",
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="party_named_on_certificate",
            field=models.ManyToManyField(
                blank=True,
                related_name="party_on_certificate_responsible_names",
                to="customer_hirl.HIRLResponsibleName",
            ),
        ),
    ]
