# Generated by Django 2.2 on 2020-08-06 17:46

from django.db import migrations


def create_responsible_names(apps, schema_editor):
    HIRLResponsibleName = apps.get_model("customer_hirl", "HIRLResponsibleName")

    lst = [
        {"name": "Builder", "slug": "builder"},
        {"name": "Developer", "slug": "developer"},
        {"name": "Architect", "slug": "architect"},
        {"name": "Owner", "slug": "owner"},
    ]
    for data in lst:
        HIRLResponsibleName.objects.get_or_create(name=data["name"], slug=data["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0076_auto_20200806_1636"),
    ]

    operations = [
        migrations.RunPython(create_responsible_names),
    ]
