# Generated by Django 2.2 on 2020-08-07 10:58

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0077_auto_20200806_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_first_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_last_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.BuilderOrganization",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="commercial_space_type",
            field=models.CharField(
                blank=True,
                choices=[("core&shell", "Core & Shell"), ("full", "Full")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="community_named_on_certificate",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="multi_family_building_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="multi_family_number_of_units",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="multi_family_project_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="name_to_be_listed_on_commercial_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("same", "Same Name as Residential Builder/Developer"),
                    ("same", "Different Name(s) - email gbverifications"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="project_contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="project_contact_first_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="project_contact_last_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="project_contact_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="rough_inspection_schedule",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Any date"), (1, "Rough inspection planned within the next 5 days")],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="total_commercial_space",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="builder_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="builder_first_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="builder_last_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="builder_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="commercial_space_type",
            field=models.CharField(
                blank=True,
                choices=[("core&shell", "Core & Shell"), ("full", "Full")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="community_named_on_certificate",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="multi_family_building_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="multi_family_number_of_units",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="multi_family_project_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="name_to_be_listed_on_commercial_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("same", "Same Name as Residential Builder/Developer"),
                    ("same", "Different Name(s) - email gbverifications"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="project_contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="project_contact_first_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="project_contact_last_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="project_contact_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="rough_inspection_schedule",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Any date"), (1, "Rough inspection planned within the next 5 days")],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="total_commercial_space",
            field=models.FloatField(null=True),
        ),
    ]
