# Generated by Django 2.2 on 2020-08-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0078_auto_20200807_1058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="is_include_commercial_space",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="is_include_commercial_space",
            field=models.BooleanField(null=True),
        ),
    ]
