# Generated by Django 2.2 on 2020-08-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0079_auto_20200807_1101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="builder_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.BuilderOrganization",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="multi_family_building_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="multi_family_number_of_units",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="rough_inspection_schedule",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Any date"), (1, "Rough inspection planned within the next 5 days")],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="total_commercial_space",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="multi_family_building_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="multi_family_number_of_units",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="rough_inspection_schedule",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Any date"), (1, "Rough inspection planned within the next 5 days")],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="total_commercial_space",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
