# Generated by Django 2.2 on 2020-08-11 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0080_auto_20200807_1115"),
        ("customer_hirl", "0059_auto_20200811_0839"),
    ]

    operations = []
