# Generated by Django 2.2 on 2020-08-12 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0081_merge_20200811_1942"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="rough_inspection_schedule",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="rough_inspection_schedule",
        ),
    ]
