# Generated by Django 2.2 on 2020-09-10 07:53

import json
from django.db import migrations, models


def forward_data_migration(apps, schema):
    HIRLRaterUser = apps.get_model("customer_hirl", "HIRLRaterUser")
    for rater in HIRLRaterUser.objects.all():
        rater.hirl_id = rater.data["ID"]
        print(rater.hirl_id)
        rater.save()


def revert_migration(apps, schema):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0082_auto_20200812_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlrateruser",
            name="hirl_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Internal ID"),
            preserve_default=False,
        ),
        migrations.RunPython(code=forward_data_migration, reverse_code=revert_migration),
    ]
