# Generated by Django 2.2 on 2020-09-25 12:35

from django.db import migrations


def builder_organization_forward_data_migration(apps, schema):
    HIRLBuilderOrganization = apps.get_model("customer_hirl", "HIRLBuilderOrganization")
    for builder_organization in HIRLBuilderOrganization.objects.all():
        builder_organization.hirl_id = builder_organization.data["ID"]
        print(builder_organization.hirl_id)
        builder_organization.save()


def revert_migration(apps, schema):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0084_auto_20200925_1203"),
    ]

    operations = [
        migrations.RunPython(
            code=builder_organization_forward_data_migration, reverse_code=revert_migration
        )
    ]
