# Generated by Django 2.2 on 2020-10-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0085_auto_20200925_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="builder_organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="checklist_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="scoring_path_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="verifier_name",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="verifier_organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="builder_organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="checklist_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="scoring_path_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="verifier_name",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="verifier_organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
