# Generated by Django 2.2 on 2020-10-01 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0086_auto_20201001_1015"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certification",
            old_name="verifier_organization_id",
            new_name="verifier_id",
        ),
        migrations.RenameField(
            model_name="historicalcertification",
            old_name="verifier_organization_id",
            new_name="verifier_id",
        ),
    ]
