# Generated by Django 2.2 on 2020-10-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0088_hirlbuilderagreementstatus_hirlverifieragreementstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlbuilderagreementstatus",
            name="hirl_expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlbuilderagreementstatus",
            name="hirl_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlverifieragreementstatus",
            name="hirl_expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlverifieragreementstatus",
            name="hirl_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
