# Generated by Django 2.2 on 2020-10-04 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0090_auto_20201004_0944"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirlbuilderagreementstatus",
            old_name="hirl_verifier_id",
            new_name="hirl_builder_id",
        ),
        migrations.RenameField(
            model_name="hirlverifieragreementstatus",
            old_name="hirl_builder_id",
            new_name="hirl_verifier_id",
        ),
    ]
