# Generated by Django 2.2 on 2020-10-04 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0091_auto_20201004_0947"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirlbuilderagreementstatus",
            old_name="hirl_builder_agreement",
            new_name="builder_agreement",
        ),
        migrations.RenameField(
            model_name="hirlverifieragreementstatus",
            old_name="hirl_verifier_agreement",
            new_name="verifier_agreement",
        ),
    ]
