# Generated by Django 2.2 on 2020-10-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0092_auto_20201004_1004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlbuilderagreementstatus",
            name="builder_agreement",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_hirl.BuilderAgreement",
            ),
        ),
        migrations.AlterField(
            model_name="hirlverifieragreementstatus",
            name="verifier_agreement",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_hirl.VerifierAgreement",
            ),
        ),
    ]
