# Generated by Django 2.2 on 2020-10-06 09:11

import axis.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0093_auto_20201004_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLBuilderInsurance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("hirl_id", models.PositiveIntegerField(verbose_name="Internal ID")),
                (
                    "hirl_insurance_type",
                    models.CharField(
                        choices=[
                            (1, "Automobile Liability"),
                            (2, "Excess/Umbrella Liability"),
                            (3, "General Liability"),
                            (4, "Professional Liability"),
                            (5, "Workers Compensation"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("hirl_insurance_name", models.CharField(blank=True, max_length=255)),
                ("hirl_policy_number", models.CharField(blank=True, max_length=255)),
                ("hirl_policy_effective_date", models.DateField(blank=True, null=True)),
                ("hirl_policy_expiration_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "builder_agreement",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer_hirl.BuilderAgreement",
                    ),
                ),
            ],
        ),
    ]
