# Generated by Django 2.2 on 2020-10-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0094_hirlbuilderinsurance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlbuilderinsurance",
            name="hirl_insurance_type",
            field=models.IntegerField(
                choices=[
                    (1, "Automobile Liability"),
                    (2, "Excess/Umbrella Liability"),
                    (3, "General Liability"),
                    (4, "Professional Liability"),
                    (5, "Workers Compensation"),
                ],
                null=True,
            ),
        ),
    ]
