# Generated by Django 2.2 on 2020-10-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0096_hirlverifierinsurance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlverifierinsurance",
            name="builder_agreement",
        ),
        migrations.AddField(
            model_name="hirlverifierinsurance",
            name="coi_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_hirl.COIDocument",
            ),
        ),
    ]
