# Generated by Django 2.2 on 2020-10-12 14:31

import axis.core.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0030_auto_20200714_1352"),
        ("customer_hirl", "0097_auto_20201006_1600"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="builderagreement",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("insurance_received", "Insurance Received"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="HIRLVerifierAccreditationStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hirl_id", models.PositiveIntegerField(verbose_name="Internal ID")),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accreditation",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.Accreditation",
                    ),
                ),
            ],
        ),
    ]
