# Generated by Django 2.2 on 2020-10-15 14:57

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0030_auto_20200714_1352"),
        ("customer_hirl", "0100_auto_20201012_1511"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verifieragreement",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RemoveField(
            model_name="hirlverifieraccreditationstatus",
            name="accreditation",
        ),
        migrations.AddField(
            model_name="hirlverifieraccreditationstatus",
            name="accreditations",
            field=models.ManyToManyField(to="user_management.Accreditation"),
        ),
        migrations.AlterField(
            model_name="historicalverifieragreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
