# Generated by Django 2.2 on 2020-10-16 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_hirl", "0101_auto_20201015_1457"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLUserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_master_verifier", models.BooleanField(default=False)),
                ("is_wri_verifier", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "HI User Settings",
                "verbose_name_plural": "HI User Settings",
            },
        ),
    ]
