# Generated by Django 2.2 on 2020-10-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0102_hirluserprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirluserprofile",
            name="is_master_verifier",
            field=models.BooleanField(default=False, verbose_name="Master Verifier"),
        ),
        migrations.AlterField(
            model_name="hirluserprofile",
            name="is_wri_verifier",
            field=models.BooleanField(default=False, verbose_name="WRI Verifier"),
        ),
    ]
