# Generated by Django 2.2 on 2020-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0103_auto_20201027_1829"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="energy_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="eri",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="final_grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="final_reviewer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="final_verifier_grade_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="final_verifier_grades_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="hud_disaster_case_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="rough_grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="rough_reviewer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="rough_verifier_grade_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="rough_verifier_grades_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="verifier_certification_energy_path_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="water_path",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="water_path_selected",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="wri",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="energy_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="eri",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="final_grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="final_reviewer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="final_verifier_grade_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="final_verifier_grades_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="hud_disaster_case_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="rough_grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="rough_reviewer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="rough_verifier_grade_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="rough_verifier_grades_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="verifier_certification_energy_path_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="water_path",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="water_path_selected",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="wri",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
