# Generated by Django 2.2 on 2020-12-04 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0104_auto_20201203_1708"),
        ("customer_hirl", "0104_auto_20201201_1317"),
    ]

    operations = []
