# Generated by Django 2.2 on 2020-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0105_merge_20201204_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="state_change_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="state_change_reason",
            field=models.TextField(blank=True),
        ),
    ]
