# Generated by Django 2.2 on 2020-12-16 19:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0106_auto_20201209_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="builder_contractor_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="builder_contractor_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="builder_contractor_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="builder_contractor_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="builder_contractor_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="building_will_include_non_residential_space",
            field=models.BooleanField(
                default=False,
                verbose_name="Building(s) will include non-residential space (retail/commercial) ?",
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="intended_to_be_affordable_housing",
            field=models.BooleanField(
                default=False, verbose_name="Intended to be affordable housing?"
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="multi_family_project_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="multi_family_project_estimated_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="multi_family_project_website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="non_residential_space_to_be_included_in_certification",
            field=models.BooleanField(
                default=False, verbose_name="Non-residential space to be included in certification?"
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="seeking_fannie_mae_green_financing",
            field=models.BooleanField(
                default=False, verbose_name="Seeking Fannie Mae Green financing?"
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="seeking_freddie_mac_green_financing",
            field=models.BooleanField(
                default=False, verbose_name="Seeking Freddie Mac Green financing?"
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="seeking_hud_mortgage_insurance_premium_reduction",
            field=models.BooleanField(
                default=False, verbose_name="Seeking HUD Mortgage Insurance Premium Reduction?"
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="builder_contractor_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="builder_contractor_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="builder_contractor_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="builder_contractor_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="builder_contractor_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="building_will_include_non_residential_space",
            field=models.BooleanField(
                default=False,
                verbose_name="Building(s) will include non-residential space (retail/commercial) ?",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="intended_to_be_affordable_housing",
            field=models.BooleanField(
                default=False, verbose_name="Intended to be affordable housing?"
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="multi_family_project_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="multi_family_project_estimated_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="multi_family_project_website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="non_residential_space_to_be_included_in_certification",
            field=models.BooleanField(
                default=False, verbose_name="Non-residential space to be included in certification?"
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="seeking_fannie_mae_green_financing",
            field=models.BooleanField(
                default=False, verbose_name="Seeking Fannie Mae Green financing?"
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="seeking_freddie_mac_green_financing",
            field=models.BooleanField(
                default=False, verbose_name="Seeking Freddie Mac Green financing?"
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="seeking_hud_mortgage_insurance_premium_reduction",
            field=models.BooleanField(
                default=False, verbose_name="Seeking HUD Mortgage Insurance Premium Reduction?"
            ),
        ),
    ]
