# Generated by Django 2.2 on 2020-12-17 15:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0107_auto_20201216_1919"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="developer_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="developer_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="developer_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="developer_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="developer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="marketing_email",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="marketing_first_name",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="marketing_last_name",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="marketing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="sales_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="sales_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="sales_website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="marketing_email",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="marketing_first_name",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="marketing_last_name",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="marketing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="sales_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="sales_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="sales_website_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
