# Generated by Django 2.2 on 2020-12-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0108_auto_20201217_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="building_will_include_non_residential_space",
            field=models.BooleanField(
                null=True,
                default=False,
                verbose_name="Building(s) will include non-residential space (retail/commercial) ?",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="intended_to_be_affordable_housing",
            field=models.BooleanField(
                null=True, default=False, verbose_name="Intended to be affordable housing?"
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="non_residential_space_to_be_included_in_certification",
            field=models.BooleanField(
                null=True,
                default=False,
                verbose_name="Non-residential space to be included in certification?",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="seeking_fannie_mae_green_financing",
            field=models.BooleanField(
                null=True, default=False, verbose_name="Seeking Fannie Mae Green financing?"
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="seeking_freddie_mac_green_financing",
            field=models.BooleanField(
                null=True, default=False, verbose_name="Seeking Freddie Mac Green financing?"
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="seeking_hud_mortgage_insurance_premium_reduction",
            field=models.BooleanField(
                null=True,
                default=False,
                verbose_name="Seeking HUD Mortgage Insurance Premium Reduction?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="building_will_include_non_residential_space",
            field=models.BooleanField(
                null=True,
                default=False,
                verbose_name="Building(s) will include non-residential space (retail/commercial) ?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="intended_to_be_affordable_housing",
            field=models.BooleanField(
                null=True, default=False, verbose_name="Intended to be affordable housing?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="non_residential_space_to_be_included_in_certification",
            field=models.BooleanField(
                null=True,
                default=False,
                verbose_name="Non-residential space to be included in certification?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="seeking_fannie_mae_green_financing",
            field=models.BooleanField(
                null=True, default=False, verbose_name="Seeking Fannie Mae Green financing?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="seeking_freddie_mac_green_financing",
            field=models.BooleanField(
                null=True, default=False, verbose_name="Seeking Freddie Mac Green financing?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="seeking_hud_mortgage_insurance_premium_reduction",
            field=models.BooleanField(
                null=True,
                default=False,
                verbose_name="Seeking HUD Mortgage Insurance Premium Reduction?",
            ),
        ),
    ]
