# Generated by Django 2.2 on 2020-12-22 16:54

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0109_auto_20201218_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="architect_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="architect_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="architect_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="architect_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="architect_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="billing_email",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="billing_first_name",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="billing_last_name",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="billing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="billing_email",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="billing_first_name",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="billing_last_name",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="billing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
    ]
