# Generated by Django 2.2 on 2020-12-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0110_auto_20201222_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="building_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="story_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="building_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="story_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
