# Generated by Django 2.2 on 2020-12-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0111_auto_20201222_1810"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="billing_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="billing_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="billing_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="marketing_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="marketing_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="marketing_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="billing_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="billing_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="billing_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="marketing_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="marketing_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="marketing_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
