# Generated by Django 3.1.3 on 2020-12-30 12:18

import axis.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0113_auto_20201222_2036"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLProjectContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hirl_id", models.PositiveIntegerField(verbose_name="Internal ID")),
                (
                    "contact_type",
                    models.IntegerField(
                        choices=[(1, "Architect"), (1, "Developer"), (1, "Builder"), (4, "Owner")]
                    ),
                ),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
