# Generated by Django 3.1.3 on 2021-01-04 13:57

import django.db.models.deletion
from django.db import migrations, models

import axis.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0019_auto_20201230_1215"),
        ("customer_hirl", "0114_hirlprojectcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlprojectcontact",
            name="hirl_company_id",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Internal fkArchitectOrDeveloperID"
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectcontact",
            name="contact_type",
            field=models.IntegerField(
                choices=[(1, "Architect"), (2, "Developer"), (3, "Builder"), (4, "Owner")]
            ),
        ),
        migrations.CreateModel(
            name="HIRLProjectOwner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hirl_id", models.PositiveIntegerField(verbose_name="Internal ID")),
                ("name", models.TextField()),
                ("website", models.TextField(blank=True)),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community_owner_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.communityownerorganization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HIRLProjectDeveloper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hirl_id", models.PositiveIntegerField(verbose_name="Internal ID")),
                ("name", models.TextField()),
                ("website", models.TextField(blank=True)),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community_developer_owner_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.communitydeveloperownerorganization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HIRLProjectArchitect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hirl_id", models.PositiveIntegerField(verbose_name="Internal ID")),
                ("name", models.TextField()),
                ("website", models.TextField(blank=True)),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community_architects_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.communityarchitectsorganization",
                    ),
                ),
            ],
        ),
    ]
