# Generated by Django 3.1.3 on 2021-01-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0019_auto_20201230_1215"),
        ("customer_hirl", "0115_auto_20210104_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlprojectarchitect",
            name="community_architects_organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.communityarchitectsorganization",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectdeveloper",
            name="community_developer_owner_organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.communitydeveloperownerorganization",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectowner",
            name="community_owner_organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.communityownerorganization",
            ),
        ),
    ]
