# Generated by Django 3.1.3 on 2021-01-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0119_auto_20210106_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhirlproject",
            name="application_packet_completion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="customer_hirl.hirlresponsiblename",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="party_named_on_certificate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="customer_hirl.hirlresponsiblename",
            ),
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="application_packet_completion",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="application_packet_completion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_packet_completion",
                to="customer_hirl.hirlresponsiblename",
            ),
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="party_named_on_certificate",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="party_named_on_certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="party_named_on_certificate",
                to="customer_hirl.hirlresponsiblename",
            ),
        ),
    ]
