# Generated by Django 3.1.3 on 2021-01-07 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0120_auto_20210107_1029"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="builder_contractor_company_name",
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="builder_contractor_email",
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="builder_contractor_first_name",
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="builder_contractor_last_name",
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="builder_contractor_phone",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="builder_contractor_company_name",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="builder_contractor_email",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="builder_contractor_first_name",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="builder_contractor_last_name",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="builder_contractor_phone",
        ),
    ]
