# Generated by Django 3.1.3 on 2021-01-08 10:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0121_auto_20210107_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="architect_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="architect_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="architect_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="architect_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="developer_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="developer_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="developer_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="developer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="owner_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="architect_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="developer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="owner_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True
            ),
        ),
    ]
