# Generated by Django 3.1.3 on 2021-01-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0122_auto_20210108_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="entity_responsible_for_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_responsible_for_payment",
                to="customer_hirl.hirlresponsiblename",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="entity_responsible_for_payment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="customer_hirl.hirlresponsiblename",
            ),
        ),
    ]
