# Generated by Django 3.1.3 on 2021-01-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0123_auto_20210111_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="hud_disaster_case_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="hud_disaster_case_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="multi_family_project_website_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="sales_website_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="multi_family_project_website_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="sales_website_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
