# Generated by Django 3.1.3 on 2021-02-04 15:24

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0125_auto_20210115_1623"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="non_residential_space_to_be_included_in_certification",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="non_residential_space_to_be_included_in_certification",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="multi_family_project_client",
            field=models.CharField(
                blank=True,
                choices=[
                    ("builder", "Builder/General Contractor"),
                    ("developer", "Developer"),
                    ("owner", "Owner"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="multi_family_project_client",
            field=models.CharField(
                blank=True,
                choices=[
                    ("builder", "Builder/General Contractor"),
                    ("developer", "Developer"),
                    ("owner", "Owner"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
