# Generated by Django 3.1.6 on 2021-02-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0126_auto_20210204_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="hud_disaster_case_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="HUD Disaster Case Number"
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="is_include_commercial_space",
            field=models.BooleanField(default=False, verbose_name="Is Include Commercial Space"),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="hud_disaster_case_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="HUD Disaster Case Number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="is_include_commercial_space",
            field=models.BooleanField(default=False, verbose_name="Is Include Commercial Space"),
        ),
    ]
