# Generated by Django 3.1.6 on 2021-02-12 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0127_auto_20210208_1926"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hirlgreenenergybadge",
            options={
                "ordering": ("name",),
                "verbose_name": "NGBS Green+ Badge",
                "verbose_name_plural": "NGBS Green+ Badges",
            },
        ),
    ]
