# Generated by Django 3.1.6 on 2021-02-12 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0128_auto_20210212_1710"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirlproject",
            old_name="verifier",
            new_name="registration_user",
        ),
        migrations.RenameField(
            model_name="historicalhirlproject",
            old_name="verifier",
            new_name="registration_user",
        ),
    ]
