# Generated by Django 3.1.6 on 2021-03-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0131_auto_20210224_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlgreenenergybadge",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
