# Generated by Django 3.1.6 on 2021-03-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0132_hirlgreenenergybadge_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="h_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="h_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
