# Generated by Django 3.1.6 on 2021-03-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0133_auto_20210315_1207"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlrateruser",
            name="assigned_verifier_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
