# Generated by Django 3.1.6 on 2021-03-29 20:08

import axis.customer_hirl.models.project
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0135_auto_20210318_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlgreenenergybadge",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="ATTENTION: This is a base value that affects on ALL badges fees based on Project. Fees calculation performs in method `calculate_cost()`",
                max_digits=9,
                verbose_name="Cost",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="h_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="h_number",
            field=models.IntegerField(default=0),
        ),
    ]
