# Generated by Django 3.1.6 on 2021-03-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_auto_20210224_1038"),
        ("customer_hirl", "0136_auto_20210329_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="home_status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_hirl_project",
                to="home.eepprogramhomestatus",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="home_status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="home.eepprogramhomestatus",
            ),
        ),
    ]
