# Generated by Django 3.1.6 on 2021-03-23 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0137_auto_20210323_1303"),
        ("customer_hirl", "0135_auto_20210318_1746"),
    ]

    operations = []
