# Generated by Django 3.1.6 on 2021-03-31 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0138_merge_20210323_1625"),
        ("customer_hirl", "0136_auto_20210329_2008"),
    ]

    operations = []
