# Generated by Django 3.1.6 on 2021-03-31 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0138_auto_20210331_1006"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="home",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="home",
        ),
    ]
