# Generated by Django 3.1.6 on 2021-04-01 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0139_merge_20210331_1041"),
        ("customer_hirl", "0139_auto_20210331_1115"),
    ]

    operations = []
