# Generated by Django 3.1.6 on 2021-04-09 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_hirl", "0142_auto_20210406_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="h_number",
            field=models.IntegerField(
                default=0, help_text="Special Unique Key for HI", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="h_number",
            field=models.IntegerField(
                db_index=True, default=0, help_text="Special Unique Key for HI"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalHIRLGreenEnergyBadge",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="ATTENTION: This is a base value that affects on ALL badges fees based on Project. Fees calculation performs in method `calculate_cost()`",
                        max_digits=9,
                        verbose_name="Cost",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical NGBS Green+ Badge",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
