# Generated by Django 3.1.8 on 2021-04-14 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0145_auto_20210414_2133"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_hirl.hirlprojectregistration",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="registration",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="customer_hirl.hirlprojectregistration",
            ),
        ),
    ]
