# Generated by Django 3.1.8 on 2021-04-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0146_auto_20210414_2155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="customer_hirl.hirlprojectregistration",
            ),
        ),
    ]
