# Generated by Django 3.1.8 on 2021-04-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eep_program", "0022_merge_20210401_1458"),
        ("customer_hirl", "0147_auto_20210415_1133"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="eep_program",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="eep_program",
        ),
        migrations.AddField(
            model_name="hirlprojectregistration",
            name="eep_program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eep_program.eepprogram",
                verbose_name="Program",
            ),
        ),
    ]
