# Generated by Django 3.1.8 on 2021-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0149_auto_20210416_1038"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="is_associated_with_accessory_structure_seeking_certification",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="is_associated_with_accessory_structure_seeking_certification",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="is_accessory_structure",
            field=models.BooleanField(
                default=False,
                verbose_name="Is this property associated with an Accessory Structure Seeking Certification?",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_accessory_structure",
            field=models.BooleanField(
                default=False,
                verbose_name="Is this property associated with an Accessory Structure Seeking Certification?",
            ),
        ),
    ]
