# Generated by Django 3.1.8 on 2021-04-19 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0149_auto_20210416_1038"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlrateruser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="hirlrateruser",
            name="state",
        ),
        migrations.RemoveField(
            model_name="hirlrateruser",
            name="state_abbr",
        ),
        migrations.RemoveField(
            model_name="hirlrateruser",
            name="street_line1",
        ),
        migrations.RemoveField(
            model_name="hirlrateruser",
            name="street_line2",
        ),
        migrations.RemoveField(
            model_name="hirlrateruser",
            name="zipcode",
        ),
    ]
