# Generated by Django 3.1.8 on 2021-04-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subdivision", "0006_auto_20200128_1940"),
        ("customer_hirl", "0150_auto_20210420_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlprojectregistration",
            name="subdivision",
            field=models.OneToOneField(
                blank=True,
                help_text="After Approval: Subdivision automatically created for each Multi Family registration",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subdivision.subdivision",
                verbose_name="Subdivision",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlprojectregistration",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="After Approval: Subdivision automatically created for each Multi Family registration",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="subdivision.subdivision",
                verbose_name="Subdivision",
            ),
        ),
    ]
