# Generated by Django 3.1.8 on 2021-04-27 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0150_auto_20210419_1442"),
        ("customer_hirl", "0151_auto_20210422_1413"),
    ]

    operations = []
