# Generated by Django 3.1.8 on 2021-04-27 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0152_auto_20210427_1417"),
        ("customer_hirl", "0152_merge_20210427_0510"),
    ]

    operations = []
