# Generated by Django 3.1.8 on 2021-04-28 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0154_auto_20210428_0817"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirlprojectregistration",
            old_name="multi_family_project_estimated_completion_date",
            new_name="estimated_completion_date",
        ),
        migrations.RenameField(
            model_name="hirlprojectregistration",
            old_name="multi_family_project_client",
            new_name="project_client",
        ),
        migrations.RenameField(
            model_name="hirlprojectregistration",
            old_name="multi_family_project_description",
            new_name="project_description",
        ),
        migrations.RenameField(
            model_name="hirlprojectregistration",
            old_name="multi_family_project_website_url",
            new_name="project_website_url",
        ),
        migrations.RenameField(
            model_name="historicalhirlprojectregistration",
            old_name="multi_family_project_estimated_completion_date",
            new_name="estimated_completion_date",
        ),
        migrations.RenameField(
            model_name="historicalhirlprojectregistration",
            old_name="multi_family_project_client",
            new_name="project_client",
        ),
        migrations.RenameField(
            model_name="historicalhirlprojectregistration",
            old_name="multi_family_project_description",
            new_name="project_description",
        ),
        migrations.RenameField(
            model_name="historicalhirlprojectregistration",
            old_name="multi_family_project_website_url",
            new_name="project_website_url",
        ),
    ]
