# Generated by Django 3.1.8 on 2021-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0157_auto_20210507_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="hud_disaster_case_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="HUD Disaster Case Number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="hud_disaster_case_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="HUD Disaster Case Number"
            ),
        ),
    ]
