# Generated by Django 3.1.8 on 2021-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0158_auto_20210510_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="sampling",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_sampling", "No Sampling"),
                    ("testing_and_practices_only", "For Energy efficiency testing practices only"),
                    ("all", "For All or most NGBS practices"),
                ],
                max_length=30,
                null=True,
                verbose_name="Do you intend to employ the NGBS Green Alternative Multifamily Verification Protocol (Sampling) ?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="sampling",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_sampling", "No Sampling"),
                    ("testing_and_practices_only", "For Energy efficiency testing practices only"),
                    ("all", "For All or most NGBS practices"),
                ],
                max_length=30,
                null=True,
                verbose_name="Do you intend to employ the NGBS Green Alternative Multifamily Verification Protocol (Sampling) ?",
            ),
        ),
    ]
