# Generated by Django 3.1.8 on 2021-05-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_auto_20210512_1743"),
        ("customer_hirl", "0159_auto_20210511_1142"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlprojectregistration",
            name="builder_organization_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.contactcard",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlprojectregistration",
            name="builder_organization_contact",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.contactcard",
            ),
        ),
    ]
