# Generated by Django 3.1.8 on 2021-05-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0161_auto_20210514_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="commercial_space_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commercial_spaces",
                to="customer_hirl.hirlproject",
                verbose_name="Commercial Space project attached",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="commercial_space_parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="customer_hirl.hirlproject",
                verbose_name="Commercial Space project attached",
            ),
        ),
    ]
