# Generated by Django 3.1.8 on 2021-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0162_auto_20210519_1556"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlprojectregistration",
            name="ngbs_registration_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Legacy NGBS Registration ID determines that project been synced automatically via NGBS API",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlprojectregistration",
            name="ngbs_registration_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Legacy NGBS Registration ID determines that project been synced automatically via NGBS API",
                null=True,
            ),
        ),
    ]
