# Generated by Django 3.1.8 on 2021-05-26 20:59

import axis.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0163_auto_20210526_1629"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLLegacyRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hirl_id", models.PositiveIntegerField(blank=True, verbose_name="Internal ID")),
                (
                    "issued_project_id",
                    models.PositiveIntegerField(blank=True, verbose_name="Issued Project ID"),
                ),
                ("scoring_path_name", models.TextField(blank=True)),
                ("is_accessory_structure", models.BooleanField(default=False)),
                ("is_commercial_space", models.BooleanField(default=False)),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer_hirl.hirlprojectregistration",
                    ),
                ),
            ],
        ),
    ]
