# Generated by Django 3.1.8 on 2021-05-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0164_hirllegacyregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirllegacyregistration",
            name="issued_project_id",
            field=models.TextField(blank=True, verbose_name="Issued Project ID"),
        ),
    ]
