# Generated by Django 3.1.8 on 2021-05-26 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0165_auto_20210526_2104"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlprojectregistration",
            name="ngbs_registration_id",
        ),
        migrations.RemoveField(
            model_name="historicalhirlprojectregistration",
            name="ngbs_registration_id",
        ),
    ]
