# Generated by Django 3.1.8 on 2021-05-28 18:02

import axis.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0167_hirllegacyregistration_convert_to_registration_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLLegacyCertification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hirl_id", models.PositiveIntegerField(blank=True, verbose_name="Internal ID")),
                ("project_id", models.TextField(blank=True, verbose_name="Project ID")),
                ("scoring_path_name", models.TextField(blank=True)),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
