# Generated by Django 3.1.8 on 2021-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0168_hirllegacycertification"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="legacy_certification_id",
            field=models.TextField(
                blank=True,
                help_text="Identify that this Project has been created from Legacy HI Project",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="legacy_certification_id",
            field=models.TextField(
                blank=True,
                help_text="Identify that this Project has been created from Legacy HI Project",
            ),
        ),
    ]
