# Generated by Django 3.1.8 on 2021-05-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0169_auto_20210528_1833"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirllegacycertification",
            name="project_id",
        ),
        migrations.AddField(
            model_name="hirllegacycertification",
            name="convert_to_registration_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hirllegacycertification",
            name="hirl_project_id",
            field=models.TextField(
                blank=True, help_text="Legacy Project ID", verbose_name="Project ID"
            ),
        ),
        migrations.AddField(
            model_name="hirllegacycertification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer_hirl.hirlproject",
            ),
        ),
    ]
