# Generated by Django 3.1.8 on 2021-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0170_auto_20210528_1850"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="manual_billing_state",
            field=models.CharField(
                choices=[
                    ("complimentary", "complimentary"),
                    ("not_pursuing", "not_pursuing"),
                    ("test", "test"),
                ],
                default="",
                help_text="Manual override Billing State",
                max_length=30,
                verbose_name="Billing State Override",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="manual_billing_state",
            field=models.CharField(
                choices=[
                    ("complimentary", "complimentary"),
                    ("not_pursuing", "not_pursuing"),
                    ("test", "test"),
                ],
                default="",
                help_text="Manual override Billing State",
                max_length=30,
                verbose_name="Billing State Override",
            ),
        ),
    ]
