# Generated by Django 3.1.9 on 2021-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0172_auto_20210607_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlverifiercommunityproject",
            name="hirl_architect_contact_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlverifiercommunityproject",
            name="hirl_architect_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlverifiercommunityproject",
            name="hirl_community_owner_contact_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlverifiercommunityproject",
            name="hirl_community_owner_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlverifiercommunityproject",
            name="hirl_developer_contact_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlverifiercommunityproject",
            name="hirl_developer_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
