# Generated by Django 3.1.9 on 2021-06-07 20:33

import axis.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0173_auto_20210607_1450"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLVerifierCertificationBadgesToRecords",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hirl_id", models.PositiveIntegerField(verbose_name="Internal ID")),
                ("record_id", models.PositiveIntegerField(blank=True, null=True)),
                ("sources_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "verifier_certification_badges_pricing_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                ("story_count", models.IntegerField(blank=True, null=True)),
                ("data", axis.core.fields.AxisJSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
