# Generated by Django 3.2.4 on 2021-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0175_auto_20210627_0857"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="legacy_certification_id",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="legacy_certification_id",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="is_require_rough_inspection",
            field=models.BooleanField(
                default=True,
                help_text="Rough inspections are typically not required if there will be no renovation behind drywall. ",
                verbose_name="Will this remodel project require a rough inspection?",
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="is_require_water_sense_certification",
            field=models.BooleanField(
                default=False, verbose_name="Is the project seeking WaterSense Certification?"
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_require_rough_inspection",
            field=models.BooleanField(
                default=True,
                help_text="Rough inspections are typically not required if there will be no renovation behind drywall. ",
                verbose_name="Will this remodel project require a rough inspection?",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_require_water_sense_certification",
            field=models.BooleanField(
                default=False, verbose_name="Is the project seeking WaterSense Certification?"
            ),
        ),
    ]
