# Generated by Django 3.2.4 on 2021-07-07 19:09

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0176_auto_20210702_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="BLD",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="REG",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
