# Generated by Django 3.2.4 on 2021-07-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0177_auto_20210707_1909"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirluserprofile",
            name="is_qa_designee",
            field=models.BooleanField(default=False, verbose_name="QA Designee"),
        ),
    ]
