# Generated by Django 3.2.4 on 2021-07-19 13:18

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0178_hirluserprofile_is_qa_designee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlbuilderorganization",
            name="builder_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.builderorganization",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="PRJ",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
