# Generated by Django 3.2.4 on 2021-07-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0179_auto_20210719_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlbuilderorganization",
            name="builder_organization",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.builderorganization",
            ),
        ),
    ]
