# Generated by Django 3.2.6 on 2021-08-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0180_alter_hirlbuilderorganization_builder_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="builderagreement",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Builder Agreement",
                "verbose_name_plural": "Builder Agreements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbuilderagreement",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Builder Agreement",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalverifieragreement",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Verifier Agreement",
            },
        ),
        migrations.AlterModelOptions(
            name="verifieragreement",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Verifier Agreement",
                "verbose_name_plural": "Verifier Agreements",
            },
        ),
        migrations.AddField(
            model_name="hirlgreenenergybadge",
            name="description",
            field=models.TextField(
                blank=True, help_text="Using in Scoring Path Certificate generation"
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlgreenenergybadge",
            name="description",
            field=models.TextField(
                blank=True, help_text="Using in Scoring Path Certificate generation"
            ),
        ),
    ]
