# Generated by Django 3.2.7 on 2021-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0181_auto_20210820_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="certification_counter",
            field=models.IntegerField(
                default=0,
                help_text="Increased automatically when NGBS Project have been certified",
                verbose_name="Certification Counter",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="certification_counter",
            field=models.IntegerField(
                default=0,
                help_text="Increased automatically when NGBS Project have been certified",
                verbose_name="Certification Counter",
            ),
        ),
    ]
