# Generated by Django 3.2.7 on 2021-09-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0182_auto_20210907_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="most_recent_notice_sent",
            field=models.DateTimeField(
                help_text="Most recent Fee notification sent to Company Responsible For Payment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="most_recent_notice_sent",
            field=models.DateTimeField(
                help_text="Most recent Fee notification sent to Company Responsible For Payment",
                null=True,
            ),
        ),
    ]
