# Generated by Django 3.2.7 on 2021-09-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0184_auto_20210921_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="manual_billing_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Automatically"),
                    ("new", "New"),
                    ("new_queued", "New - Queued"),
                    ("new_notified", "New - Notified"),
                    ("notice_sent", "Notice Sent"),
                    ("completed", "Completed"),
                    ("complimentary", "Сomplimentary"),
                    ("not_pursuing", "Not pursuing"),
                    ("test", "Test"),
                    ("void", "Void"),
                    ("4300", "4300"),
                ],
                default="",
                help_text="Manual override Billing State",
                max_length=30,
                verbose_name="Billing State Override",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="most_recent_notice_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent Fee notification sent to Company Responsible For Payment",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="manual_billing_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Automatically"),
                    ("new", "New"),
                    ("new_queued", "New - Queued"),
                    ("new_notified", "New - Notified"),
                    ("notice_sent", "Notice Sent"),
                    ("completed", "Completed"),
                    ("complimentary", "Сomplimentary"),
                    ("not_pursuing", "Not pursuing"),
                    ("test", "Test"),
                    ("void", "Void"),
                    ("4300", "4300"),
                ],
                default="",
                help_text="Manual override Billing State",
                max_length=30,
                verbose_name="Billing State Override",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="most_recent_notice_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent Fee notification sent to Company Responsible For Payment",
                null=True,
            ),
        ),
    ]
