# Generated by Django 3.2.7 on 2021-10-14 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0185_auto_20210923_2112"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="builderagreement",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Client Agreement",
                "verbose_name_plural": "Client Agreements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbuilderagreement",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Client Agreement",
            },
        ),
    ]
