# Generated by Django 3.2.7 on 2021-10-27 09:23

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0187_auto_20211020_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="builderagreement",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="user_email",
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="signer_email",
            field=models.EmailField(
                help_text="Using for dircet DocuSign workflow without AXIS User",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="signer_name",
            field=models.CharField(
                help_text="Using for direct DocuSign workflow without AXIS User",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="signer_email",
            field=models.EmailField(
                help_text="Using for dircet DocuSign workflow without AXIS User",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="signer_name",
            field=models.CharField(
                help_text="Using for direct DocuSign workflow without AXIS User",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="coidocument",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coi_documents",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Submitted"),
                    ("approved", "Approved"),
                    ("verified", "Routed for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
