# Generated by Django 3.2.7 on 2021-11-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0188_auto_20211027_0923"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="vr_batch_submission_parent_final",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vr_batch_submission_final_childrens",
                to="customer_hirl.hirlproject",
                verbose_name="Final Parent project",
            ),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="vr_batch_submission_parent_rough",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vr_batch_submission_rough_childrens",
                to="customer_hirl.hirlproject",
                verbose_name="Rough Parent project",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="vr_batch_submission_parent_final",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="customer_hirl.hirlproject",
                verbose_name="Final Parent project",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="vr_batch_submission_parent_rough",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="customer_hirl.hirlproject",
                verbose_name="Rough Parent project",
            ),
        ),
    ]
