# Generated by Django 3.2.9 on 2021-11-17 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0189_auto_20211101_1517"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirluserprofile",
            name="is_master_verifier",
        ),
        migrations.RemoveField(
            model_name="hirluserprofile",
            name="is_wri_verifier",
        ),
    ]
