# Generated by Django 3.2.9 on 2021-11-17 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0190_auto_20211117_0911"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="builderagreement",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="builderagreement",
            name="insurance_expiration_date",
        ),
        migrations.RemoveField(
            model_name="builderagreement",
            name="insurance_policy_number",
        ),
        migrations.RemoveField(
            model_name="builderagreement",
            name="insurance_start_date",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="insurance_expiration_date",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="insurance_policy_number",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="insurance_start_date",
        ),
    ]
