# Generated by Django 3.2.9 on 2021-12-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0191_auto_20211117_0936"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="billing_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Automatically"),
                    ("new", "New"),
                    ("new_queued", "New - Queued"),
                    ("new_notified", "New - Notified"),
                    ("notice_sent", "Notice Sent"),
                    ("completed", "Completed"),
                    ("complimentary", "Сomplimentary"),
                    ("not_pursuing", "Not pursuing"),
                    ("test", "Test"),
                    ("void", "Void"),
                    ("4300", "4300"),
                ],
                default="new",
                max_length=30,
                verbose_name="Billing State",
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="billing_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Automatically"),
                    ("new", "New"),
                    ("new_queued", "New - Queued"),
                    ("new_notified", "New - Notified"),
                    ("notice_sent", "Notice Sent"),
                    ("completed", "Completed"),
                    ("complimentary", "Сomplimentary"),
                    ("not_pursuing", "Not pursuing"),
                    ("test", "Test"),
                    ("void", "Void"),
                    ("4300", "4300"),
                ],
                default="new",
                max_length=30,
                verbose_name="Billing State",
            ),
        ),
    ]
