# Generated by Django 3.2.9 on 2021-11-18 23:27

import axis.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0191_auto_20211117_0936"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlbuilderorganization",
            name="id",
        ),
        migrations.AlterField(
            model_name="hirlbuilderorganization",
            name="data",
            field=axis.core.fields.AxisJSONField(
                blank=True, default=dict, encoder=axis.core.fields.AxisJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="hirlbuilderorganization",
            name="hirl_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
