# Generated by Django 3.2.9 on 2021-11-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0192_auto_20211118_2327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlbuilderorganization",
            name="hirl_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
