# Generated by Django 3.2.9 on 2021-12-08 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0192_auto_20211202_1816"),
        ("customer_hirl", "0195_alter_hirlrateruser_hirl_id"),
    ]

    operations = []
