# Generated by Django 3.2.9 on 2021-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0196_merge_20211208_0917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlbuilderorganization",
            name="hirl_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hirlbuilderorganization",
            name="hirl_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
