# Generated by Django 3.2.10 on 2022-01-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subdivision", "0007_auto_20210719_1327"),
        ("customer_hirl", "0197_auto_20211208_1134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="application_packet_completion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("architect", "Architect"),
                    ("builder", "Builder"),
                    ("community_owner", "Owner"),
                    ("developer", "Developer"),
                ],
                default="builder",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="party_named_on_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("architect", "Architect"),
                    ("builder", "Builder"),
                    ("community_owner", "Owner"),
                    ("developer", "Developer"),
                ],
                default="builder",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                help_text="After Approval: Subdivision automatically created for each Multi Family registration",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subdivision.subdivision",
                verbose_name="Subdivision",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="application_packet_completion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("architect", "Architect"),
                    ("builder", "Builder"),
                    ("community_owner", "Owner"),
                    ("developer", "Developer"),
                ],
                default="builder",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="party_named_on_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("architect", "Architect"),
                    ("builder", "Builder"),
                    ("community_owner", "Owner"),
                    ("developer", "Developer"),
                ],
                default="builder",
                max_length=255,
                null=True,
            ),
        ),
    ]
