# Generated by Django 3.2.12 on 2022-03-23 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0199_auto_20220322_2030"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="providedservice",
            options={"ordering": ("-order",)},
        ),
    ]
