# Generated by Django 3.2.12 on 2022-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0200_alter_providedservice_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="sampling",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_sampling", "No Sampling"),
                    (
                        "testing_and_practices_only",
                        "For Energy efficiency testing practices only (both Rough and Final)",
                    ),
                    (
                        "rough_testing_and_practices_only",
                        "For Energy efficiency testing practices only (Rough only)",
                    ),
                    (
                        "final_testing_and_practices_only",
                        "For Energy efficiency testing practices only (Final only)",
                    ),
                    ("all", "For All or most NGBS practices (both Rough and Final)"),
                    ("rough_all", "For All or most NGBS practices (Rough only)"),
                    ("final_all", "For All or most NGBS practices (Final only)"),
                ],
                max_length=100,
                null=True,
                verbose_name="Do you intend to employ the NGBS Green Alternative Multifamily Verification Protocol (Sampling) ?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="sampling",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_sampling", "No Sampling"),
                    (
                        "testing_and_practices_only",
                        "For Energy efficiency testing practices only (both Rough and Final)",
                    ),
                    (
                        "rough_testing_and_practices_only",
                        "For Energy efficiency testing practices only (Rough only)",
                    ),
                    (
                        "final_testing_and_practices_only",
                        "For Energy efficiency testing practices only (Final only)",
                    ),
                    ("all", "For All or most NGBS practices (both Rough and Final)"),
                    ("rough_all", "For All or most NGBS practices (Rough only)"),
                    ("final_all", "For All or most NGBS practices (Final only)"),
                ],
                max_length=100,
                null=True,
                verbose_name="Do you intend to employ the NGBS Green Alternative Multifamily Verification Protocol (Sampling) ?",
            ),
        ),
    ]
