# Generated by Django 3.2.13 on 2022-05-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0023_auto_20210719_1332"),
        ("customer_hirl", "0201_auto_20220328_1844"),
    ]

    operations = [
        migrations.CreateModel(
            name="HIRLCompanyClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "HI Company Client",
                "verbose_name_plural": "HI Company Client",
            },
        ),
    ]
