# Generated by Django 3.2.12 on 2022-04-12 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0201_auto_20220324_1536"),
        ("customer_hirl", "0201_auto_20220328_1844"),
    ]

    operations = []
