# Generated by Django 3.2.13 on 2022-05-03 16:22

from django.db import migrations
from django.apps import apps

customer_hirl_app = apps.get_app_config("customer_hirl")


def forward(apps, schema_editor):
    """This will update all users"""
    Company = apps.get_model("company", "Company")
    HIRLCompanyClient = apps.get_model("customer_hirl", "HIRLCompanyClient")
    existing_hirl_builder_companies = (
        Company.objects.filter(
            company_type="builder", builderorganization__hirlbuilderorganization__isnull=False
        )
        .select_related("builderorganization__hirlbuilderorganization")
        .order_by("builderorganization__hirlbuilderorganization__hirl_id")
    )
    print("Delete all IDs")
    HIRLCompanyClient.objects.all().delete()

    for company in existing_hirl_builder_companies:
        print(
            f"Create existing {company.company_type}: HIRL ID "
            f"{company.builderorganization.hirlbuilderorganization.hirl_id}"
        )
        HIRLCompanyClient.objects.create(
            id=company.builderorganization.hirlbuilderorganization.hirl_id, company=company
        )

    other_companies = Company.objects.filter(
        company_type__in=["architect", "developer", "communityowner"]
    ).order_by("id")

    last_id = 0
    if existing_hirl_builder_companies.last():
        last_id = (
            existing_hirl_builder_companies.last().builderorganization.hirlbuilderorganization.hirl_id
        )
        migrations.RunSQL("ALTER TABLE customer_hirl_hirlcompanyclient AUTO_INCREMENT={last_id+1};")
    print(f"Other companies: {other_companies.count()}")
    for company in other_companies:
        last_id = last_id + 1
        c = HIRLCompanyClient.objects.create(id=last_id, company=company)
        print(f"Create {company.company_type}: HIRL ID {c.id}")


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0202_hirlcompanyclient"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
