# Generated by Django 3.2.13 on 2022-05-27 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0202_merge_0201_auto_20220324_1536_0201_auto_20220328_1844"),
        ("customer_hirl", "0203_auto_20220503_1622"),
    ]

    operations = []
