# Generated by Django 3.2.13 on 2022-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0204_merge_20220527_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="is_require_wri_certification",
            field=models.BooleanField(default=False, verbose_name="Is this project seeking a WRI?"),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_require_wri_certification",
            field=models.BooleanField(default=False, verbose_name="Is this project seeking a WRI?"),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="wri_certification_counter",
            field=models.IntegerField(
                default=0,
                help_text="Increased automatically when NGBS WRI Project have been certified",
                verbose_name="WRI Certification Counter",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="wri_certification_counter",
            field=models.IntegerField(
                default=0,
                help_text="Increased automatically when NGBS WRI Project have been certified",
                verbose_name="WRI Certification Counter",
            ),
        ),
    ]
