# Generated by Django 4.0.6 on 2022-07-22 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_hirl", "0205_auto_20220527_1138"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalbuilderagreement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Client Agreement",
                "verbose_name_plural": "historical Client Agreements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcertification",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical certification",
                "verbose_name_plural": "historical certifications",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcoidocument",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical COI Document",
                "verbose_name_plural": "historical COI Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhirlgreenenergybadge",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical NGBS Green+ Badge",
                "verbose_name_plural": "historical NGBS Green+ Badges",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhirlproject",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Project",
                "verbose_name_plural": "historical Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhirlprojectregistration",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Project Registration",
                "verbose_name_plural": "historical Project Registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalverifieragreement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Verifier Agreement",
                "verbose_name_plural": "historical Verifier Agreements",
            },
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="company",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_enrolled_agreements",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="owner",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_managed_agreements",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="hirlproject",
            name="home_status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_project",
                to="home.eepprogramhomestatus",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="architect_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_project_registrations_as_architect",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="architect_organization_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_project_registration_architects",
                to="core.contactcard",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="builder_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_project_registrations_as_builder",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="builder_organization_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_project_registration_builders",
                to="core.contactcard",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="community_owner_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_project_registrations_as_communityowner",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="community_owner_organization_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_project_registration_communityowners",
                to="core.contactcard",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="developer_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_project_registrations_as_developer",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="developer_organization_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_project_registration_developers",
                to="core.contactcard",
            ),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="registration_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_project_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcertification",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcoidocument",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlgreenenergybadge",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="architect_organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="builder_organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="community_owner_organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="developer_organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalverifieragreement",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="owner",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_managed_verifier_agreements",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="verifieragreement",
            name="verifier",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_enrolled_verifier_agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
