# Generated by Django 4.0.6 on 2022-08-18 10:45

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0207_alter_hirlbuilderorganization_builder_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="is_build_to_rent",
            field=models.BooleanField(default=False, verbose_name="Is this project Build-To-Rent?"),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_build_to_rent",
            field=models.BooleanField(default=False, verbose_name="Is this project Build-To-Rent?"),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("abandoned", "Abandoned"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("abandoned", "Abandoned"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
