# Generated by Django 4.0.6 on 2022-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0208_hirlproject_is_build_to_rent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="is_build_to_rent",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="is_build_to_rent",
        ),
        migrations.AddField(
            model_name="hirlprojectregistration",
            name="is_build_to_rent",
            field=models.BooleanField(default=False, verbose_name="Is this project Build-To-Rent?"),
        ),
        migrations.AddField(
            model_name="historicalhirlprojectregistration",
            name="is_build_to_rent",
            field=models.BooleanField(default=False, verbose_name="Is this project Build-To-Rent?"),
        ),
    ]
