# Generated by Django 4.0.7 on 2022-09-14 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0024_alter_eepprogramhomestatus_home_and_more"),
        ("customer_hirl", "0210_builderagreement_initiator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="builderagreement",
            name="initiator",
            field=models.ForeignKey(
                blank=True,
                help_text="User from other company(mostly Verifier) who created this Client Agreement for Company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_initiated_client_agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="initiator",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User from other company(mostly Verifier) who created this Client Agreement for Company",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this Client Agreement for Company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_created_client_agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="home",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.home"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who created this Client Agreement for Company",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
