# Generated by Django 4.0.7 on 2022-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0212_alter_candidate_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlprojectregistration",
            name="is_appeals_project",
            field=models.BooleanField(default=False, verbose_name="Is this an appeals project?"),
        ),
        migrations.AddField(
            model_name="historicalhirlprojectregistration",
            name="is_appeals_project",
            field=models.BooleanField(default=False, verbose_name="Is this an appeals project?"),
        ),
    ]
