# Generated by Django 4.0.8 on 2022-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0213_hirlprojectregistration_is_appeals_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="lot_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="lot_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
