# Generated by Django 4.0.7 on 2022-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0213_hirlprojectregistration_is_appeals_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="is_require_full_certification",
            field=models.BooleanField(default=False, null=True, verbose_name="Full Certification"),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="is_require_letter_of_approval",
            field=models.BooleanField(default=False, null=True, verbose_name="Letter Of Approval"),
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="number_of_lots",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_require_full_certification",
            field=models.BooleanField(default=False, null=True, verbose_name="Full Certification"),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_require_letter_of_approval",
            field=models.BooleanField(default=False, null=True, verbose_name="Letter Of Approval"),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="number_of_lots",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hirlprojectregistration",
            name="project_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Single Family"), (2, "Multi Family"), (3, "Multi Family")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlprojectregistration",
            name="project_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Single Family"), (2, "Multi Family"), (3, "Multi Family")], default=1
            ),
        ),
    ]
