# Generated by Django 4.0.7 on 2022-10-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0214_hirlproject_is_require_full_certification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="is_require_full_certification",
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="is_require_letter_of_approval",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="is_require_full_certification",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="is_require_letter_of_approval",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="ld_workflow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_certification", "Full Certification"),
                    (
                        "letter_of_approval_and_full_certification",
                        "Letter of Approval and Full Certification",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="ld_workflow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_certification", "Full Certification"),
                    (
                        "letter_of_approval_and_full_certification",
                        "Letter of Approval and Full Certification",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
