# Generated by Django 4.0.7 on 2022-10-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0217_hirlproject_ld_phase_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlproject",
            name="ld_phase_parent",
        ),
        migrations.RemoveField(
            model_name="hirlproject",
            name="ld_workflow",
        ),
        migrations.RemoveField(
            model_name="hirlprojectregistration",
            name="are_all_homes_in_ld_seeking_certification",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="ld_phase_parent",
        ),
        migrations.RemoveField(
            model_name="historicalhirlproject",
            name="ld_workflow",
        ),
        migrations.RemoveField(
            model_name="historicalhirlprojectregistration",
            name="are_all_homes_in_ld_seeking_certification",
        ),
        migrations.AddField(
            model_name="hirlproject",
            name="are_all_homes_in_ld_seeking_certification",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hirlprojectregistration",
            name="ld_workflow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_certification", "Full Certification"),
                    (
                        "letter_of_approval_and_full_certification",
                        "Letter of Approval and Full Certification",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="are_all_homes_in_ld_seeking_certification",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhirlprojectregistration",
            name="ld_workflow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_certification", "Full Certification"),
                    (
                        "letter_of_approval_and_full_certification",
                        "Letter of Approval and Full Certification",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
