# Generated by Django 4.0.8 on 2022-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0214_alter_hirlproject_lot_number_and_more"),
        ("customer_hirl", "0221_hirlproject_is_require_final_inspection_and_more"),
    ]

    operations = []
