# Generated by Django 4.0.8 on 2022-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0222_merge_20221115_2002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="land_development_phase_number",
            field=models.IntegerField(
                blank=True,
                help_text="Phase number for project. NULL is using for LOA projects",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="land_development_phase_number",
            field=models.IntegerField(
                blank=True,
                help_text="Phase number for project. NULL is using for LOA projects",
                null=True,
            ),
        ),
    ]
