# Generated by Django 4.0.8 on 2022-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0223_alter_hirlproject_land_development_phase_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="is_appeals_project",
            field=models.BooleanField(default=False, verbose_name="Is this an appeals project?"),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="is_appeals_project",
            field=models.BooleanField(default=False, verbose_name="Is this an appeals project?"),
        ),
    ]
