# Generated by Django 4.0.8 on 2022-12-13 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0224_hirlproject_is_appeals_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirlprojectregistration",
            name="is_appeals_project",
        ),
        migrations.RemoveField(
            model_name="historicalhirlprojectregistration",
            name="is_appeals_project",
        ),
    ]
