# Generated by Django 4.0.8 on 2022-12-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0225_remove_hirlprojectregistration_is_appeals_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirlproject",
            name="initial_invoice_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Set once when first non Appeals Invoice was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhirlproject",
            name="initial_invoice_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Set once when first non Appeals Invoice was created",
                null=True,
            ),
        ),
    ]
