# Generated by Django 4.0.8 on 2022-12-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0226_hirlproject_initial_invoice_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirlproject",
            name="lot_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhirlproject",
            name="lot_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
