# Generated by Django 4.1.7 on 2023-04-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0030_alter_company_city_alter_company_group_and_more"),
        ("customer_hirl", "0229_alter_builderagreement_agreement_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderagreement",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_enrolled_agreements",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_managed_agreements",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
            ),
        ),
    ]
