# Generated by Django 4.2 on 2023-04-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0230_alter_builderagreement_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coidocument",
            name="document",
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="historicalcoidocument",
            name="document",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
