# Generated by Django 4.2 on 2023-04-18 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0231_alter_coidocument_document_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coidocument",
            options={"ordering": ("-last_update",), "verbose_name": "COI Document"},
        ),
    ]
