# Generated by Django 4.2 on 2023-05-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0014_geocode_raw_country"),
        ("customer_hirl", "0232_alter_coidocument_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="builderagreement",
            name="mailing_geocode_response",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected by user in case of multiple valid results, automatically when we have one result and empty when geocode do not have valid results",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.geocoderesponse",
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="shipping_geocode_response",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected by user in case of multiple valid results, automatically when we have one result and empty when geocode do not have valid results",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.geocoderesponse",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="mailing_geocode_response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Selected by user in case of multiple valid results, automatically when we have one result and empty when geocode do not have valid results",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.geocoderesponse",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="shipping_geocode_response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Selected by user in case of multiple valid results, automatically when we have one result and empty when geocode do not have valid results",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.geocoderesponse",
            ),
        ),
    ]
