# Generated by Django 4.2 on 2023-05-17 15:35

import axis.core.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("filehandling", "0014_alter_customerdocument_document_and_more"),
        ("customer_hirl", "0233_builderagreement_mailing_geocode_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="builderagreement",
            name="extension_request_certifying_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.customerdocument",
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="extension_request_data",
            field=axis.core.fields.AxisJSONField(
                blank=True, default=dict, encoder=axis.core.fields.AxisJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="extension_request_signed_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filehandling.customerdocument",
            ),
        ),
        migrations.AddField(
            model_name="builderagreement",
            name="extension_request_state",
            field=django_fsm.FSMField(
                choices=[
                    ("not_sent", "Not sent"),
                    ("sent_to_client", "Sent to Client"),
                    ("sent_for_countersigned", "Sent for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                ],
                default="not_sent",
                help_text="State for extension request",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="extension_request_certifying_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.customerdocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="extension_request_data",
            field=axis.core.fields.AxisJSONField(
                blank=True, default=dict, encoder=axis.core.fields.AxisJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="extension_request_signed_agreement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filehandling.customerdocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderagreement",
            name="extension_request_state",
            field=django_fsm.FSMField(
                choices=[
                    ("not_sent", "Not sent"),
                    ("sent_to_client", "Sent to Client"),
                    ("sent_for_countersigned", "Sent for Counter-Signing"),
                    ("countersigned", "Counter-Signed"),
                ],
                default="not_sent",
                help_text="State for extension request",
                max_length=50,
            ),
        ),
    ]
