# Generated by Django 4.2.1 on 2023-05-23 14:01

import axis.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0235_builderagreement_extension_request_reject_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderagreement",
            name="data",
            field=axis.core.fields.AxisJSONField(
                blank=True, default=dict, encoder=axis.core.fields.AxisJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="builderagreement",
            name="extension_request_data",
            field=axis.core.fields.AxisJSONField(
                blank=True, default=dict, encoder=axis.core.fields.AxisJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="data",
            field=axis.core.fields.AxisJSONField(
                blank=True, default=dict, encoder=axis.core.fields.AxisJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderagreement",
            name="extension_request_data",
            field=axis.core.fields.AxisJSONField(
                blank=True, default=dict, encoder=axis.core.fields.AxisJSONEncoder, null=True
            ),
        ),
    ]
