# Generated by Django 4.2.1 on 2023-05-23 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_hirl", "0236_alter_builderagreement_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="data",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderagreement",
            name="extension_request_data",
        ),
    ]
