export const STORE_MULTIPLE_CHOICE_ANSWER = 'STORE_MULTIPLE_CHOICE_ANSWER';
export const REMOVE_MULTIPLE_CHOICE_ANSWER = 'REMOVE_MULTIPLE_CHOICE_ANSWER';
export const STORE_OPEN_ANSWER = 'STORE_OPEN_ANSWER';
export const REMOVE_OPEN_ANSWER = 'REMOVE_OPEN_ANSWER';
export const RECEIVE_ANSWERS = 'RECEIVE_ANSWERS';
export const RECEIVE_RELATED_ANSWERS = 'RECEIVE_RELATED_ANSWERS';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const STORE_DOCUMENT = 'STORE_DOCUMENT';
export const STORE_DOCUMENTS_SHELL = 'STORE_DOCUMENTS_SHELL';
export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT';
export const REMOVE_DOCUMENT_SHELL = 'REMOVE_DOCUMENT_SHELL';
export const ATTACH_DOCUMENT = 'ATTACH_DOCUMENT';
export const SAVING_ANSWER = 'SAVING_ANSWER';
export const ANSWER_SAVED = 'ANSWER_SAVED';

export const actions = {
    STORE_MULTIPLE_CHOICE_ANSWER,
    REMOVE_MULTIPLE_CHOICE_ANSWER,
    STORE_OPEN_ANSWER,
    REMOVE_OPEN_ANSWER,
    RECEIVE_ANSWERS,
    RECEIVE_RELATED_ANSWERS,
    DELETE_ANSWER,
    UPDATE_COMMENT,
    STORE_DOCUMENT,
    STORE_DOCUMENTS_SHELL,
    REMOVE_DOCUMENT,
    REMOVE_DOCUMENT_SHELL,
    ATTACH_DOCUMENT,
    SAVING_ANSWER,
    ANSWER_SAVED
};

export default actions;
