export const RECEIVE_EEP_PROGRAM = 'RECEIVE_EEP_PROGRAM';
export const RECEIVE_CHECKLIST = 'RECEIVE_CHECKLIST';
export const DISCARD_PROGRAM = 'DISCARD_PROGRAM';
export const DISCARD_CHECKLISTS = 'DISCARD_CHECKLISTS';
export const DISCARD_QUESTIONS = 'DISCARD_QUESTIONS';
export const CLEAR_ENTITIES = 'CLEAR_ENTITIES';

export const actions = {
    RECEIVE_EEP_PROGRAM,
    RECEIVE_CHECKLIST,
    DISCARD_PROGRAM,
    DISCARD_CHECKLISTS,
    DISCARD_QUESTIONS,
    CLEAR_ENTITIES
};

export default actions;
