export const SET_FILTER_STRING = 'SET_FILTER_STRING';
export const SET_TYPE_CHECKBOX = 'SET_TYPE_CHECKBOX';
export const SET_STATE_CHECKBOX = 'SET_STATE_CHECKBOX';
export const SET_SECTION_CHECKBOX = 'SET_SECTION_CHECKBOX';
export const SET_PROGRAM_CHECKBOX = 'SET_PROGRAM_CHECKBOX';
export const RESET_FILTERS = 'RESET_FILTERS';

export const actions = {
    SET_FILTER_STRING,
    SET_TYPE_CHECKBOX,
    SET_STATE_CHECKBOX,
    SET_SECTION_CHECKBOX,
    SET_PROGRAM_CHECKBOX,
    RESET_FILTERS
};

export default actions;
