export const SET_INTERACTION_SETTING = 'SET_INTERACTION_SETTING';
export const SET_SHOW_INTERACTION_SETTINGS = 'SET_SHOW_INTERACTION_SETTINGS';
export const SET_SHOW_FILTER_SETTINGS = 'SET_SHOW_FILTER_SETTINGS';
export const SET_SETTING = 'SET_SETTING';
export const CLIENT_ERROR = 'CLIENT_ERROR';
export const SERVER_ERROR = 'SERVER_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';


export const actions = {
    SET_INTERACTION_SETTING,
    SET_SHOW_INTERACTION_SETTINGS,
    SET_SHOW_FILTER_SETTINGS,
    SET_SETTING,
    CLIENT_ERROR,
    SERVER_ERROR,
    REMOVE_ERROR
};

export default actions;
