export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const SELECT_QUESTION = 'SELECT_QUESTION';
export const SET_FILTER_STRING = 'SET_FILTER_STRING';
export const SET_FILTER_CHECKBOX = 'SET_FILTER_CHECKBOX';

export const actions = {
    REQUEST_QUESTIONS,
    RECEIVE_QUESTIONS,
    SELECT_QUESTION,
    SET_FILTER_STRING,
    SET_FILTER_CHECKBOX
}
export default actions;
