# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geographic", "0001_initial"),
        ("home", "0001_initial"),
        ("customer_aps", "0002_auto_20181008_1815"),
        ("geocoder", "0002_auto_20181008_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalapshome",
            name="home",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="home.Home",
            ),
        ),
        migrations.AddField(
            model_name="historicalapshome",
            name="metro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.Metro",
            ),
        ),
        migrations.AddField(
            model_name="historicalapshome",
            name="place",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.Place",
            ),
        ),
        migrations.AddField(
            model_name="apshome",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text='Type the first few letters of the name of the city the home is located in and select the correct city/state/county combination from the list presented. If the correct city is not available, click "Add New" to add a city to the database.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geographic.City",
                verbose_name="City/State",
            ),
        ),
        migrations.AddField(
            model_name="apshome",
            name="climate_zone",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geographic.ClimateZone",
            ),
        ),
        migrations.AddField(
            model_name="apshome",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geographic.County",
                verbose_name="County",
            ),
        ),
        migrations.AddField(
            model_name="apshome",
            name="geocode_response",
            field=models.ForeignKey(
                blank=True,
                help_text="The response this place was constructed from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geocoder.GeocodeResponse",
            ),
        ),
        migrations.AddField(
            model_name="apshome",
            name="home",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="home.Home"
            ),
        ),
        migrations.AddField(
            model_name="apshome",
            name="metro",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geographic.Metro",
                verbose_name="Metro",
            ),
        ),
        migrations.AddField(
            model_name="apshome",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apshome_set",
                to="geographic.Place",
            ),
        ),
    ]
