# Generated by Django 1.11.17 on 2019-07-23 20:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subdivision", "0003_auto_20190531_1224"),
        ("customer_aps", "0005_auto_20190826_2024"),
    ]

    operations = [
        migrations.CreateModel(
            name="APSSmartThermostatOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "eligibility",
                    models.CharField(
                        choices=[
                            ("ineligible", "Not Eligible"),
                            ("partial", "Eligible and partial participation"),
                            ("complete", "Eligible and 100% participation"),
                        ],
                        default="ineligible",
                        max_length=14,
                    ),
                ),
                (
                    "models",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ineligible", "Not Eligible"),
                            ("partial", "Eligible and " "partial " "participation"),
                            ("complete", "Eligible and 100% participation"),
                        ],
                        max_length=64,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile(r"^\\d+(?:\\,\\d+)*\\Z"),
                                code="invalid",
                                message="Enter only digits separated by commas.",
                            )
                        ],
                    ),
                ),
                (
                    "subdivision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aps_thermostat_option",
                        to="subdivision.Subdivision",
                    ),
                ),
            ],
            options={"verbose_name": "APS Smart Thermostat Option"},
        ),
        migrations.CreateModel(
            name="HistoricalAPSSmartThermostatOption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "eligibility",
                    models.CharField(
                        choices=[
                            ("ineligible", "Not Eligible"),
                            ("partial", "Eligible and partial participation"),
                            ("complete", "Eligible and 100% participation"),
                        ],
                        default="ineligible",
                        max_length=14,
                    ),
                ),
                (
                    "models",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ineligible", "Not Eligible"),
                            ("partial", "Eligible and partial participation"),
                            ("complete", "Eligible and 100% participation"),
                        ],
                        max_length=64,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile(r"^\\d+(?:\\,\\d+)*\\Z"),
                                code="invalid",
                                message="Enter only digits separated by commas.",
                            )
                        ],
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subdivision",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="subdivision.Subdivision",
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical APS Smart Thermostat Option",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
