# Generated by Django 1.11.26 on 2020-06-19 17:44

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_aps", "0008_auto_20200415_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apssmartthermostatoption",
            name="models",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ineligible", "Not Eligible"),
                    ("partial", "Eligible and partial participation"),
                    ("complete", "Eligible and 100% participation"),
                ],
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z", 32),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalapssmartthermostatoption",
            name="models",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ineligible", "Not Eligible"),
                    ("partial", "Eligible and partial participation"),
                    ("complete", "Eligible and 100% participation"),
                ],
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z", 32),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
    ]
