# Generated by Django 1.11.26 on 2020-06-26 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_aps", "0009_auto_20200624_1559"),
        ("customer_aps", "0009_auto_20200619_1744"),
    ]

    operations = []
