# Generated by Django 3.1.3 on 2020-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_aps", "0011_merge_20200701_0829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apshome",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapshome",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
    ]
