# Generated by Django 4.0.6 on 2022-07-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0005_auto_20211021_1932"),
        ("customer_aps", "0012_auto_20201230_1218"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalapshome",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical APS Exported Home",
                "verbose_name_plural": "historical APS Exported Homes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalapssmartthermostatoption",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical APS Smart Thermostat Option",
                "verbose_name_plural": "historical APS Smart Thermostat Options",
            },
        ),
        migrations.AlterField(
            model_name="apshome",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text='Type the first few letters of the name of the city the project is located in and select the correct city/state/county combination from the list presented. If the correct city is not available, click "Add New" to add a city to the database.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geographic.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="apshome",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="apshome",
            name="lot_number",
            field=models.CharField(
                blank=True,
                help_text='Enter the lot number of the project (typical for a "production builder" in a subdivision or development of multiple projects), or leave blank or "N/A" if unknown or not applicable.',
                max_length=16,
                null=True,
                verbose_name="Lot number",
            ),
        ),
        migrations.AlterField(
            model_name="apshome",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="geographic.place",
            ),
        ),
        migrations.AlterField(
            model_name="apshome",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="apshome",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of project.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="apssmartthermostatoption",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapshome",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Type the first few letters of the name of the city the project is located in and select the correct city/state/county combination from the list presented. If the correct city is not available, click "Add New" to add a city to the database.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapshome",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalapshome",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapshome",
            name="lot_number",
            field=models.CharField(
                blank=True,
                help_text='Enter the lot number of the project (typical for a "production builder" in a subdivision or development of multiple projects), or leave blank or "N/A" if unknown or not applicable.',
                max_length=16,
                null=True,
                verbose_name="Lot number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapshome",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapshome",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of project.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapssmartthermostatoption",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalapssmartthermostatoption",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="legacyapsbuilder",
            name="builder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
        migrations.AlterField(
            model_name="legacyapsbuilder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="legacyapshome",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="legacyapssubdivision",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
