# Generated by Django 1.11.16 on 2018-10-08 18:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models

import axis.company.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RESNETCompany",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("street_line1", models.CharField(blank=True, max_length=100, null=True)),
                ("street_line2", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "zipcode",
                    models.CharField(blank=True, max_length=15, null=True, verbose_name="ZIP Code"),
                ),
                (
                    "office_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=20, null=True
                    ),
                ),
                (
                    "office_fax",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=20, null=True
                    ),
                ),
                ("home_page", models.URLField(blank=True, null=True)),
                ("is_rater", models.BooleanField(default=False)),
                ("is_provider", models.BooleanField(default=False)),
                ("is_sampling_provider", models.BooleanField(default=False)),
                ("is_training_provider", models.BooleanField(default=False)),
                ("is_hesp_provider", models.BooleanField(default=False)),
                ("is_watersense_provider", models.BooleanField(default=False)),
                (
                    "certification_number",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        validators=[axis.company.validators.validate_provider_id],
                    ),
                ),
                ("resnet_expiration", models.DateField(blank=True, null=True)),
                ("resnet_profile_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(editable=False)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resnet",
                        to="company.Company",
                    ),
                ),
            ],
            options={"verbose_name": "RESNET Company", "verbose_name_plural": "RESNET Companies"},
        ),
        migrations.CreateModel(
            name="RESNETContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(editable=False)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "resnet_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resnet.RESNETCompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "RESNET Contact",
            },
        ),
    ]
