# Generated by Django 1.11.17 on 2019-07-05 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resnet", "0002_auto_20190531_1224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resnetcompany",
            name="is_hesp_provider",
        ),
    ]
