# Generated by Django 4.0.7 on 2022-09-14 17:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("resnet", "0003_remove_resnetcompany_is_hesp_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resnetcompany",
            name="office_fax",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="resnetcompany",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="resnetcontact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
