# Generated by Django 1.11.16 on 2018-10-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_json_data_update_20181008_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
