# Generated by Django 1.11.17 on 2019-08-22 20:27

from django.db import migrations, models


def forward(apps, schema_editor):
    """This will update all users"""
    User = apps.get_model("core", "User")
    User.objects.filter(is_active=True).update(is_approved=True)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_historicaluser_history_change_reason_foo"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has been approved to log in by a company administrator.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has been approved to log in by a company administrator.",
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
