# Generated by Django 1.11.26 on 2020-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_auto_20200415_1542"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaterRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Rater role name, eg. Energy Modeler", max_length=50
                    ),
                ),
                ("slug", models.SlugField()),
                ("is_hidden", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="rater_roles",
            field=models.ManyToManyField(blank=True, to="core.RaterRole"),
        ),
    ]
