# Generated by Django 1.11.26 on 2020-04-22 18:55

from django.db import migrations, transaction


@transaction.atomic
def migrate_rater_role_to_rater_roles(apps, schema_editor):
    print("Migrate rater_role to rater_roles")
    user_class = apps.get_model("core", "User")
    rater_role_class = apps.get_model("core", "RaterRole")

    rfi_role, _ = rater_role_class.objects.get_or_create(title="Rating Field Inspector", slug="rfi")
    rater_verifier_role, _ = rater_role_class.objects.get_or_create(
        title="Rater/Verifier", slug="rater_verifier"
    )
    qa_designee_role, _ = rater_role_class.objects.get_or_create(
        title="QA Designee", slug="qa_designee"
    )
    operations_role, _ = rater_role_class.objects.get_or_create(
        title="Operations", slug="operations"
    )

    roles_map = {
        "1": rfi_role,
        "2": rater_verifier_role,
        "3": qa_designee_role,
        "4": rater_verifier_role,
        "5": operations_role,
    }

    for user in user_class.objects.filter(rater_role__isnull=False):
        role_obj = roles_map[user.rater_role]
        print(user, user.get_rater_role_display(), role_obj)
        user.rater_roles.add(role_obj)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_auto_20200422_1743"),
    ]

    operations = [
        migrations.RunPython(migrate_rater_role_to_rater_roles),
    ]
