# Generated by Django 1.11.26 on 2020-04-22 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_auto_20200422_1855"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="rater_role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="rater_role",
        ),
    ]
