# Generated by Django 1.11.26 on 2020-05-19 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20200518_1846"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="ngbs_verifier_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ngbs_verifier_id",
        ),
    ]
