# Generated by Django 1.11.26 on 2020-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auto_20200519_0812"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="show_beta",
            field=models.BooleanField(
                default=False, help_text="Switch between classic and new pages view"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_beta",
            field=models.BooleanField(
                default=False, help_text="Switch between classic and new pages view"
            ),
        ),
    ]
