# Generated by Django 1.11.26 on 2020-06-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0008_merge_20200427_1427"),
        ("core", "0015_auto_20200602_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="mailing_geocode",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="shipping_geocode",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mailing_geocode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_geocode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
    ]
