# Generated by Django 1.11.26 on 2020-06-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_auto_20200603_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mailing_geocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="shipping_geocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="geocoder.Geocode",
            ),
        ),
    ]
