# Generated by Django 2.2 on 2020-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_merge_20200811_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_master_verifier",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="is_wri_verifier",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_master_verifier",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_wri_verifier",
            field=models.BooleanField(default=False),
        ),
    ]
