# Generated by Django 2.2 on 2020-10-16 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_auto_20201016_1444"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="is_master_verifier",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="is_wri_verifier",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_master_verifier",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_wri_verifier",
        ),
    ]
