# Generated by Django 2.2 on 2020-11-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flatpages", "0001_initial"),
        ("core", "0027_auto_20201028_1733"),
    ]

    operations = [
        migrations.CreateModel(
            name="AxisFlatPage",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.FlatPage",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Additional priority for static pages"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This field is using for ordering FlatPages. For example: News list",
                    ),
                ),
            ],
            bases=("flatpages.flatpage",),
        ),
        migrations.AlterModelOptions(
            name="recentlyviewed",
            options={"ordering": ("-updated_at",), "verbose_name_plural": "Recently Viewed"},
        ),
    ]
