# Generated by Django 2.2 on 2020-11-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_auto_20201116_0953"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="axisflatpage",
            options={"verbose_name": "Static page"},
        ),
        migrations.AlterField(
            model_name="axisflatpage",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Additional priority for static pages"
            ),
        ),
    ]
