# Generated by Django 3.1.8 on 2021-05-11 19:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_auto_20210511_1901"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactcard",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contactcard",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contactcard",
            name="tag",
        ),
        migrations.AddField(
            model_name="contactcard",
            name="protected",
            field=models.BooleanField(
                default=False,
                help_text="This ContactCard created and will be updated automatically based on User or Company data",
            ),
        ),
        migrations.CreateModel(
            name="ContactCardPhone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region=None
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="core.contactcard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactCardEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("description", models.CharField(max_length=100)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="core.contactcard",
                    ),
                ),
            ],
        ),
    ]
