# Generated by Django 3.1.8 on 2021-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_auto_20210511_1913"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcardemail",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="contactcardphone",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
