# Generated by Django 3.2.6 on 2021-09-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("core", "0036_auto_20210519_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Site on what user registered. This domain will use for all links in notifications that do not have request object. Empty value means default SITE_ID domain",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Site on what user registered. This domain will use for all links in notifications that do not have request object. Empty value means default SITE_ID domain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sites.site",
            ),
        ),
    ]
