# Generated by Django 3.2.12 on 2022-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_auto_20210903_1905"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactcard",
            options={
                "ordering": ("first_name", "last_name"),
                "verbose_name": "Contact Card",
                "verbose_name_plural": "Contact Cards",
            },
        )
    ]
