# Generated by Django 4.1.5 on 2023-02-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0031_companyrole_companyaccess"),
        ("core", "0040_historicalaxisflatpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(through="company.CompanyAccess", to="company.company"),
        ),
    ]
