__author__ = "Steven Klass"
__date__ = "1/20/12 1:28 PM"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = [
    "Steven Klass",
]


SUB_MERGE_MAP = [
    #
    dict(
        name="70ELARASR",
        actual="Araby Crossing",
        community="",
        eep="",
        custom=False,
        original="Araby Crossing",
        original_c="",
    ),
    dict(
        name="70ELARRSR",
        actual="Arroyo De Fortuna",
        community="",
        eep="",
        custom=False,
        original="Arroyo De Fortuna",
        original_c="",
    ),
    dict(
        name="70LOVIZA",
        actual="Izabel Homes",
        community="",
        eep="",
        custom=False,
        original="Izabel Homes",
        original_c="",
    ),
    dict(
        name="70MONAPRSR",
        actual="Privada",
        community="",
        eep="",
        custom=False,
        original="Privada",
        original_c="",
    ),
    dict(
        name="BEAGLN70SRS",
        actual="Glenmont Estates",
        community="",
        eep="",
        custom=False,
        original="Glenmont Estates",
        original_c="",
    ),
    dict(
        name="BEASAN70SRS",
        actual="Sanctuary",
        community="Canyon Trails",
        eep="",
        custom=False,
        original="Sanctuary At Canyon Trails",
        original_c="",
    ),
    dict(
        name="BEATER70SRS",
        actual="Terraza",
        community="Villago",
        eep="",
        custom=False,
        original="Terraza At Villago",
        original_c="",
    ),
    dict(
        name="BEATRI70SRS",
        actual="Trianda Terrace",
        community="Canyon Trails",
        eep="",
        custom=False,
        original="Trianda Terrace",
        original_c="",
    ),
    dict(
        name="CENBRO1",
        actual="Oasis at Canyon Trails - Brookhaven",
        community="",
        eep="",
        custom=False,
        original="Oasis at Canyon Trails - Brookhaven",
        original_c="",
    ),
    dict(
        name="CNBGFR70",
        actual="Grey Fox Ridge",
        community="",
        eep="",
        custom=False,
        original="Grey Fox Ridge",
        original_c="",
    ),
    dict(
        name="COPCUS",
        actual="Custom Homes",
        community="",
        eep="",
        custom=False,
        original="Custom Homes",
        original_c="",
    ),
    dict(
        name="CORPER70SRS",
        actual="Cortessa Peralta",
        community="",
        eep="",
        custom=False,
        original="Cortessa Peralta",
        original_c="",
    ),
    dict(
        name="CORVE70SRS",
        actual="Cortessa Verona",
        community="",
        eep="",
        custom=False,
        original="Cortessa Verona",
        original_c="",
    ),
    dict(
        name="DMRMON70",
        actual="Fireside At Norterra Desert Ridge/4500s/DW/montage",
        community="",
        eep="",
        custom=False,
        original="Fireside At Norterra Desert Ridge/4500s/DW/montage",
        original_c="",
    ),
    dict(
        name="DMROVR70",
        actual="Fireside Norterra/dynamite Mountain Ranch/FC 3500",
        community="",
        eep="",
        custom=False,
        original="Fireside Norterra/dynamite Mountain Ranch/FC 3500",
        original_c="",
    ),
    dict(
        name="DMRPRI70",
        actual="Fireside @ Desert Ridge - 5500s/DW/primavera",
        community="",
        eep="",
        custom=False,
        original="Fireside @ Desert Ridge - 5500s/DW/primavera",
        original_c="",
    ),
    dict(
        name="DRHSONV",
        actual="Sonoran Vista",
        community="",
        eep="",
        custom=False,
        original="Sonoran Vista",
        original_c="",
    ),
    dict(
        name="DRHTUCR",
        actual="Tuscany Ranch",
        community="",
        eep="",
        custom=False,
        original="Tuscany Ranch",
        original_c="",
    ),
    dict(
        name="ELLEST",
        actual="Estrella Unit 3",
        community="",
        eep="",
        custom=False,
        original="Estrella Unit 3",
        original_c="",
    ),
    dict(
        name="ELLESTSR",
        actual="Estrella Unit 3",
        community="",
        eep="",
        custom=False,
        original="Estrella Unit #3 - Solar Ready",
        original_c="",
    ),
    dict(
        name="ELLESTSR70",
        actual="Estrella Unit 3",
        community="",
        eep="",
        custom=False,
        original="Estrella Unit # 3",
        original_c="",
    ),
    dict(
        name="ELLSEE70SR",
        actual="Scottsdale East Estates",
        community="",
        eep="",
        custom=False,
        original="Scottsdale East Estates",
        original_c="",
    ),
    dict(
        name="FLAG01",
        actual="Flagstaff division",
        community="",
        eep="",
        custom=True,
        original="Flagstaff division",
        original_c="",
    ),
    dict(
        name="FORCUS70",
        actual="Custom",
        community="",
        eep="",
        custom=True,
        original="Custom",
        original_c="",
    ),
    dict(
        name="HABCUS",
        actual="Prescott area",
        community="",
        eep="",
        custom=True,
        original="Prescott area",
        original_c="",
    ),
    dict(
        name="HABPHX",
        actual="Custom",
        community="",
        eep="",
        custom=True,
        original="Custom",
        original_c="",
    ),
    dict(
        name="HOMSYC1",
        actual="Sycamore Creek",
        community="",
        eep="",
        custom=False,
        original="Sycamore Creek",
        original_c="",
    ),
    dict(
        name="HOMSYCSR",
        actual="Sycamore Creek",
        community="",
        eep="",
        custom=False,
        original="Sycamore Creek",
        original_c="",
    ),
    dict(
        name="HOPCUS",
        actual="Custom",
        community="",
        eep="",
        custom=True,
        original="Custom",
        original_c="",
    ),
    dict(
        name="HUNCUS",
        actual="Custom",
        community="",
        eep="",
        custom=True,
        original="Custom",
        original_c="",
    ),
    dict(
        name="KBHMES70",
        actual="Mesquite Cove",
        community="",
        eep="",
        custom=False,
        original="Mesquite Cove",
        original_c="",
    ),
    dict(
        name="KEYIRO70",
        actual="Ironwood Village",
        community="",
        eep="",
        custom=False,
        original="Ironwood Village",
        original_c="",
    ),
    dict(
        name="LENASA70",
        actual="Asante",
        community="",
        eep="",
        custom=False,
        original="Asante",
        original_c="",
    ),
    dict(
        name="MARCRE",
        actual="Crescent Views",
        community="",
        eep="",
        custom=False,
        original="Crescent Views",
        original_c="",
    ),
    dict(
        name="MARCREsr70",
        actual="Crescent Views",
        community="",
        eep="",
        custom=False,
        original="Crescent Views",
        original_c="",
    ),
    dict(
        name="MATCAN70",
        actual="Mattamy Homes",
        community="",
        eep="",
        custom=False,
        original="Mattamy Homes At Canyon Trails",
        original_c="",
    ),
    dict(
        name="MCHGOS",
        actual="Ghost Hollow Estates",
        community="",
        eep="",
        custom=False,
        original="Ghost Hollow Estates",
        original_c="",
    ),
    dict(
        name="MERCIB70SR",
        actual="Cibola Vista",
        community="",
        eep="",
        custom=False,
        original="Cibola Vista",
        original_c="",
    ),
    dict(
        name="MERNIC",
        actual="Nicholas Point",
        community="",
        eep="",
        custom=False,
        original="Nicholas Point -50s",
        original_c="",
    ),
    dict(
        name="MERRIVSR",
        actual="Riverstone Estates",
        community="",
        eep="",
        custom=False,
        original="Riverstone Estates",
        original_c="",
    ),
    dict(
        name="MERSONSR",
        actual="Sonoran Foothills",
        community="",
        eep="",
        custom=False,
        original="Sonoran Foothills",
        original_c="",
    ),
    dict(
        name="MERVAL",
        actual="Valley Vista",
        community="",
        eep="",
        custom=False,
        original="Valley Vista (Meritage)",
        original_c="",
    ),
    dict(
        name="PDRETE70",
        actual="Fireside",
        community="Desert Ridge",
        eep="",
        custom=False,
        original="Fireside Desert Ridge/cluster/dw/eternal",
        original_c="",
    ),
    dict(
        name="PDRSPL70",
        actual="Fireside",
        community="Desert Ridge",
        eep="",
        custom=False,
        original="Fireside Desert Ridge/3500s/DW/Splendor",
        original_c="",
    ),
    dict(
        name="PERTER",
        actual="Terra Bella",
        community="",
        eep="",
        custom=False,
        original="Terra Bella",
        original_c="",
    ),
    dict(
        name="PULCAB",
        actual="Cabrillo Point",
        community="",
        eep="",
        custom=False,
        original="Cabrillo Point",
        original_c="",
    ),
    dict(
        name="PULCAB70",
        actual="Cabrillo Point",
        community="",
        eep="",
        custom=False,
        original="Cabrillo Point",
        original_c="",
    ),
    dict(
        name="PULFOO",
        actual="Vista de Montana",
        community="",
        eep="",
        custom=False,
        original="Vista de Montana - Foothills / 48'S",
        original_c="",
    ),
    dict(
        name="PULHOM70",
        actual="Homestead Series",
        community="",
        eep="",
        custom=False,
        original="Red Rock 2400s/Homestead Series",
        original_c="",
    ),
    dict(
        name="PULLGD70",
        actual="Legend Series",
        community="",
        eep="",
        custom=False,
        original="Red Rock - 4500s/Legend Series",
        original_c="",
    ),
    dict(
        name="PULLON70",
        actual="Lone Mountain",
        community="",
        eep="",
        custom=False,
        original="Lone Mountain",
        original_c="",
    ),
    dict(
        name="PULNOL1",
        actual="Northgate Ledgestone",
        community="",
        eep="",
        custom=False,
        original="Northgate Ledgestone",
        original_c="",
    ),
    dict(
        name="PULNOR70",
        actual="Northgate Ridgerock",
        community="",
        eep="",
        custom=False,
        original="Northgate - Ridgerock",
        original_c="",
    ),
    dict(
        name="PULPIN",
        actual="Vista De Montana",
        community="",
        eep="",
        custom=False,
        original="Vista De Montana - Pinnacles / 58'S",
        original_c="",
    ),
    dict(
        name="PULPIN70",
        actual="Vista De Montana",
        community="",
        eep="",
        custom=False,
        original="Vista De Montana - HERS 70 - Pinnacles & Foothills",
        original_c="",
    ),
    dict(
        name="PULTAR",
        actual="Tartesso",
        community="",
        eep="",
        custom=False,
        original="Tartesso",
        original_c="",
    ),
    dict(
        name="PULTDR70",
        actual="Tierra Del Rio",
        community="",
        eep="",
        custom=False,
        original="Tierra Del Rio",
        original_c="",
    ),
    dict(
        name="RESCON",
        actual="Custom homes",
        community="",
        eep="",
        custom=True,
        original="Custom homes",
        original_c="",
    ),
    dict(
        name="RICDAS70",
        actual="Davis",
        community="",
        eep="",
        custom=False,
        original="Davis At Savannah",
        original_c="",
    ),
    dict(
        name="RICTRA70",
        actual="Tramonto",
        community="",
        eep="",
        custom=False,
        original="Tramonto",
        original_c="",
    ),
    dict(
        name="ROBPEB",
        actual="Pebble Creek",
        community="",
        eep="",
        custom=False,
        original="PebbleCreek",
        original_c="PebbleCreek",
    ),
    dict(
        name="ROBPEB70",
        actual="Pebble Creek",
        community="",
        eep="",
        custom=False,
        original="Pebblecreek",
        original_c="Pebblecreek",
    ),
    dict(
        name="ROBPEB70SR",
        actual="Pebble Creek",
        community="",
        eep="",
        custom=False,
        original="Pebblecreek - 70SR",
        original_c="",
    ),
    dict(
        name="SEDEL70SR",
        actual="Sedella",
        community="",
        eep="",
        custom=False,
        original="Sedella",
        original_c="",
    ),
    dict(
        name="SHEVLP70",
        actual="Village At Litchfield Park",
        community="",
        eep="",
        custom=False,
        original="Village At Litchfield Park",
        original_c="",
    ),
    dict(
        name="STABHV70",
        actual="Blue Horizon Villages",
        community="",
        eep="",
        custom=False,
        original="Blue Horizon Villages",
        original_c="",
    ),
    dict(
        name="STACAT70",
        actual="Canyon Trails",
        community="",
        eep="",
        custom=False,
        original="Canyon Trails 4500/5000",
        original_c="",
    ),
    dict(
        name="STACOR70",
        actual="Cortessa",
        community="",
        eep="",
        custom=False,
        original="Cortessa",
        original_c="",
    ),
    dict(
        name="SUNRAN70SR",
        actual="Sunset Ranch",
        community="",
        eep="",
        custom=False,
        original="Sunset Ranch",
        original_c="",
    ),
    dict(
        name="SUNTERSR70",
        actual="Sunset Terrace",
        community="",
        eep="",
        custom=False,
        original="Sunset Terrace @ The View",
        original_c="",
    ),
    dict(
        name="TMDISEN70",
        actual="Las Brisas",
        community="",
        eep="",
        custom=False,
        original="Las Brisas - Discovery/encore",
        original_c="",
    ),
    dict(
        name="TMLEG70",
        actual="Sycamore Estates",
        community="",
        eep="",
        custom=False,
        original="Sycamore Estates - Legacy",
        original_c="",
    ),
    dict(
        name="TMSAVVG70",
        actual="Savannah - Voyage",
        community="",
        eep="",
        custom=False,
        original="Savannah - Voyage",
        original_c="",
    ),
    dict(
        name="TMVOY70",
        actual="Sycamore Estates",
        community="",
        eep="",
        custom=False,
        original="Sycamore Estates - Voyage",
        original_c="",
    ),
    dict(
        name="TREVER70SR",
        actual="Verrado",
        community="",
        eep="",
        custom=False,
        original="Verrado",
        original_c="",
    ),
    dict(
        name="VILCRW",
        actual="Village at Canyon Ridge West",
        community="",
        eep="",
        custom=False,
        original="Village at Canyon Ridge West",
        original_c="",
    ),
    # anthem
    dict(
        name="PULARG70",
        actual="Arroyo Grand",
        community="anthem",
        eep="",
        custom=False,
        original="Anthem Arroyo Grand/6500s/unit 81/dream",
        original_c="Anthem",
    ),
    dict(
        name="PULASP",
        actual="Aspire Series",
        community="anthem",
        eep="",
        custom=False,
        original="Anthem - Aspire Series (unit 81 - 5500 series)",
        original_c="Anthem",
    ),
    dict(
        name="PULCEL",
        actual="Celebrate series",
        community="anthem",
        eep="",
        custom=False,
        original="Anthem - Celebrate series (unit 81 - 8000 series)",
        original_c="Anthem",
    ),
    # anthem at merrill ranch
    dict(
        name="AMRU20",
        actual="AMR-Unit 20 / Classics, Premiers, Estates",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Unit 20 / Classics, Premiers, Estates",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="AMRU40",
        actual="AMR-Unit 40 Holiday, Cottages, Classics, Prem, Est",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Unit 40 Holiday, Cottages, Classics, Prem, Est",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULACC1",
        actual="AMR-DW/unit 19/acclaim",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-DW/unit 19/acclaim",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULAMB70",
        actual="AMR-FC/3500s",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-FC/3500s",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULCAC70",
        actual="AMR ~ Parkside ~ Cactus ~ 4000",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR ~ Parkside ~ Cactus ~ 4000",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULCAN70",
        actual="AMR ~ Parkside ~ Canyon ~ 5000",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR ~ Parkside ~ Canyon ~ 5000",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULCLA70SR",
        actual="AMR-Classics",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Classics",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULCOT70SR",
        actual="AMR-Cottages",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Cottages",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULCTR1",
        actual="AMR Unit 39/Cantera/Andover/FC 4500s",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR Unit 39/Cantera/Andover/FC 4500s",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULCTR70",
        actual="AMR-Pulte 4500s",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Pulte 4500s",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULDSC1",
        actual="AMR-Unit 12/discovery",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Unit 12/discovery",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULEST70SR",
        actual="AMR-Estates",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Estates",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULHER1",
        actual="AMR-DW/unit13/heritage/celebration/3000s",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-DW/unit13/heritage/celebration/3000s",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULHOL70SR",
        actual="AMR-Holiday Series",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Holiday Series",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULMOD1",
        actual="AMR-Unit 2/holiday Series/model Home Park",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Unit 2/holiday Series/model Home Park",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULPRE70SR",
        actual="AMR-Premiers",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Premiers",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULREU1",
        actual="AMR-DW/unit 8/reunion/estates",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-DW/unit 8/reunion/estates",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULSAV1",
        actual="AMR-Unit 29/savoy",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Unit 29/savoy",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULSER1",
        actual="AMR-Unit 10/serenity",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-Unit 10/serenity",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULTAP1",
        actual="AMR-DW/Unit 15/Tapestry/5400s",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-DW/Unit 15/Tapestry/5400s",
        original_c="Anthem at Merrill Ranch",
    ),
    dict(
        name="PULTRA70",
        actual="AMR-FC/4000",
        community="anthem at merrill ranch",
        eep="",
        custom=False,
        original="AMR-FC/4000",
        original_c="Anthem at Merrill Ranch",
    ),
    # arroyo mountain estates
    dict(
        name="SHEGRA",
        actual="Granite Ridge",
        community="arroyo mountain estates",
        eep="",
        custom=False,
        original="Granite Ridge at Arroyo Mountain Estates",
        original_c="Arroyo Mountain Estates",
    ),
    dict(
        name="SHEMOU",
        actual="Mountain Shadows",
        community="arroyo mountain estates",
        eep="",
        custom=False,
        original="Mountain Shadows at Arroyo Mountain Estates",
        original_c="Arroyo Mountain Estates",
    ),
    dict(
        name="SHEMOU70",
        actual="Mountain Shadows",
        community="arroyo mountain estates",
        eep="",
        custom=False,
        original="Mountain Shadows at Arroyo Mountain Estates",
        original_c="Arroyo Mountain Estates",
    ),
    # canyon trails
    dict(
        name="REFSTA70",
        actual="Reflections/Stargazer",
        community="canyon trails",
        eep="",
        custom=False,
        original="Centex Reflections/Stargazer -- Canyon Trails",
        original_c="",
    ),
    dict(
        name="SPCANT",
        actual="Sierra Point",
        community="canyon trails",
        eep="",
        custom=False,
        original="Sierra Point At Canyon Trails",
        original_c="",
    ),
    dict(
        name="TMCTLEG70",
        actual="Legacy",
        community="canyon trails",
        eep="",
        custom=False,
        original="Canyon Trails ~ Legacy",
        original_c="Canyon Trails",
    ),
    dict(
        name="TMCTSUM70",
        actual="Summit",
        community="canyon trails",
        eep="",
        custom=False,
        original="Canyon Trails ~ Summit",
        original_c="Canyon Trails",
    ),
    # cibola vista
    dict(
        name="CENPRE1",
        actual="The Preserve",
        community="cibola vista",
        eep="",
        custom=False,
        original="The Preserve at Cibola Vista",
        original_c="Cibola Vista",
    ),
    # cielo verde
    dict(
        name="JACCV1",
        actual="Cielo Verde",
        community="cielo verde",
        eep="",
        custom=False,
        original="Cielo Verde Phase I",
        original_c="Cielo Verde",
    ),
    # coldwater ranch
    dict(
        name="WLHARR",
        actual="Arroyo",
        community="coldwater ranch",
        eep="",
        custom=False,
        original="Arroyo at Coldwater Ranch",
        original_c="",
    ),
    # colina del sur
    dict(
        name="KHVREGCDS70",
        actual="Regency",
        community="colina del sur",
        eep="",
        custom=False,
        original="Regency @ Colina Del Sur",
        original_c="",
    ),
    # dc ranch
    dict(
        name="ROSDCR",
        actual="Rosewood Homes",
        community="dc ranch",
        eep="",
        custom=False,
        original="Rosewood Homes at D.C. Ranch",
        original_c="DC Ranch",
    ),
    dict(
        name="ROSDCR70",
        actual="Rosewood Home",
        community="dc ranch",
        eep="",
        custom=False,
        original="Rosewood At Dc Ranch",
        original_c="DC Ranch",
    ),
    # desert oasis
    dict(
        name="CENHAR1",
        actual="Harmony",
        community="desert oasis",
        eep="",
        custom=False,
        original="Harmony at Desert Oasis",
        original_c="Desert Oasis",
    ),
    dict(
        name="CENHAV",
        actual="Haven",
        community="desert oasis",
        eep="",
        custom=False,
        original="Haven at Desert Oasis",
        original_c="Desert Oasis",
    ),
    dict(
        name="CENSER1",
        actual="Serenade",
        community="desert oasis",
        eep="",
        custom=False,
        original="Serenade at Desert Oasis",
        original_c="Desert Oasis",
    ),
    # dynamite mountain ranch
    dict(
        name="DMRVIS70",
        actual="Fireside At Norterra/Vista/FC 4000",
        community="dynamite mountain ranch",
        eep="",
        custom=False,
        original="Fireside At Norterra/Vista/FC 4000",
        original_c="Dynamite Mountain Ranch",
    ),
    # eagle heights
    dict(
        name="KHVREH",
        actual="Regency",
        community="eagle heights",
        eep="",
        custom=False,
        original="Regency At Eagle Heights",
        original_c="NA",
    ),
    # estrella
    dict(
        name="JCHCM70SR",
        actual="CantaMia",
        community="estrella",
        eep="",
        custom=False,
        original="AVATAR-CantaMia At Estrella",
        original_c="",
    ),
    # estrella mountain ranch
    dict(
        name="ASHLPM70",
        actual="Las Palmas At Montecito",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="Las Palmas At Montecito",
        original_c="Estrella Mountain Ranch",
    ),
    dict(
        name="LAENT",
        actual="La Entrada",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="La Entrada - Montecito in Estrella  100s",
        original_c="Estrella Mountain Ranch",
    ),
    dict(
        name="LAMIR",
        actual="La Mirada",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="La Mirada - Montecito in Estrella  700s",
        original_c="Estrella Mountain Ranch",
    ),
    dict(
        name="MARMED",
        actual="Medina",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="Medina At Estrella",
        original_c="Estrella Mountain Ranch",
    ),
    dict(
        name="MARMED70",
        actual="Medina",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="Medina @ Estrella",
        original_c="",
    ),
    dict(
        name="MARMEDSR",
        actual="Medina",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="Medina At Estrella",
        original_c="Estrella Mountain Ranch",
    ),
    dict(
        name="RICBEM70",
        actual="Bennett",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="Bennett At Estrella Mountain",
        original_c="Estrella Mountain Ranch",
    ),
    dict(
        name="ROSGAT",
        actual="Stone Gate",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="Stone Gate",
        original_c="Estrella Mountain Ranch",
    ),
    dict(
        name="ROSGAT70SR",
        actual="Stone Gate",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="Stone Gate In Montecito At Estrella",
        original_c="Estrella Mountain Ranch",
    ),
    dict(
        name="WRHIRO70SR",
        actual="Ironwood Pointe",
        community="estrella mountain ranch",
        eep="",
        custom=False,
        original="Ironwood Pointe",
        original_c="Estrella Mountain Ranch",
    ),
    # festival ranch
    dict(
        name="PULADO",
        actual="Festival Foothills - Adobe",
        community="festival ranch",
        eep="",
        custom=False,
        original="Festival Foothills - Adobe",
        original_c="Festival Ranch",
    ),
    dict(
        name="PULPEA",
        actual="Festival Foothills - Peak",
        community="festival ranch",
        eep="",
        custom=False,
        original="Festival Foothills - Peak",
        original_c="Festival Ranch",
    ),
    dict(
        name="PULRID",
        actual="Festival Foothills - Ridge",
        community="festival ranch",
        eep="",
        custom=False,
        original="Festival Foothills - Ridge",
        original_c="Festival Ranch",
    ),
    dict(
        name="PULSON",
        actual="Festival Foothills - Sonoran",
        community="festival ranch",
        eep="",
        custom=False,
        original="Festival Foothills - Sonoran",
        original_c="Festival Ranch",
    ),
    # fireside at desert ridge
    dict(
        name="PDRMAJ1",
        actual="Desert Ridge -DW/majesty/5500s",
        community="fireside at desert ridge",
        eep="",
        custom=False,
        original="Desert Ridge -DW/majesty/5500s",
        original_c="Fireside at Desert Ridge",
    ),
    dict(
        name="PDRMON1",
        actual="Desert Ridge-DW/monument/4500s",
        community="fireside at desert ridge",
        eep="",
        custom=False,
        original="Desert Ridge-DW/monument/4500s",
        original_c="Fireside at Desert Ridge",
    ),
    # fireside at norterra
    dict(
        name="DMRALL1",
        actual="Norterra DW/allegro/G8000s",
        community="fireside at norterra",
        eep="",
        custom=False,
        original="Norterra DW/allegro/G8000s",
        original_c="Fireside at Norterra",
    ),
    dict(
        name="DMRMAE",
        actual="Norterra Maestro - Pulte 4000 Vista",
        community="fireside at norterra",
        eep="",
        custom=False,
        original="Norterra Maestro - Pulte 4000 Vista",
        original_c="Fireside at Norterra",
    ),
    dict(
        name="DMRMAJ70",
        actual="Fireside @ Norterra ~ Majesty 5500",
        community="fireside at norterra",
        eep="",
        custom=False,
        original="Fireside @ Norterra ~ Majesty 5500",
        original_c="Fireside at Norterra",
    ),
    # granite park
    dict(
        name="SPHCGP70",
        actual="Canyons",
        community="granite park",
        eep="",
        custom=False,
        original="Canyons At Granite Park",
        original_c="",
    ),
    # grayhawk
    dict(
        name="CACENC",
        actual="Encore",
        community="grayhawk",
        eep="",
        custom=False,
        original="Encore at Grayhawk",
        original_c="Grayhawk",
    ),
    # lone mountain
    dict(
        name="LENELM70",
        actual="Estates",
        community="lone mountain",
        eep="",
        custom=False,
        original="Estates At Lone Mountain",
        original_c="",
    ),
    dict(
        name="PULLON",
        actual="Lone Mountain",
        community="lone mountain",
        eep="",
        custom=False,
        original="INACTIVE-Lone Mountain",
        original_c="Lone Mountain",
    ),
    # marley park
    dict(
        name="ASHMAB",
        actual="Bloomfield",
        community="marley park",
        eep="",
        custom=False,
        original="Marley Park - Bloomfield",
        original_c="Marley Park",
    ),
    dict(
        name="MATHMP70",
        actual="Mattamy Homes",
        community="marley park",
        eep="",
        custom=False,
        original="Mattamy Homes At Marley Park",
        original_c="Marley Park",
    ),
    dict(
        name="RICBMP70",
        actual="Bennett",
        community="marley park",
        eep="",
        custom=False,
        original="Bennett At Marley Park",
        original_c="Marley Park",
    ),
    # mirabel village
    dict(
        name="MONMBV70SR",
        actual="Monterey",
        community="mirabel village",
        eep="",
        custom=False,
        original="Monterey at Mirabel Village",
        original_c="",
    ),
    # montecito
    dict(
        name="WRHSER70SR",
        actual="Serenity",
        community="montecito",
        eep="",
        custom=False,
        original="Serenity At Montecito",
        original_c="",
    ),
    # mountain ranch
    dict(
        name="WRHGRE70SR",
        actual="Greenspointe",
        community="mountain ranch",
        eep="",
        custom=False,
        original="Greenspointe at Mountain Ranch",
        original_c="",
    ),
    # palm valley
    dict(
        name="70JCHPRE",
        actual="Preserve",
        community="palm valley",
        eep="",
        custom=False,
        original="AVATAR-Preserve At Palm Valley",
        original_c="Palm Valley",
    ),
    dict(
        name="70MPVCOSR",
        actual="Cortile",
        community="palm valley",
        eep="",
        custom=False,
        original="Palm Valley Cortile",
        original_c="Palm Valley",
    ),
    dict(
        name="JCHSER70SR",
        actual="Seren",
        community="palm valley",
        eep="",
        custom=False,
        original="AVATAR-Sereno At Palm Valley",
        original_c="",
    ),
    dict(
        name="MARMOR",
        actual="Morada",
        community="palm valley",
        eep="",
        custom=False,
        original="Morada At Palm Valley",
        original_c="",
    ),
    dict(
        name="MARMORsr",
        actual="Morada",
        community="palm valley",
        eep="",
        custom=False,
        original="Morada At Palm Valley",
        original_c="",
    ),
    dict(
        name="MARMORsr70",
        actual="Morada",
        community="palm valley",
        eep="",
        custom=False,
        original="Morada @ Palm Valley",
        original_c="",
    ),
    dict(
        name="RICCPV70",
        actual="Cottages",
        community="palm valley",
        eep="",
        custom=False,
        original="Cottages At Palm Valley",
        original_c="",
    ),
    dict(
        name="STAPAL70",
        actual="Palm Valley",
        community="palm valley",
        eep="",
        custom=False,
        original="Palm Valley",
        original_c="Palm Valley",
    ),
    # portales
    dict(
        name="ASHSAN70",
        actual="San Rafael",
        community="portales",
        eep="",
        custom=False,
        original="San Rafael At Portales",
        original_c="",
    ),
    dict(
        name="TWLCAL",
        actual="Calderra",
        community="portales",
        eep="",
        custom=False,
        original="Calderra at Portales (1000s)",
        original_c="",
    ),
    dict(
        name="TWLLOS",
        actual="Los Vientos",
        community="portales",
        eep="",
        custom=False,
        original="Los Vientos at Portales (2000-3000s)",
        original_c="",
    ),
    dict(
        name="TWLTOR",
        actual="Torremar",
        community="portales",
        eep="",
        custom=False,
        original="Torremar at Portales (4000s)",
        original_c="",
    ),
    # prescott lakes
    dict(
        name="DORBRO70",
        actual="Brookside & Lakeside",
        community="prescott lakes",
        eep="",
        custom=False,
        original="Brookside/lakeside At Prescott Lakes",
        original_c="",
    ),
    # sonoran foothills
    dict(
        name="MARDES",
        actual="Desert Pass",
        community="sonoran foothills",
        eep="",
        custom=False,
        original="Desert Pass At Sonoran Foothills",
        original_c="",
    ),
    dict(
        name="TWLDES",
        actual="Desert Trails",
        community="sonoran foothills",
        eep="",
        custom=False,
        original="Desert Trails at Sonoran Foothills (2000-3000s)",
        original_c="",
    ),
    dict(
        name="TWLDSP",
        actual="Desert Springs",
        community="sonoran foothills",
        eep="",
        custom=False,
        original="Desert Springs at Sonoran Foothills (1000s)",
        original_c="",
    ),
    # stetson valley
    dict(
        name="KHVENCSV70",
        actual="Enclave",
        community="stetson valley",
        eep="",
        custom=False,
        original="Enclave @ Stetson Valley",
        original_c="Stetson Valley",
    ),
    dict(
        name="LENEST70",
        actual="Estates",
        community="stetson valley",
        eep="",
        custom=False,
        original="Estates At Stetson Valley",
        original_c="Stetson Valley",
    ),
    dict(
        name="LENHOR70",
        actual="Horizon",
        community="stetson valley",
        eep="",
        custom=False,
        original="Horizon At Stetson Valley",
        original_c="Stetson Valley",
    ),
    dict(
        name="LENSIG70",
        actual="Signatures",
        community="stetson valley",
        eep="",
        custom=False,
        original="Signatures At Stetson Valley",
        original_c="Stetson Valley",
    ),
    dict(
        name="LENVIS70",
        actual="Vision",
        community="stetson valley",
        eep="",
        custom=False,
        original="Vision At Stetson Valley",
        original_c="Stetson Valley",
    ),
    dict(
        name="PULMNU70",
        actual="Stetson Monument Series",
        community="stetson valley",
        eep="",
        custom=False,
        original="Stetson Monument Series 3500s",
        original_c="Stetson Valley",
    ),
    dict(
        name="PULPRO",
        actual="Stetson Prospector",
        community="stetson valley",
        eep="",
        custom=False,
        original="Stetson Prospector / 5000's",
        original_c="Stetson Valley",
    ),
    dict(
        name="PULSTD",
        actual="Stetson Discovery",
        community="stetson valley",
        eep="",
        custom=False,
        original="Stetson Discovery / 6500'S",
        original_c="Stetson Valley",
    ),
    dict(
        name="PULSTH",
        actual="Stetson Harmony",
        community="stetson valley",
        eep="",
        custom=False,
        original="Stetson Harmony / Cluster / 6-pack",
        original_c="Stetson Valley",
    ),
    dict(
        name="PULSTP",
        actual="Stetson Pioneer",
        community="stetson valley",
        eep="",
        custom=False,
        original="Stetson Pioneer / 5500's",
        original_c="Stetson Valley",
    ),
    dict(
        name="PULSTT",
        actual="Stetson Treasure",
        community="stetson valley",
        eep="",
        custom=False,
        original="Stetson Treasure / 4500's",
        original_c="Stetson Valley",
    ),
    # sun city festival
    dict(
        name="DWCLAS70SR",
        actual="Classics",
        community="sun city festival",
        eep="",
        custom=False,
        original="Sun City Festival DW - Classics",
        original_c="",
    ),
    dict(
        name="DWCOTT70SR",
        actual="Cottages",
        community="sun city festival",
        eep="",
        custom=False,
        original="Sun City Festival DW - Cottages",
        original_c="",
    ),
    dict(
        name="DWESTA70SR",
        actual="Estates",
        community="sun city festival",
        eep="",
        custom=False,
        original="Sun City Festival DW - Estates",
        original_c="",
    ),
    dict(
        name="DWHOLI70SR",
        actual="Holiday",
        community="sun city festival",
        eep="",
        custom=False,
        original="Sun City Festival DW - Holiday",
        original_c="",
    ),
    dict(
        name="DWPREM70SR",
        actual="Premiers",
        community="sun city festival",
        eep="",
        custom=False,
        original="Sun City Festival DW - Premiers",
        original_c="",
    ),
    # sundance
    dict(
        name="MERSUN",
        actual="Sundance Active Adult",
        community="sundance",
        eep="",
        custom=False,
        original="Sundance Active Adult",
        original_c="Sundance",
    ),
    dict(
        name="MERSUNSR",
        actual="Sundance Active Adult",
        community="sundance",
        eep="",
        custom=False,
        original="Sundance Active Adult",
        original_c="",
    ),
    # sunset ranch
    dict(
        name="WOOSUN70",
        actual="Encore",
        community="sunset ranch",
        eep="",
        custom=False,
        original="Encore at Sunset Ranch",
        original_c="",
    ),
    dict(
        name="WOOSUN70SR",
        actual="Encore",
        community="sunset ranch",
        eep="",
        custom=False,
        original="Encore at Sunset Ranch",
        original_c="",
    ),
    # surprise farms
    dict(
        name="PERSUP70SRS",
        actual="Peralta",
        community="surprise farms",
        eep="",
        custom=False,
        original="Peralta At Surprise Farms",
        original_c="",
    ),
    dict(
        name="REGSUP70SRS",
        actual="Regency",
        community="surprise farms",
        eep="",
        custom=False,
        original="Regency At Surprise Farms",
        original_c="",
    ),
    dict(
        name="TMDISC70",
        actual="Discovery",
        community="surprise farms",
        eep="",
        custom=False,
        original="Surprise Farms P5 - Discovery",
        original_c="Surprise Farms",
    ),
    dict(
        name="TMENCOR70",
        actual="Encore",
        community="surprise farms",
        eep="",
        custom=False,
        original="Surprise Farms P5 - Encore",
        original_c="Surprise Farrms",
    ),
    dict(
        name="TMODYSS70",
        actual="Odyssey",
        community="surprise farms",
        eep="",
        custom=False,
        original="Surprise Farms P5 - Odyssey",
        original_c="Surprise Farms",
    ),
    dict(
        name="TMPREM70",
        actual="Premiere",
        community="surprise farms",
        eep="",
        custom=False,
        original="Surprise Farms P3 - Premiere",
        original_c="Surprise Farms",
    ),
    dict(
        name="VERSUP70SRS",
        actual="Verona",
        community="surprise farms",
        eep="",
        custom=False,
        original="Verona At Surprise Farms",
        original_c="",
    ),
    # the view
    dict(
        name="SUNTER",
        actual="Sunset Terrace",
        community="the view",
        eep="",
        custom=False,
        original="Sunset Terrace At The View",
        original_c="",
    ),
    dict(
        name="SUNTERSR",
        actual="Sunset Terrace",
        community="the view",
        eep="",
        custom=False,
        original="Sunset Terrace At The View",
        original_c="",
    ),
    # verrado
    dict(
        name="ASHFVW70",
        actual="Fairview Park",
        community="verrado",
        eep="",
        custom=False,
        original="Fairview Park",
        original_c="Verrado",
    ),
    dict(
        name="ASHVEC",
        actual="Casitas",
        community="verrado",
        eep="",
        custom=False,
        original="Verrado - Casitas",
        original_c="Verrado",
    ),
    dict(
        name="ASHVEM70",
        actual="Madison Park",
        community="verrado",
        eep="",
        custom=False,
        original="Madison Park At Verrado",
        original_c="Verrado",
    ),
    dict(
        name="ASHVEP",
        actual="Presidio",
        community="verrado",
        eep="",
        custom=False,
        original="Verrado - Presidio",
        original_c="Verrado",
    ),
    dict(
        name="CACSUM",
        actual="Summit Park",
        community="verrado",
        eep="",
        custom=False,
        original="Verrado - Summit Park",
        original_c="Verrado",
    ),
    dict(
        name="CENPAR1",
        actual="Parkview Square",
        community="verrado",
        eep="",
        custom=False,
        original="Parkview Square at Verrado",
        original_c="Verrado",
    ),
    dict(
        name="KHVAV70",
        actual="Avalon",
        community="verrado",
        eep="",
        custom=False,
        original="Avalon At Verrado",
        original_c="Verrado",
    ),
    dict(
        name="KHVAVV",
        actual="Avalon",
        community="verrado",
        eep="",
        custom=False,
        original="Avalon at Verrado (plans 46,47,48,49)",
        original_c="Verrado",
    ),
    dict(
        name="KHVVHV70",
        actual="Vintage",
        community="verrado",
        eep="",
        custom=False,
        original="Vintage At Happy Valley",
        original_c="",
    ),
    dict(
        name="KHVVIV",
        actual="Vintage",
        community="verrado",
        eep="",
        custom=False,
        original="Vintage At Verrado (plans 41,42,43,45)",
        original_c="Verrado",
    ),
    dict(
        name="KHVVV70",
        actual="Vintage",
        community="verrado",
        eep="",
        custom=False,
        original="Vintage At Verrado",
        original_c="Verrado",
    ),
    dict(
        name="MARVER70",
        actual="Maracay",
        community="verrado",
        eep="",
        custom=False,
        original="Maracay At Verrado",
        original_c="Verrado",
    ),
    dict(
        name="MONVER70SR",
        actual="Monterrey",
        community="verrado",
        eep="",
        custom=False,
        original="Monterrey At Verrado",
        original_c="Verrado",
    ),
    dict(
        name="RICDAV70",
        actual="Davis",
        community="verrado",
        eep="",
        custom=False,
        original="Davis At Verrado",
        original_c="Verrado",
    ),
    dict(
        name="TREVER",
        actual="Verrado",
        community="verrado",
        eep="",
        custom=False,
        original="Verrado",
        original_c="Verrado",
    ),
    # vistancia
    dict(
        name="ASHVIS",
        actual="Eagle Canyon",
        community="vistancia",
        eep="",
        custom=False,
        original="Vistancia - Eagle Canyon at Vistancia",
        original_c="Vistancia",
    ),
    dict(
        name="KHVEST",
        actual="Estates at Blackstone",
        community="vistancia",
        eep="",
        custom=False,
        original="Estates At Blackstone",
        original_c="Blackstone At Vistancia",
    ),
    dict(
        name="KHVEBS70",
        actual="Estates at Blackstone",
        community="vistancia",
        eep="",
        custom=False,
        original="Estates At Blackstone",
        original_c="NA",
    ),
    dict(
        name="MERARV",
        actual="Aria",
        community="vistancia",
        eep="",
        custom=False,
        original="Aria At Vistancia",
        original_c="Vistancia",
    ),
    dict(
        name="MERARV70",
        actual="Aria",
        community="vistancia",
        eep="",
        custom=False,
        original="Aria At Vistancia",
        original_c="Vistancia",
    ),
    dict(
        name="ROSPRO",
        actual="Mountain Gate",
        community="vistancia",
        eep="",
        custom=False,
        original="Production Parcel G-3/A-30 -- Mountain Gate at Vis",
        original_c="Vistancia",
    ),
    dict(
        name="ROSPRO70SR",
        actual="Mountain Gate",
        community="vistancia",
        eep="",
        custom=False,
        original="Mountain Gate At Vistancia",
        original_c="Vistancia",
    ),
    dict(
        name="SHEMVE",
        actual="Mountain View Estates",
        community="vistancia",
        eep="",
        custom=False,
        original="Mountain View Estates at Vistancia",
        original_c="Vistancia",
    ),
    dict(
        name="SHETRI2",
        actual="Trilogy",
        community="vistancia",
        eep="",
        custom=False,
        original="Trilogy At Vistancia",
        original_c="Vistancia",
    ),
    dict(
        name="SHETRI270",
        actual="Trilogy",
        community="vistancia",
        eep="",
        custom=False,
        original="Trilogy",
        original_c="Vistancia",
    ),
    dict(
        name="TWLALT",
        actual="Alta Vista",
        community="vistancia",
        eep="",
        custom=False,
        original="AltaVista at Vistancia (1000s)",
        original_c="Vistancia",
    ),
    dict(
        name="TWLALT70",
        actual="Alta Vista",
        community="vistancia",
        eep="",
        custom=False,
        original="Alta Vista",
        original_c="Vistancia",
    ),
    dict(
        name="TWLBLA70",
        actual="Blackstone",
        community="vistancia",
        eep="",
        custom=False,
        original="Vistancia At Blackstone",
        original_c="Vistancia",
    ),
    # watson estates
    dict(
        name="SHBRIWE70",
        actual="Brighton",
        community="watson estates",
        eep="",
        custom=False,
        original="Brighton @ Watson Estates",
        original_c="Watson Estates",
    ),
    dict(
        name="SHKENWE70",
        actual="Kensington",
        community="watson estates",
        eep="",
        custom=False,
        original="Kensington @ Watson Estates",
        original_c="Watson Estates",
    ),
    # white tank foothills
    dict(
        name="PULCNY70",
        actual="Canyon",
        community="white tank foothills",
        eep="",
        custom=False,
        original="White Tank Foothills-Canyon/5400s",
        original_c="White Tank Foothills",
    ),
    dict(
        name="PULCOM70",
        actual="Compass",
        community="white tank foothills",
        eep="",
        custom=False,
        original="White Tank Foothills-Compass/4500s",
        original_c="White Tank Foothills",
    ),
    dict(
        name="PULDIS70",
        actual="Discovery",
        community="white tank foothills",
        eep="",
        custom=False,
        original="White Tank Foothills-Discovery/6500s",
        original_c="White Tank Foothills",
    ),
    dict(
        name="PULSMT",
        actual="Summit",
        community="white tank foothills",
        eep="",
        custom=False,
        original="White Tank Foothills - Summit",
        original_c="White Tank Foothills",
    ),
    dict(
        name="PULTRL",
        actual="Trailhead",
        community="white tank foothills",
        eep="",
        custom=False,
        original="White Tank Foothills - Trailhead",
        original_c="White Tank Foothills",
    ),
]
