"""This was generated via write_program"""

__author__ = "Steven K"
__date__ = "04/23/2022 21:35"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = [
    "Steven K",
]

from axis.eep_program.program_builder.base import ProgramBuilder
import datetime
from collections import OrderedDict


class UtilityIncentiveV1SingleFamily(ProgramBuilder):
    name = "Utility Incentive V1 - Single Family"
    slug = "utility-incentive-v1-single-family"
    owner = "neea"
    is_qa_program = False
    opt_in = True
    workflow_default_settings = {}
    min_hers_score = 0
    max_hers_score = 100
    per_point_adder = 0.0
    builder_incentive_dollar_value = 0.0
    rater_incentive_dollar_value = 0.0
    enable_standard_disclosure = False
    require_floorplan_approval = False
    require_input_data = True
    require_rem_data = True
    require_model_file = True
    require_ekotrope_data = False
    require_rater_of_record = False
    manual_transition_on_certify = True
    allow_sampling = True
    allow_metro_sampling = True
    require_resnet_sampling_provider = False
    is_legacy = False
    is_public = False
    is_active = True
    is_multi_family = False

    visibility_date = datetime.date(2017, 1, 31)
    start_date = datetime.date(2017, 1, 31)
    close_date = datetime.date(2019, 1, 27)
    submit_date = datetime.date(2019, 1, 27)
    end_date = datetime.date(2019, 1, 27)

    comment = (
        """Version 1 of the NEEA Utility Incentive program for Single Family new construction."""
    )

    require_home_relationships = {
        "builder": True,
        "hvac": True,
        "utility": True,
        "rater": True,
        "provider": True,
        "qa": True,
    }
    require_provider_relationships = {
        "builder": True,
        "hvac": True,
        "utility": False,
        "rater": True,
        "provider": True,
        "qa": True,
    }
    measures = {
        "rater": {
            "default": [
                "for-this-home-upload-a-copy-of-the-nw-compliance",
            ],
        },
    }
    texts = {
        "rater": {
            "for-this-home-upload-a-copy-of-the-nw-compliance": "For this home, upload a copy of the NW Compliance Report as generated by REM/Rate.",
        },
    }
    descriptions = {
        "rater": {},
    }
    suggested_responses = {
        "rater": {
            (
                "Upload Document(s)",
                "Not Applicable (comment required)",
            ): [
                "for-this-home-upload-a-copy-of-the-nw-compliance",
            ],
        },
    }
    suggested_response_flags = {
        "rater": {
            "for-this-home-upload-a-copy-of-the-nw-compliance": {
                "Upload Document(s)": {
                    "document_required": True,
                },
                "Not Applicable (comment required)": {
                    "comment_required": True,
                },
            },
        },
    }
    annotations = OrderedDict(
        (
            (
                "heat-source",
                {
                    "name": "Primary Heat Source",
                    "data_type": "multiple-choice",
                    "valid_multiplechoice_values": "Heat Pump,Heat Pump - Geothermal/Ground Source,Heat Pump - w/ Gas Backup,Heat Pump - Mini Split,Gas with AC,Gas No AC,Zonal Electric,Propane Oil or Wood",
                    "is_required": "True",
                },
            ),
            (
                "project-start-nr",
                {
                    "name": "Project Start",
                    "data_type": "date",
                    "valid_multiplechoice_values": "",
                    "is_required": "True",
                },
            ),
        )
    )
