"""geea_form_fields.py: """


__author__ = "Rajesh P"
__date__ = "2020-05-07 12:57 PM"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = [
    "Steven Klass",
]

all_geea_checkbox_form_fields = (
    "ACH50",
    "Appliances ENERGY STAR Dishwasher",
    "Appliances ENERGY STAR Refrigerator",
    "Appliances ENERGY STAR WasherDryer",
    "Confirmed Rating",
    "ENERGY STAR",
    "Indoor airPLUS",
    "Leed Certified",
    "PHIUS 2015",
    "NGBS Silver",
    "NGBS Bronze",
    "NGBS Gold",
    "NGBS Emerald",
    "Living Building Certified",
    "PHI Low Energy",
    "Enerphit",
    "Passive House",
    "LEED Silver",
    "LEED Gold",
    "LEED Platinum",
    "LEED Certified",
    "Sampling Rating",
    "Projected Rating",
    "Petal Certification",
    "Energy Label Organization URL RESNET",
    "Energy Label Organization URL Home Energy Score",
    "Energy Label Organization URL Other",
    "Energy Label Verification reviewed on site",
    "Energy Label Verification attached to this report",
    "Verified Energy Improvements Verification reviewed on site",
    "Verified Energy Improvements Verification attached to this report",
    "Verified Energy Improvements Organization URL Other",
    "Verified Energy Improvements Organization URL energystar",
    "Fiberglass BlownIn",
    "Foam Insulation",
    "Cellulose",
    "Fiberglass Batt Insulation_1",
    "RValue",
    "Insulation Other",
    "Green Certification Verification reviewed on site",
    "Green Certification Verification attached to this report",
    "DOE Official Score",
    "DOE Unofficial Score",
    "CFM25",
    "CFM50",
    "ACH Natural",
    "Windows ENERGY STAR",
    "Windows Low E",
    "Windows High Impact",
    "Windows Storm",
    "Windows Double Pane",
    "Windows Triple Pane",
    "Windows Tinted",
    "Windows Solar Shades",
    "Appliances Source Propane",
    "Appliances Source Electric",
    "Appliances Source Natural Gas",
    "Appliances ENERGY STAR Other",
    "Appliances Source Other",
    "Water Heater ENERGY STAR",
    "Water Heater Tankless",
    "Water Heater Solar",
    "Water Heater Heat Pump",
    "Water Heater Coil",
    "High Efficiency HVAC",
    "Heat Pump Efficiency Rating",
    "Thermostat Controllers",
    "Programmable Thermostat",
    "Auxiliary heat source",
    "Radiant Floor Heat",
    "Geothermal",
    "Electric Vehicle Ready",
    "Indoor Environmental Quality ERV or HRV",
    "Indoor Environmental Quality Other",
    "Indoor Environmental Quality Humidity Monitoring",
    "Non Toxic Pest Control",
    "Radon System",
    "Radon System Active",
    "Radon System Passive",
    "Reclaimed Water System",
    "Greywater reuse system",
    "Water Saving Fixtures",
    "Rain Barrels Used in Irrigation",
    "Utility Costs Heating",
    "Utility Costs Electric",
    "Utility Costs Water",
    "Utility Costs Other",
    "Type of Ownership Array 1 Leased",
    "Type of Ownership Array 1 Owned",
    "Type of Ownership Array 1 Solar Loan with UCC Filing",
    "Type of Ownership Array 1 Power Purchase Agreement PPA",
    "Type of Ownership Array 2 Leased",
    "Type of Ownership Array 2 Owned",
    "Type of Ownership Array 2 Solar Loan",
    "Type of Ownership Array 2 UCC Filing",
    "Type of Ownership Array 2 PPA",
    "Array 1 Fixed Mount",
    "Array 1 Tracking Mount",
    "Battery Type Lithium-ion",
    "Battery Type Lithium-ion Polymer",
    "Battery Type Lead Acid",
    "Battery Type Lead Calcium",
    "Battery Type AGM",
    "Battery Type GEL",
    "Type of System Active Direct",
    "Type of System Active Indirect",
    "Type of System Inactive Integral collector",
    "Type of System Inactive Thermosyphon",
    "Collector Type Flat-Plat",
    "Collector Type Integral",
    "Collector Type Evacuated-Tube Solar",
    "Backup System Conventional Water Heater",
    "Backup System Tankless On Demand",
    "Backup System Tankless Heat Pump",
    "Walk Score Source walkscore",
    "Walk Score Source Other",
    "Public Transportation Bus",
    "Public Transportation Train",
    "Public Transportation Subway",
    "Site Orientation East West",
    "Site Orientation North South",
    "Site Landscaping Water Efficient",
    "Site Landscaping PondLake on site",
    "Site Landscaping Natural",
    "Site Landscaping Rain Garden",
    "WaterSense",
    "Zero Energy Ready Home ZERH",
)

repeating_fields = (
    "client_file_num",
    "appraisal_file_num",
    "Client",
    "Subject Property",
    "Completed by",
    "Completed Title",
    "Completed Date",
)
