"""us_states.py: """

__author__ = "Artem Hruzd"
__date__ = "09/28/2020 20:23"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = [
    "Artem Hruzd",
    "Steven Klass",
]

HIRL_INTERNAL_US_STATES = [
    {"ID": 1, "State": "Alaska", "StateAbbr": "AK"},
    {"ID": 2, "State": "Alabama", "StateAbbr": "AL"},
    {"ID": 3, "State": "Arkansas", "StateAbbr": "AR"},
    {"ID": 4, "State": "Arizona", "StateAbbr": "AZ"},
    {"ID": 5, "State": "California", "StateAbbr": "CA"},
    {"ID": 6, "State": "Colorado", "StateAbbr": "CO"},
    {"ID": 7, "State": "Connecticut", "StateAbbr": "CT"},
    {"ID": 8, "State": "District of Columbia", "StateAbbr": "DC"},
    {"ID": 9, "State": "Delaware", "StateAbbr": "DE"},
    {"ID": 10, "State": "Florida", "StateAbbr": "FL"},
    {"ID": 11, "State": "Georgia", "StateAbbr": "GA"},
    {"ID": 12, "State": "Hawaii", "StateAbbr": "HI"},
    {"ID": 13, "State": "Iowa", "StateAbbr": "IA"},
    {"ID": 14, "State": "Idaho", "StateAbbr": "ID"},
    {"ID": 15, "State": "Illinois", "StateAbbr": "IL"},
    {"ID": 16, "State": "Indiana", "StateAbbr": "IN"},
    {"ID": 17, "State": "Kansas", "StateAbbr": "KS"},
    {"ID": 18, "State": "Kentucky", "StateAbbr": "KY"},
    {"ID": 19, "State": "Louisiana", "StateAbbr": "LA"},
    {"ID": 20, "State": "Massachusetts", "StateAbbr": "MA"},
    {"ID": 21, "State": "Maryland", "StateAbbr": "MD"},
    {"ID": 22, "State": "Maine", "StateAbbr": "ME"},
    {"ID": 23, "State": "Michigan", "StateAbbr": "MI"},
    {"ID": 24, "State": "Minnesota", "StateAbbr": "MN"},
    {"ID": 25, "State": "Missouri", "StateAbbr": "MO"},
    {"ID": 26, "State": "Mississippi", "StateAbbr": "MS"},
    {"ID": 27, "State": "Montana", "StateAbbr": "MT"},
    {"ID": 28, "State": "North Carolina", "StateAbbr": "NC"},
    {"ID": 29, "State": "North Dakota", "StateAbbr": "ND"},
    {"ID": 30, "State": "Nebraska", "StateAbbr": "NE"},
    {"ID": 31, "State": "New Hampshire", "StateAbbr": "NH"},
    {"ID": 32, "State": "New Jersey", "StateAbbr": "NJ"},
    {"ID": 33, "State": "New Mexico", "StateAbbr": "NM"},
    {"ID": 34, "State": "Nevada", "StateAbbr": "NV"},
    {"ID": 35, "State": "New York", "StateAbbr": "NY"},
    {"ID": 36, "State": "Ohio", "StateAbbr": "OH"},
    {"ID": 37, "State": "Oklahoma", "StateAbbr": "OK"},
    {"ID": 38, "State": "Oregon", "StateAbbr": "OR"},
    {"ID": 39, "State": "Pennsylvania", "StateAbbr": "PA"},
    {"ID": 40, "State": "Rhode Island", "StateAbbr": "RI"},
    {"ID": 41, "State": "South Carolina", "StateAbbr": "SC"},
    {"ID": 42, "State": "South Dakota", "StateAbbr": "SD"},
    {"ID": 43, "State": "Tennessee", "StateAbbr": "TN"},
    {"ID": 44, "State": "Texas", "StateAbbr": "TX"},
    {"ID": 45, "State": "Utah", "StateAbbr": "UT"},
    {"ID": 46, "State": "Virginia", "StateAbbr": "VA"},
    {"ID": 47, "State": "Vermont", "StateAbbr": "VT"},
    {"ID": 48, "State": "Washington", "StateAbbr": "WA"},
    {"ID": 49, "State": "Wisconsin", "StateAbbr": "WI"},
    {"ID": 50, "State": "West Virginia", "StateAbbr": "WV"},
    {"ID": 51, "State": "Wyoming", "StateAbbr": "WY"},
    {"ID": 54, "State": "Alberta", "StateAbbr": "AB"},
    {
        "ID": 55,
        "State": "British Columbia",
        "StateAbbr": "BC",
    },
    {
        "ID": 56,
        "State": "Manitoba",
        "StateAbbr": "MB",
    },
    {
        "ID": 57,
        "State": "New Brunswick",
        "StateAbbr": "NB",
    },
    {
        "ID": 58,
        "State": "Newfoundland",
        "StateAbbr": "NL",
    },
    {
        "ID": 59,
        "State": "Northwest Territories",
        "StateAbbr": "NT",
    },
    {
        "ID": 60,
        "State": "Nova Scotia",
        "StateAbbr": "NS",
    },
    {
        "ID": 61,
        "State": "Ontario",
        "StateAbbr": "ON",
    },
    {"ID": 62, "State": "Prince Edward Island", "StateAbbr": "PE"},
    {"ID": 63, "State": "Quebec", "StateAbbr": "QC"},
    {
        "ID": 64,
        "State": "Saskatchewan",
        "StateAbbr": "SK",
    },
    {
        "ID": 65,
        "State": "Yukon",
        "StateAbbr": "YT",
    },
    {
        "ID": 67,
        "State": "U.S. Virgin Islands",
        "StateAbbr": "VI",
    },
    {"ID": 68, "State": "Puerto Rico", "StateAbbr": "PR"},
]
