import logging
import re

__author__ = "Autumn Valenta"
__date__ = "10/31/16 09:02"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = [
    "Steven Klass",
]

log = logging.getLogger(__name__)


THERMAL_ENVELOPE_FOUNDATION_TYPES = (
    "CONDITIONED_BASEMENT",
    "UNCONDITIONED_BASEMENT",
    "SLAB_ON_GRADE",
    "CRAWLSPACE",
)

MECHANICAL_EQUIPMENT_TYPES = (
    "AIR_CONDITIONER",
    "AIR_SOURCE_HEAT_PUMP",
    "BOILER",
    "FURNACE",
    "GROUND_SOURCE_HEAT_PUMP",
    "HOT_WATER_HEATER",
    "RADIANT_FLOOR_ELECTRIC",
    "RADIANT_FLOOR_HYDRONIC",
    "RESISTANCE_HEATER",
    "SOLAR_HOT_WATER",
    "CUSTOM",
)

MECHANICAL_EQUIPMENT_EFFICIENCY_TYPES = (
    "AFUE",
    "SEER",
    "EER",
    "HSPF",
    "COP",
    "ADJUSTED_EFFICIENCY",
    "ENERGY_FACTOR",
)

ENERGY_FUEL_TYPES = (
    "ELECTRIC",
    "NATURAL_GAS",
    "PROPANE",
    "OIL",
    "WOOD",
)
COMPONENT_CATEGORIES = (
    "ROOF",
    "FOUNDATION_WALL",
    "ABOVE_GROUND_WALL",
    "FRAMED_FLOOR",
    "RIM_JOIST",
    "SLAB",
    "WINDOW",
    "SKYLIGHT",
    "DOOR",
    "DISTRIBUTION",
    "INFILTRATION",
    "MECHANICAL_VENTILATION",
    "LIGHTING_AND_APPLICANCES",
    "INTERNAL_GAINS",
)

COMPLIANCE_CODES = (
    # "AEPOhio",
    "Ashrae62_2_2010",
    "Ashrae62_2_2013",
    # "ColumbiaGasOhio",
    # "ConsumersEnergyMichigan",
    "DOEZeroEnergyReady",
    # "DTERebateProgram",
    # "DTERebateProgram2021",
    # "DTERebateProgram2022",
    # "DominionVirginiaProgram",
    # "DukeEnergyCarolinas",
    # "DukeNC2018HEROPerformance",
    # "DukeNCHEROPerformance",
    # "DukeRebate2018",
    # "DukeRebate_1_1_19",
    # "DukeRebate_1_1_22",
    # "DukeRebate_8_1_18",
    # "ElPasoElectric",
    # "EnergyStarFloridaV31",
    "EnergyStarMFV1",
    "EnergyStarMFV11",
    "EnergyStarV2",
    "EnergyStarV3",
    "EnergyStarV31",
    "EnergyStarWaOrV32",
    # "EversourceNHProgram",
    # "Georgia2020ERI",
    # "Georgia2020Performance",
    # "Georgia2020Prescriptive",
    # "HERS",
    # "ICFTexasAEP",
    # "ICFTexasAEP2021",
    # "ICFTexasTNMP",
    "IECC2006Performance",
    "IECC2006Prescriptive",
    "IECC2009Performance",
    "IECC2009Prescriptive",
    "IECC2012Performance",
    "IECC2012Prescriptive",
    "IECC2015ERI",
    "IECC2015Performance",
    "IECC2015Prescriptive",
    "IECC2018ERI",
    "IECC2018Performance",
    "IECC2018Prescriptive",
    "IECC2021ERI",
    "IECC2021Performance",
    "IECC2021Prescriptive",
    # "Indiana2020Performance",
    "IndoorAirPlus",
    # "Iowa2012Performance",
    # "Iowa2012Prescriptive",
    "LeedSourceEnergyBudget",
    # "Maryland2018ERI",
    # "MassSave2016",
    # "MassSave2017",
    # "MassSave2019",
    # "MassSave2020Oit",
    # "MassSaveRAndA",
    # "MassSaveRAndA2019",
    # "MassSaveRAndA2020",
    # "MassSaveRAndA2020Oit",
    "NGBS2015",
    "NGBS2020",
    "NGBS2020ERI",
    # "NVEnergyICF",
    # "NVEnergyICF2021",
    # "NewJerseyCEP",
    # "NewMexicoICF",
    # "NewYork2016ERI",
    # "NewYork2016Performance",
    # "NewYork2016Prescriptive",
    # "NewYork2020ERI",
    # "NewYork2020Performance",
    # "NewYork2020Prescriptive",
    "NorthCarolina2012Performance",
    "NorthCarolina2012Prescriptive",
    # "NorthCarolina2018Eri",
    # "NorthCarolina2018HEROPrescriptive",
    # "NorthCarolina2018Performance",
    # "NorthCarolina2018Prescriptive",
    # "NorthernNevada2018Eri",
    # "NorthernNevada2018Performance",
    # "NorthernNevada2018Prescriptive",
    # "Ohio2019ERI",
    # "Ohio2019OHBACompPath1",
    # "Ohio2019OHBACompPath2",
    # "Ohio2019Performance",
    # "Ohio2019Prescriptive",
    # "Pennsylvania2015ERI",
    # "Pennsylvania2015Performance",
    # "Pennsylvania2015Prescriptive",
    # "RNCWashingtonGasVaProgram",
    "SRPICFProgram",
    # "SouthernNevada2018Eri",
    # "SouthernNevada2018Performance",
    # "SouthernNevada2018Prescriptive",
    "TaxCredit45L",
    # "Virginia2015ERI",
    # "Virginia2015Performance",
    # "Virginia2015Prescriptive",
    # "Virginia2018ERI",
    # "Virginia2018Performance",
    # "Virginia2018Prescriptive",
)

BUILIDING_TYPES = (
    "Austin2015Proposed",
    "Austin2015Reference",
    "CenterpointTX2019Reference",
    "ConnecticutRebateProposed",
    "ConnecticutRebateReference",
    "DOEZeroEnergyReadyTarget",
    "DominionVA2021ReferenceHome",
    "DukeNorthCarolina2017Proposed",
    "DukeNorthCarolina2017Reference",
    "DukeNorthCarolina2018HEROProposed",
    "DukeNorthCarolina2018HEROReference",
    "DukeNorthCarolinaHEROProposed",
    "DukeNorthCarolinaHEROReference",
    "DukeNorthCarolinaProposed_1_1_19",
    "DukeNorthCarolinaProposed_8_1_18",
    "DukeNorthCarolinaReference_1_1_19",
    "DukeNorthCarolinaReference_8_1_18",
    "EPSNewConstructionOregon2019Proposed",
    "EPSNewConstructionOregon2019Reference",
    "EPSNewConstructionOregonCentral2020Proposed",
    "EPSNewConstructionOregonCentral2020Reference",
    "EPSNewConstructionOregonZonal2020Proposed",
    "EPSNewConstructionOregonZonal2020Reference",
    "EkotropeAsModeled",
    "EnergyStarMFV11Reference",
    "EnergyStarMFV11Reference2019",
    "EnergyStarMFV1Reference",
    "EnergyStarMFV1Reference2019",
    "EnergyStarV31Reference",
    "EnergyStarV32Reference",
    "EnergyStarV3Reference",
    "Georgia2020Proposed",
    "Georgia2020Reference",
    "HERSRated",
    "HERSReference",
    "IECC2006Proposed",
    "IECC2006Reference",
    "IECC2006ReferenceFederalMin",
    "IECC2009Proposed",
    "IECC2009Reference",
    "IECC2009ReferenceFederalMin",
    "IECC2012Proposed",
    "IECC2012Reference",
    "IECC2012ReferenceFederalMin",
    "IECC2012_4ACH50MultifamilyReference",
    "IECC2012_5ACH50Reference",
    "IECC2015Proposed",
    "IECC2015Reference",
    "IECC2015ReferenceFederalMin",
    "IECC2015_24SF_30MF_CFM50PerSqFtShellReference",
    "IECC2015_4ACH50MultifamilyReference",
    "IECC2015_4ACH50Reference",
    "IECC2015_5ACH50Reference",
    "IECC2018ERIReference",
    "IECC2018Proposed",
    "IECC2018Reference",
    "IECC2018ReferenceFederalMin",
    "IECC2018_24SF_30MF_CFM50PerSqFtShellReference",
    "IECC2018_4ACH50MultifamilyReference",
    "IECC2018_4ACH50Reference",
    "IECC2018_5ACH50Reference",
    "Illinois2015Proposed",
    "Illinois2015Reference",
    "Illinois2015ReferenceFederalMin",
    "Illinois2018Proposed",
    "Illinois2018Reference",
    "Illinois2018ReferenceFederalMin",
    "Indiana2020Proposed",
    "Indiana2020Reference",
    "Iowa2012Proposed",
    "Iowa2012Reference",
    "LEEDEnergyBudgetProposed",
    "LEEDEnergyBudgetReferencce",
    "Maryland2018Proposed",
    "Maryland2018Reference",
    "MarylandIcfRebateProposed_12_1_20",
    "MarylandIcfRebateReference_12_1_20",
    "MarylandIcfRebateReference_1_1_19",
    "MassSave2016Proposed",
    "MassSave2016Reference",
    "MassSave2017Proposed",
    "MassSave2017Reference",
    "MassSave2019Proposed",
    "MassSave2019Reference",
    "MassSaveRAProposed",
    "MassSaveRAReference",
    "MassSaveRAReference2019",
    "MassSaveRAReference2020",
    "Michigan2015Proposed",
    "Michigan2015Reference",
    "Michigan2015ReferenceFederalMin",
    "MinnesotaMERCRebateReference",
    "MinnesotaRebateProposed",
    "MinnesotaRebateReference",
    "Montana2012Proposed",
    "Montana2012Reference",
    "NGBS2015Proposed",
    "NGBS2015Reference",
    "NGBS2020Proposed",
    "NGBS2020Reference",
    "NYSERDA2016Proposed",
    "NYSERDA2016Reference",
    "Nevada2018Proposed",
    "Nevada2018Reference",
    "NewJerseyCEPProposed",
    "NewJerseyCEPReference",
    "NewYork2016Proposed",
    "NewYork2016Reference",
    "NewYork2020Proposed",
    "NewYork2020Reference",
    "NorthCarolina2012HEROProposed",
    "NorthCarolina2012HEROReference",
    "NorthCarolina2012Proposed",
    "NorthCarolina2012Reference",
    "NorthCarolina2018HEROProposed",
    "NorthCarolina2018HEROReference",
    "NorthCarolina2018Proposed",
    "NorthCarolina2018Reference",
    "Ohio2019Proposed",
    "Ohio2019Reference",
    "OhioAEPRebateReference_7_1_19",
    "OhioColumbiaGasReference",
    "OhioColumbiaGasReference_7_1_19",
    "OhioRebateProposed",
    "OklahomaOGEProposed",
    "OklahomaOGEReference",
    "OklahomaPSORebateProposed_1_1_19",
    "OklahomaPSORebateReference_1_1_19",
    "Penn2016QualificationProposed",
    "Penn2016QualificationReference",
    "Penn2016SavingsProposed",
    "Penn2016SavingsReference",
    "TaxCreditProposed",
    "TaxCreditReference",
    "TaxCreditReferenceNoEnvelopeChanges",
    "Texas2017Baseline",
    "Texas2017Proposed",
    "Texas2018Baseline",
    "Texas2018Proposed",
    "Texas2020Baseline",
    "Texas2020Proposed",
    "TexasICFProposed",
    "TexasICFProposed_3_1_21",
    "TexasICFReference",
    "TexasICFReference_1_1_19",
    "TexasICFReference_3_1_21",
    "UtahDominionThermwiseProposed",
    "UtahDominionThermwiseReference",
    "Virginia2015Proposed",
    "Virginia2015Reference",
    "Virginia2015ReferenceFederalMin",
)

DEFAULT_ANALYSES = [
    ("EkotropeAsModeled", COMPLIANCE_CODES),
    ("HERSReference", None),
    ("HERSRated", None),
    ("EnergyStarV3Reference", None),
    ("EnergyStarV31Reference", None),
    ("EnergyStarV32Reference", None),
    ("IECC2015Reference", None),
    ("IECC2015Proposed", None),
    ("IECC2018Reference", None),
    ("IECC2018Proposed", None),
    ("TaxCreditReference", None),
    ("TaxCreditProposed", None),
    ("NGBS2015Proposed", None),
    ("NGBS2015Reference", None),
    ("EPSNewConstructionOregon2019Proposed", None),
    ("EPSNewConstructionOregon2019Reference", None),
    ("EPSNewConstructionOregonCentral2020Proposed", None),
    ("EPSNewConstructionOregonCentral2020Reference", None),
    ("EPSNewConstructionOregonZonal2020Proposed", None),
    ("EPSNewConstructionOregonZonal2020Reference", None),
    ("EPSNewConstructionOregonCentral2021Proposed", None),
    ("EPSNewConstructionOregonCentral2021Reference", None),
    ("EPSNewConstructionOregonZonal2021Proposed", None),
    ("EPSNewConstructionOregonZonal2021Reference", None),
    ("EPSNewConstructionOregonCentral2022Proposed", None),
    ("EPSNewConstructionOregonCentral2022Reference", None),
    ("EPSNewConstructionOregonZonal2022Proposed", None),
    ("EPSNewConstructionOregonZonal2022Reference", None),
    ("EnergyStarMFV11Reference", None),
    ("EnergyStarMFV1Reference", None),
    ("NGBS2020Proposed", None),
    ("NGBS2020Reference", None),
]


COMPLIANCE_STATUES = (
    "Pass",
    "Fail",
    "NotChecked",
)

ID_PATTERN = re.compile(r"^[A-Za-z0-9]{8}")
ZIP_PATTERN = re.compile(r"^[0-9]{5}")
LOCATION_STATES = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
]
RATING_TYPES = [
    "CONFIRMED",
    "SAMPLED",
]


def validate_id(value):
    return ID_PATTERN.match(value)


def validate_location_state(value):
    return value in LOCATION_STATES


def validate_location_zip(value):
    return ZIP_PATTERN.match(value)


def validate_rating_type(value):
    return value in RATING_TYPES


def validate_foundation_type(value):
    return value in THERMAL_ENVELOPE_FOUNDATION_TYPES


def validate_equipment_type(value):
    return value in MECHANICAL_EQUIPMENT_TYPES


def validate_efficiency_type(value):
    return value in MECHANICAL_EQUIPMENT_EFFICIENCY_TYPES


def validate_fuel_type(value):
    return value in ENERGY_FUEL_TYPES


def validate_component_category(value):
    return value in COMPONENT_CATEGORIES


def validate_compliance_code(value):
    return value in COMPLIANCE_CODES


def validate_compliance_status(value):
    return value in COMPLIANCE_STATUES
