# Generated by Django 1.11.16 on 2018-10-10 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_input_collection", "0001_initial"),
        ("home", "0004_auto_20181011_1933"),
    ]

    operations = [
        migrations.AddField(
            model_name="eepprogramhomestatus",
            name="collection_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_input_collection.CollectionRequest",
            ),
        ),
        migrations.AddField(
            model_name="historicaleepprogramhomestatus",
            name="collection_request",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="django_input_collection.CollectionRequest",
            ),
        ),
    ]
