# Generated by Django 1.11.17 on 2019-05-24 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_auto_20190531_1224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalhomedocument",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalhomedocument",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalhomedocument",
            name="home",
        ),
        migrations.RemoveField(
            model_name="homedocument",
            name="company",
        ),
        migrations.RemoveField(
            model_name="homedocument",
            name="home",
        ),
        migrations.RemoveField(
            model_name="home",
            name="documents",
        ),
        migrations.DeleteModel(
            name="HistoricalHomeDocument",
        ),
        migrations.DeleteModel(
            name="HomeDocument",
        ),
    ]
