# Generated by Django 1.11.17 on 2019-08-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_remove_home_document_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaleepprogramhomestatus",
            name="eep_program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Select the program from the list presented. You may add multiple programs to a home using the "Add new program" button below. You may customize the list of programs presented on the Tasks -> Programs page.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="eep_program.EEPProgram",
                verbose_name="Program",
            ),
        ),
        migrations.AlterField(
            model_name="historicaleepprogramhomestatus",
            name="floorplan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="floorplan.Floorplan",
                verbose_name="Active REM/Rate\u2122 data",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhome",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Type the first few letters of the name of the city the home is located in and select the correct city/state/county combination from the list presented. If the correct city is not available, click "Add New" to add a city to the database.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.City",
                verbose_name="City/State",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhome",
            name="climate_zone",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.ClimateZone",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhome",
            name="county",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.County",
                verbose_name="County",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhome",
            name="geocode_response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The response this place was constructed from.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geocoder.GeocodeResponse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhome",
            name="metro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="geographic.Metro",
                verbose_name="Metro",
            ),
        ),
    ]
