# Generated by Django 1.11.26 on 2020-01-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_validationdata_remove"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalhome",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="subdivision.Subdivision",
                verbose_name="Subdivision",
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subdivision.Subdivision",
                verbose_name="Subdivision",
            ),
        ),
    ]
