# Generated by Django 1.11.26 on 2020-03-11 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0011_auto_20200128_1940"),
    ]

    operations = [
        migrations.AddField(
            model_name="eepprogramhomestatus",
            name="energy_modeler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="energy_modeler_epp_program_home_status_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eepprogramhomestatus",
            name="field_inspectors",
            field=models.ManyToManyField(
                blank=True,
                related_name="field_inspector_epp_program_home_status_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaleepprogramhomestatus",
            name="energy_modeler",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
