# Generated by Django 2.2 on 2020-11-26 18:37

import axis.home.models.home_photo
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_auto_20200311_1141"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.ImageField(
                        upload_to=axis.home.models.home_photo.home_photo_image_upload_to
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "home",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.Home"),
                ),
            ],
        ),
    ]
