# Generated by Django 3.1.3 on 2020-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_homephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalhome",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
    ]
