# Generated by Django 3.1.8 on 2021-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_auto_20210224_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhome",
            name="is_accessory_structure",
            field=models.BooleanField(default=False, verbose_name="Is Accessory Structure"),
        ),
        migrations.AddField(
            model_name="historicalhome",
            name="is_commercial_space",
            field=models.BooleanField(default=False, verbose_name="Is Commercial Space"),
        ),
        migrations.AddField(
            model_name="home",
            name="is_accessory_structure",
            field=models.BooleanField(default=False, verbose_name="Is Accessory Structure"),
        ),
        migrations.AddField(
            model_name="home",
            name="is_commercial_space",
            field=models.BooleanField(default=False, verbose_name="Is Commercial Space"),
        ),
    ]
