# Generated by Django 4.0.7 on 2022-09-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_alter_eepprogramhomestatus_id_alter_home_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="standarddisclosuresettings",
            unique_together=set(),
        ),
    ]
