# Generated by Django 4.0.7 on 2022-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_alter_standarddisclosuresettings_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
