# Generated by Django 4.0.7 on 2022-09-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_alter_eepprogramhomestatus_id_alter_home_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eepprogramhomestatus",
            name="home",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homestatuses",
                to="home.home",
            ),
        ),
    ]
