# Generated by Django 4.0.8 on 2022-12-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_alter_historicalhome_lot_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalhome",
            name="lot_number",
            field=models.CharField(
                blank=True,
                help_text='Enter the lot number of the project (typical for a "production builder" in a subdivision or development of multiple projects), or leave blank or "N/A" if unknown or not applicable.',
                max_length=64,
                null=True,
                verbose_name="Lot number",
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="lot_number",
            field=models.CharField(
                blank=True,
                help_text='Enter the lot number of the project (typical for a "production builder" in a subdivision or development of multiple projects), or leave blank or "N/A" if unknown or not applicable.',
                max_length=64,
                null=True,
                verbose_name="Lot number",
            ),
        ),
    ]
