# Generated by Django 4.1.5 on 2023-02-14 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_alter_historicalhome_lot_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalhome",
            name="is_accessory_structure",
        ),
        migrations.RemoveField(
            model_name="historicalhome",
            name="is_commercial_space",
        ),
        migrations.RemoveField(
            model_name="home",
            name="is_accessory_structure",
        ),
        migrations.RemoveField(
            model_name="home",
            name="is_commercial_space",
        ),
    ]
