# Generated by Django 4.0.7 on 2022-09-14 19:33

from django.db import migrations, models
import django_states.fields


class Migration(migrations.Migration):
    dependencies = [
        ("incentive_payment", "0002_historicalincentivedistribution_history_change_reason_foo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalincentivedistribution",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Incentive Payment",
                "verbose_name_plural": "historical Incentive Payments",
            },
        ),
        migrations.AlterField(
            model_name="historicalincentivedistribution",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalincentivedistribution",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="incentivepaymentstatus",
            name="state",
            field=django_states.fields.StateField(
                default="start", max_length=100, verbose_name="state id"
            ),
        ),
        migrations.AlterField(
            model_name="incentivepaymentstatusstatelog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="incentivepaymentstatusstatelog",
            name="state",
            field=django_states.fields.StateField(
                default="transition_initiated", max_length=100, verbose_name="state id"
            ),
        ),
        migrations.AlterField(
            model_name="ippitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
