__author__ = "Artem Hruzd"
__date__ = "06/19/2020 17:36"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = [
    "Artem Hruzd",
    "Steven Klass",
]

from .utils import (
    PHONE_DIGITS_RE,
    BASE64_CONTENT_PATTERN,
    TEST_FEEDS,
    SELECT2_OPTIONS,
    RANDOM_LETTER_LIKE_UNICODE,
    COMMON_UNICODE,
    LONG_DASHES,
    UNSET,
    TASK_STATE_COLORS,
    random_sequence,
    randomize_filename,
    unrandomize_filename,
    humanize_bytes,
    set_help_text_from_model,
    set_verbose_name_from_model,
    getfirst,
    filter_integers,
    values_to_dict,
    select_queryset_values,
    alias_valuesqueryset,
    collect_nested_object_list,
    slugify_uniquely,
    enforce_order,
    get_generic_fk_data,
    get_task_status,
    get_field_verbose_names,
    clean_base64_encoded_payload,
    get_previous_day_start_end_times,
    get_n_days_range,
    get_current_quarter_range,
    BlockTimer,
    TimeoutError,
    timeout,
    fill_flatten_ea_pdf_template,
    get_user_perm_cache_key,
    delete_user_perm_cache,
    email_html_content_to_text,
    RemoteIdentifiersMixin,
    make_safe_field,
    random_digits,
    random_latitude,
    random_longitude,
    zipdir,
    get_dict_totals,
    has_beta_access,
    query_params_to_dict,
    get_frontend_url,
)
