# Generated by Django 1.11.26 on 2019-12-03 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_auto_20191203_1612"),
    ]

    operations = [
        migrations.RenameField(
            model_name="training",
            old_name="user",
            new_name="trainee",
        ),
    ]
