# Generated by Django 1.11.26 on 2019-12-05 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0005_auto_20191205_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="training_date",
            field=models.DateField(
                default=datetime.datetime(2019, 12, 5, 19, 7, 46, 47353, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="training",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Training name"),
        ),
    ]
