# Generated by Django 1.11.26 on 2019-12-09 14:16

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0006_auto_20191205_1907"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accreditation",
            name="certification_type",
        ),
        migrations.RemoveField(
            model_name="accreditation",
            name="name",
        ),
        migrations.RemoveField(
            model_name="accreditation",
            name="rtin",
        ),
        migrations.AddField(
            model_name="accreditation",
            name="accreditation_cycle",
            field=models.SmallIntegerField(
                choices=[(1, "Annual"), (2, "Every 2 years"), (3, "Every 3 years")], default=1
            ),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="accreditation_id",
            field=models.CharField(default="1", max_length=255, verbose_name="Accreditation ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accreditation",
            name="accreditation_program",
            field=models.CharField(
                default="1", max_length=255, verbose_name="Accreditation Program"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="date_initial",
            field=models.DateField(
                blank=True, null=True, verbose_name="Initial Accreditation Date"
            ),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="date_last",
            field=models.DateField(blank=True, null=True, verbose_name="Last Accreditation Date"),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="role",
            field=models.SmallIntegerField(
                choices=[(1, "Modeler"), (2, "Verifier"), (3, "Rater")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="accreditationstatus",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Inactive"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("probation-new", "Probation \u2013 New"),
                    ("probation-disciplinary", "Probation \u2013 Disciplinary"),
                    ("suspended-administrative", "Suspended \u2013 Administrative"),
                    ("suspended-disciplinary", "Suspended \u2013 Disciplinary"),
                    ("terminated-administrative", "Terminated \u2013 Administrative"),
                    (
                        "terminated-disciplinary(revoked)",
                        "Terminated \u2013 Disciplinary (Revoked)",
                    ),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccreditationstatus",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Inactive"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("probation-new", "Probation \u2013 New"),
                    ("probation-disciplinary", "Probation \u2013 Disciplinary"),
                    ("suspended-administrative", "Suspended \u2013 Administrative"),
                    ("suspended-disciplinary", "Suspended \u2013 Disciplinary"),
                    ("terminated-administrative", "Terminated \u2013 Administrative"),
                    (
                        "terminated-disciplinary(revoked)",
                        "Terminated \u2013 Disciplinary (Revoked)",
                    ),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="address",
            field=models.CharField(
                help_text="Name of company delivering training or conference where training credits were earned",
                max_length=255,
                verbose_name="Training Company or Conference",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="attendance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "In-person"), (2, "Remote"), (3, "ABSENT")],
                default=1,
                verbose_name="Attendance",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="duration",
            field=models.DurationField(verbose_name="Credit Hours"),
        ),
        migrations.AlterField(
            model_name="training",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Training Name"),
        ),
        migrations.AlterField(
            model_name="training",
            name="training_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Voluntary"), (2, "Mandatory")],
                default=1,
                verbose_name="Training Type",
            ),
        ),
    ]
