# Generated by Django 1.11.26 on 2019-12-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0008_auto_20191209_1835"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="duration",
        ),
        migrations.AddField(
            model_name="training",
            name="credit_hours",
            field=models.FloatField(default=1, verbose_name="Credit Hours"),
            preserve_default=False,
        ),
    ]
