# Generated by Django 1.11.26 on 2019-12-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0009_auto_20191210_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificationmetric",
            name="certification_type",
            field=models.SmallIntegerField(
                choices=[(0, "Rating"), (1, "Inspection")],
                default=0,
                verbose_name="Certification Type",
            ),
        ),
        migrations.AlterField(
            model_name="certificationmetric",
            name="date",
            field=models.DateField(verbose_name="Certification Date"),
        ),
        migrations.AlterField(
            model_name="certificationmetric",
            name="grade",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "A"), (2, "B"), (3, "C"), (4, "D"), (5, "F")], default=5
            ),
        ),
    ]
