# Generated by Django 1.11.26 on 2019-12-11 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0011_auto_20191211_1409"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accreditation",
            name="oversight_company",
        ),
    ]
