# Generated by Django 1.11.26 on 2019-12-11 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0012_remove_accreditation_oversight_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accreditation",
            name="approver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accreditation_approvers",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
