# Generated by Django 1.11.26 on 2019-12-12 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_management", "0013_auto_20191211_1645"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="certificationmetricstatus",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="certificationmetricstatus",
            name="approver",
        ),
        migrations.RemoveField(
            model_name="certificationmetricstatus",
            name="certification_metric",
        ),
        migrations.RemoveField(
            model_name="certificationmetricstatus",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalcertificationmetricstatus",
            name="approver",
        ),
        migrations.RemoveField(
            model_name="historicalcertificationmetricstatus",
            name="certification_metric",
        ),
        migrations.RemoveField(
            model_name="historicalcertificationmetricstatus",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalcertificationmetricstatus",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="certificationmetric",
            name="statuses",
        ),
        migrations.AddField(
            model_name="certificationmetric",
            name="approver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certification_metric_approvers",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="accreditation_cycle",
            field=models.SmallIntegerField(
                choices=[(1, "Annual"), (2, "Every 2 years"), (3, "Every 3 years")],
                default=1,
                verbose_name="Accreditation Cycle",
            ),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="state",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Inactive"),
                    (2, "Active"),
                    (3, "Probation \u2013 New"),
                    (4, "Probation \u2013 Disciplinary"),
                    (5, "Suspended \u2013 Administrative"),
                    (6, "Suspended \u2013 Disciplinary"),
                    (7, "Terminated \u2013 Administrative"),
                    (8, "Terminated \u2013 Disciplinary (Revoked)"),
                ],
                default=1,
                verbose_name="Accreditation Status",
            ),
        ),
        migrations.DeleteModel(
            name="CertificationMetricStatus",
        ),
        migrations.DeleteModel(
            name="HistoricalCertificationMetricStatus",
        ),
    ]
