# Generated by Django 1.11.26 on 2019-12-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0014_auto_20191212_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificationmetric",
            name="certification_type",
            field=models.SmallIntegerField(
                choices=[(1, "Rating"), (2, "Inspection")],
                default=1,
                verbose_name="Certification Type",
            ),
        ),
    ]
