# Generated by Django 1.11.26 on 2020-02-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0018_auto_20191218_1527"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="certificate",
            field=models.FileField(
                blank=True, null=True, upload_to=b"", verbose_name="Certificate"
            ),
        ),
    ]
