# Generated by Django 1.11.26 on 2020-02-13 07:05

from django.apps import apps
from django.db import migrations, models
import django.db.models.deletion

user_management_app = apps.get_app_config("user_management")


def link_eep_programs(apps, schema_editor):
    eep_program_class = apps.get_model("eep_program", "EEPProgram")
    accreditation_class = apps.get_model("user_management", "Accreditation")
    for accreditation in accreditation_class.objects.all():
        applicable_programs = user_management_app.ACCREDITATION_APPLICABLE_REQUIREMENTS.get(
            accreditation.approver.company.slug
        )
        # populate with random program from config or
        # if company already removed from it pick a random eep_program
        if applicable_programs:
            eep_program = eep_program_class.objects.filter(slug__in=applicable_programs).first()
        else:
            eep_program = eep_program_class.objects.first()
        accreditation.eep_program = eep_program
        accreditation.save()


def reverse_to_accreditation_program_name(apps, schema_editor):
    accreditation_class = apps.get_model("user_management", "Accreditation")
    for accreditation in accreditation_class.objects.all():
        accreditation.accreditation_program = "unknown"
        accreditation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0020_auto_20200213_0704"),
    ]

    operations = [
        migrations.AddField(
            model_name="accreditation",
            name="eep_program",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="eep_program.EEPProgram"
            ),
        ),
        migrations.RunPython(link_eep_programs, reverse_to_accreditation_program_name),
    ]
