# Generated by Django 1.11.26 on 2020-02-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0021_transfer_accreditation_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrainingstatus",
            name="state_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingstatus",
            name="state_note",
            field=models.TextField(blank=True),
        ),
    ]
