# Generated by Django 1.11.26 on 2020-02-13 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0022_auto_20200213_1609"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltrainingstatus",
            old_name="state_note",
            new_name="state_notes",
        ),
        migrations.RenameField(
            model_name="trainingstatus",
            old_name="state_note",
            new_name="state_notes",
        ),
    ]
