# Generated by Django 1.11.26 on 2020-02-18 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0023_auto_20200213_1613"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificationmetric",
            name="approver",
        ),
        migrations.RemoveField(
            model_name="certificationmetric",
            name="user",
        ),
        migrations.DeleteModel(
            name="CertificationMetric",
        ),
    ]
