# Generated by Django 1.11.26 on 2020-04-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user_management", "0024_auto_20200218_0634"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectiongrade",
            name="grade",
        ),
        migrations.AddField(
            model_name="inspectiongrade",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="inspectiongrade",
            name="letter_grade",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "A"), (2, "B"), (3, "C"), (4, "D"), (5, "F")], null=True
            ),
        ),
        migrations.AddField(
            model_name="inspectiongrade",
            name="numeric_grade",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="inspectiongrade",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
