# Generated by Django 1.11.26 on 2020-04-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0025_auto_20200401_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectiongrade",
            name="qa_status",
            field=models.CharField(
                blank=True,
                help_text="This field is populating when task is using QAStatus model as content type object",
                max_length=255,
            ),
        ),
    ]
