# Generated by Django 1.11.26 on 2020-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0027_auto_20200415_1540"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accreditation",
            name="role",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Energy Modeler"),
                    (2, "Verifier"),
                    (3, "Rater/Verifier"),
                    (4, "Rating Field Inspector"),
                    (5, "QA Designee"),
                ],
                default=1,
            ),
        ),
    ]
