# Generated by Django 1.11.26 on 2020-07-13 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0028_auto_20200506_1654"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accreditation",
            options={"ordering": ("-date_initial",)},
        ),
        migrations.AlterModelOptions(
            name="inspectiongrade",
            options={"ordering": ("-graded_date",)},
        ),
        migrations.AlterModelOptions(
            name="training",
            options={"ordering": ("-training_date",)},
        ),
    ]
