# Generated by Django 1.11.26 on 2020-07-14 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0029_auto_20200713_2005"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accreditation",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="inspectiongrade",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="training",
            options={"ordering": ("-created_at",)},
        ),
    ]
