# Generated by Django 2.2 on 2020-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0031_auto_20201016_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="accreditation",
            name="name",
            field=models.CharField(
                choices=[
                    ("ngbs-2020", "NGBS 2020"),
                    ("ngbs-2015", "NGBS 2015"),
                    ("ngbs-2012", "NGBS 2012"),
                ],
                default="ngbs-2020",
                max_length=45,
            ),
            preserve_default=False,
        ),
    ]
