# Generated by Django 2.2 on 2020-12-15 18:36

from django.db import migrations


def group_eep_programs(apps, schema_editor):
    accreditation_class = apps.get_model("user_management", "Accreditation")
    accreditations = accreditation_class.objects.all()

    accreditation_program_requirements = {
        "ngbs-sf-new-construction-2020-new": "ngbs-2020",
        "ngbs-mf-new-construction-2020-new": "ngbs-2020",
        "ngbs-sf-whole-house-remodel-2020-new": "ngbs-2020",
        "ngbs-mf-whole-house-remodel-2020-new": "ngbs-2020",
        "ngbs-sf-certified-2020-new": "ngbs-2020",
        "ngbs-sf-new-construction-2015-new": "ngbs-2015",
        "ngbs-mf-new-construction-2015-new": "ngbs-2015",
        "ngbs-sf-whole-house-remodel-2015-new": "ngbs-2015",
        "ngbs-mf-whole-house-remodel-2015-new": "ngbs-2015",
        "ngbs-sf-new-construction-2012-new": "ngbs-2012",
        "ngbs-mf-new-construction-2012-new": "ngbs-2012",
        "ngbs-sf-whole-house-remodel-2012-new": "ngbs-2012",
        "ngbs-mf-whole-house-remodel-2012-new": "ngbs-2012",
    }

    for accreditation in accreditations:
        program_requirements = accreditation_program_requirements.get(
            accreditation.eep_program.slug
        )
        if program_requirements:
            accreditation.name = program_requirements
            accreditation.save()
            print(f"{accreditation.eep_program.name} -> {program_requirements}")


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0032_accreditation_name"),
    ]

    operations = [
        migrations.RunPython(group_eep_programs, reverse_code),
    ]
