# Generated by Django 2.2 on 2020-12-15 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0033_auto_20201215_1836"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accreditation",
            name="eep_program",
        ),
    ]
