# Generated by Django 3.1.6 on 2021-02-24 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0034_remove_accreditation_eep_program"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspectiongrade",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Verification Grade",
                "verbose_name_plural": "Verification Grades",
            },
        ),
    ]
