# Generated by Django 3.1.9 on 2021-06-10 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0035_auto_20210224_1038"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectiongrade",
            name="performed_date",
        ),
    ]
