# Generated by Django 3.2.7 on 2021-09-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0036_remove_inspectiongrade_performed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="accreditation",
            name="manual_expiration_date",
            field=models.DateField(
                blank=True,
                help_text='If not set then expiration date will be calculated automatically based on "Last Accreditation Date" and "Accreditation Cycle"',
                null=True,
                verbose_name="Accreditation Expiration",
            ),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrainingstatus",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inspectiongrade",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trainingstatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
