# Generated by Django 3.2.10 on 2022-01-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0041_alter_accreditation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accreditation",
            name="date_last",
            field=models.DateField(
                blank=True, null=True, verbose_name="Most Recent Accreditation Date"
            ),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="manual_expiration_date",
            field=models.DateField(
                blank=True,
                help_text='If not set then expiration date will be calculated automatically based on "Most Recent Accreditation Date" and "Accreditation Cycle"',
                null=True,
                verbose_name="Accreditation Expiration",
            ),
        ),
    ]
