# Generated by Django 3.2.12 on 2022-02-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0015_auto_20220214_2224"),
        ("user_management", "0042_auto_20220128_0944"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="inspectiongrade",
        #     name="qa_status",
        #     field=models.CharField(
        #         blank=True,
        #         help_text="This field is populating when task is using QAStatus model as content type object",
        #         max_length=255,
        #     ),
        # ),
        migrations.RemoveField(
            model_name="inspectiongrade",
            name="qa_status",
        ),
    ]
