# Generated by Django 3.2.12 on 2022-02-14 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0015_auto_20220214_2224"),
        ("user_management", "0043_alter_inspectiongrade_qa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectiongrade",
            name="qa_status",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.qastatus",
            ),
        )
    ]
