# Generated by Django 3.2.12 on 2022-02-15 12:18

from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def move_content_type_qa_to_fk(apps, schema_editor):
    qa_status_class = apps.get_model("qa", "QAStatus")
    inspection_grade_class = apps.get_model("user_management", "InspectionGrade")
    ct = ContentType.objects.get_for_model(qa_status_class)
    for inspection_grade in inspection_grade_class.objects.filter(content_type__pk=ct.id):
        try:
            qa_status = qa_status_class.objects.get(id=inspection_grade.object_id)
        except Exception:
            print(f"Error for: {inspection_grade.id}")
            continue
        try:
            inspection_grade.qa_status = qa_status
            inspection_grade.save()
        except Exception:
            print(f"Error for: {inspection_grade.id} {qa_status}")
            continue


def reverse_move_content_type(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0044_inspectiongrade_qa_status"),
    ]

    operations = [
        migrations.RunPython(move_content_type_qa_to_fk, reverse_code=reverse_move_content_type),
    ]
