# Generated by Django 3.2.12 on 2022-02-22 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0045_auto_20220215_1218"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectiongrade",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="inspectiongrade",
            name="object_id",
        ),
    ]
