# Generated by Django 4.0.7 on 2022-09-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0046_auto_20220222_1055"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaltrainingstatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical training status",
                "verbose_name_plural": "historical training statuss",
            },
        ),
        migrations.AlterField(
            model_name="historicaltrainingstatus",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
