# Generated by Django 4.2 on 2023-04-24 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qa", "0020_remove_historicalqastatus_hirl_land_development_certification_level_and_more"),
        ("user_management", "0047_alter_historicaltrainingstatus_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTraining",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Training Name")),
                (
                    "address",
                    models.CharField(
                        help_text="Name of company delivering training or conference where training credits were earned",
                        max_length=255,
                        verbose_name="Training Company or Conference",
                    ),
                ),
                ("training_date", models.DateField()),
                (
                    "training_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Voluntary"), (2, "Mandatory")],
                        default=1,
                        verbose_name="Training Type",
                    ),
                ),
                (
                    "attendance_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "In-person"), (2, "Remote"), (3, "ABSENT")],
                        default=1,
                        verbose_name="Attendance",
                    ),
                ),
                (
                    "certificate",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Certificate"
                    ),
                ),
                ("credit_hours", models.FloatField(verbose_name="Credit Hours")),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical training",
                "verbose_name_plural": "historical trainings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInspectionGrade",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("graded_date", models.DateField()),
                (
                    "letter_grade",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "A"), (2, "B"), (3, "C"), (4, "D"), (5, "F")], null=True
                    ),
                ),
                ("numeric_grade", models.PositiveIntegerField(null=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qa_status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="qa.qastatus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Verification Grade",
                "verbose_name_plural": "historical Verification Grades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAccreditation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ngbs-2020", "NGBS 2020"),
                            ("ngbs-2015", "NGBS 2015"),
                            ("ngbs-2012", "NGBS 2012"),
                            ("master-verifier", "NGBS Master Verifier"),
                            ("ngbs-wri-verifier", "NGBS WRI Verifier"),
                            ("ngbs-green-field-rep", "NGBS Green Field Rep"),
                        ],
                        max_length=45,
                    ),
                ),
                (
                    "accreditation_id",
                    models.CharField(max_length=255, verbose_name="Accreditation ID"),
                ),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Energy Modeler"),
                            (2, "Verifier"),
                            (3, "Rater/Verifier"),
                            (4, "Rating Field Inspector"),
                            (5, "QA Designee"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Inactive"),
                            (2, "Active"),
                            (3, "Probation – New"),
                            (4, "Probation – Disciplinary"),
                            (5, "Suspended – Administrative"),
                            (6, "Suspended – Disciplinary"),
                            (7, "Terminated – Administrative"),
                            (8, "Terminated – Disciplinary (Revoked)"),
                        ],
                        default=1,
                        verbose_name="Accreditation Status",
                    ),
                ),
                ("state_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accreditation_cycle",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Annual"),
                            (2, "Every 2 years"),
                            (3, "Every 3 years"),
                            (4, "Every 4 years"),
                        ],
                        default=1,
                        verbose_name="Accreditation Cycle",
                    ),
                ),
                (
                    "date_initial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Initial Accreditation Date"
                    ),
                ),
                (
                    "date_last",
                    models.DateField(
                        blank=True, null=True, verbose_name="Most Recent Accreditation Date"
                    ),
                ),
                (
                    "manual_expiration_date",
                    models.DateField(
                        blank=True,
                        help_text='If not set then expiration date will be calculated automatically based on "Most Recent Accreditation Date" and "Accreditation Cycle"',
                        null=True,
                        verbose_name="Accreditation Expiration",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who approved this accreditation",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical accreditation",
                "verbose_name_plural": "historical accreditations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
