# Generated by Django 1.11.16 on 2018-12-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0002_historicalsimulation_history_change_reason_foo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotwaterdistribution",
            name="recirculation_type",
            field=models.IntegerField(
                choices=[
                    (1, "None (standard system)"),
                    (2, "Timer or Uncontroled"),
                    (3, "Temperature control"),
                    (4, "Demand (presence sensor)"),
                    (5, "Demand (manual"),
                ],
                db_column="nRecircType",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sampleset_id",
            field=models.CharField(blank=True, db_column="SPISAMSETID", max_length=93, null=True),
        ),
    ]
