# Generated by Django 1.11.17 on 2019-01-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0003_auto_20181211_0254"),
    ]

    operations = [
        migrations.AddField(
            model_name="economicparameters",
            name="calculation_methodology",
            field=models.IntegerField(db_column="NEPCalcMthd", null=True),
        ),
        migrations.AddField(
            model_name="infiltration",
            name="multi_family_good_air_exchange",
            field=models.IntegerField(blank=True, db_column="NINGDAIRXMF", null=True),
        ),
        migrations.AddField(
            model_name="mandatoryrequirements",
            name="energy_star_mf_clothes_dryer_no_ES_option",
            field=models.IntegerField(blank=True, db_column="NMRESMFDRYR", null=True),
        ),
        migrations.AddField(
            model_name="mandatoryrequirements",
            name="energy_star_mf_clothes_washer_no_ES_option",
            field=models.IntegerField(blank=True, db_column="NMRESMFWSHR", null=True),
        ),
        migrations.AddField(
            model_name="mandatoryrequirements",
            name="energy_star_mf_uses_class_aw_windows",
            field=models.IntegerField(blank=True, db_column="NMRESMFWIN", null=True),
        ),
        migrations.AddField(
            model_name="mandatoryrequirements",
            name="verified_iecc18_nc",
            field=models.BooleanField(null=True, db_column="NMRIECCNC"),
        ),
        migrations.AddField(
            model_name="project",
            name="rating_permit_date",
            field=models.CharField(blank=True, db_column="sPIPrmtDate", max_length=32, null=True),
        ),
    ]
