# Generated by Django 1.11.17 on 2019-03-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0004_remrate_15p7p2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildinginfo",
            name="thermal_boundary",
            field=models.IntegerField(
                choices=[(0, "N/A"), (1, "Floor"), (2, "Foundation Wall"), (3, "REM Default")],
                db_column="nBIThBndry",
                null=True,
            ),
        ),
    ]
