# Generated by Django 1.11.17 on 2019-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0005_auto_20190305_1935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lightsandappliance",
            name="clothes_washer_efficiency",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "RESNET Default"),
                    (2, "Med Efficiency"),
                    (3, "High Efficiency"),
                    (4, "ENERGY STAR"),
                    (5, "ENERGY STAR 2018"),
                ],
                db_column="FLAWASHEFF",
                null=True,
            ),
        ),
    ]
