# Generated by Django 1.11.17 on 2019-07-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0008_remrate_15p8"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ductsystem",
            name="leakage_test_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Both Tested"), (2, "Leakage to Outside"), (3, "Total Duct Leakage")],
                db_column="nDSTestType",
                help_text="DuctTestType",
                null=True,
            ),
        ),
    ]
