# Generated by Django 1.11.26 on 2020-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0010_auto_20200128_1939"),
    ]

    operations = [
        migrations.AddField(
            model_name="ductsystem",
            name="distribution_system_efficiency",
            field=models.FloatField(blank=True, db_column="fDSDSE", null=True),
        ),
        migrations.AddField(
            model_name="hers",
            name="worst_case_orientation",
            field=models.IntegerField(
                blank=True,
                db_column="NBADORIENT",
                null=True,
                verbose_name="Worse orientation (0, 90, 180, 270) -1 is indeterminate",
            ),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc18_design_mv_cost",
            field=models.FloatField(blank=True, db_column="f18IEDMVCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc18_reference_mv_cost",
            field=models.FloatField(blank=True, db_column="f18IERMVCT", null=True),
        ),
        migrations.AddField(
            model_name="installedequipment",
            name="distribution_system_efficiency",
            field=models.FloatField(blank=True, db_column="fEIDSE", null=True),
        ),
    ]
