# Generated by Django 1.11.26 on 2020-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0011_remrate_16p0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abovegradewall",
            name="color",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Light"),
                    (2, "Medium"),
                    (3, "Dark"),
                    (4, "Reflective"),
                    (5, "Std140"),
                    (6, "Std140-lowAbs"),
                ],
                db_column="nAGCol",
            ),
        ),
        migrations.AlterField(
            model_name="floortype",
            name="floor_covering",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Carpet"),
                    (2, "Tile"),
                    (3, "Hardwood"),
                    (4, "Vinyl"),
                    (5, "Rigid R-3 Insul"),
                    (6, "CodeRef Carpet"),
                ],
                db_column="nFTCovType",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roof",
            name="color",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Light"),
                    (2, "Medium"),
                    (3, "Dark"),
                    (4, "Reflective"),
                    (5, "Std140"),
                    (6, "Std140-lowAbs"),
                ],
                db_column="nROCol",
            ),
        ),
        migrations.AlterField(
            model_name="slabtype",
            name="floor_covering",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Carpet"),
                    (2, "Tile"),
                    (3, "Hardwood"),
                    (4, "Vinyl"),
                    (5, "Rigid R-3 Insul"),
                    (6, "CodeRef Carpet"),
                ],
                db_column="nSTFlrCvr",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walltype",
            name="construction_type",
            field=models.FloatField(
                choices=[
                    (1, "Standard Wood Frame"),
                    (2, "Double Stud Wood Frame"),
                    (7, "Standard Steel Frame"),
                    (3, "Std Frame w/Brick Veneer"),
                    (4, "Solid Concrete or Stone"),
                    (5, "Double Brick"),
                    (6, "Hollow-Core Concrete Block"),
                    (8, "Structual Insulated Panel"),
                    (9, "Insulated Concrete Form"),
                    (10, "Adobe"),
                ],
                db_column="nWTCntnTyp",
                default=0,
            ),
        ),
    ]
