# Generated by Django 3.1.3 on 2020-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0013_auto_20200713_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildinginfo",
            name="foundation_within_infiltration_volume",
            field=models.BooleanField(
                blank=True,
                db_column="NBIINFLTVOL",
                help_text="Is Foundation in Infilt Volume",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="pass_energy_star_v3HI",
            field=models.BooleanField(blank=True, db_column="bESTARV3HI", null=True),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="pass_energy_star_v3p1",
            field=models.BooleanField(blank=True, db_column="bESTARV31", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_appliance_requirements",
            field=models.BooleanField(blank=True, db_column="nDCAppl", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_duct_location_requirements",
            field=models.BooleanField(blank=True, db_column="nDCDuctLoc", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_fan_efficiency_requirements",
            field=models.BooleanField(blank=True, db_column="nDCFanEff", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_indoor_air_quality_requirements",
            field=models.BooleanField(blank=True, db_column="nDCAirQual", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_insulation_requirements",
            field=models.BooleanField(blank=True, db_column="nDCInsul", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_lighting_requirements",
            field=models.BooleanField(blank=True, db_column="nDCLighting", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_fenestration_requirements",
            field=models.BooleanField(blank=True, db_column="nDCFenstrtn", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_renewable_solar_electric_requirements",
            field=models.BooleanField(blank=True, db_column="nDCSolarE", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_renewable_solar_hot_water_requirements",
            field=models.BooleanField(blank=True, db_column="nDCSolarHW", null=True),
        ),
        migrations.AlterField(
            model_name="doechallenge",
            name="verified_water_efficiency",
            field=models.BooleanField(blank=True, db_column="nDCWaterEff", null=True),
        ),
        migrations.AlterField(
            model_name="ductsystem",
            name="energy_star_test_exemption",
            field=models.BooleanField(
                blank=True, db_column="nDSESTAREx", help_text="ENERGY STAR LtO", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ductsystem",
            name="iecc_test_exemption",
            field=models.BooleanField(
                blank=True, db_column="nDSIECCEx", help_text="IECC", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ductsystem",
            name="no_building_cavities_used_as_ducts",
            field=models.BooleanField(
                blank=True,
                db_column="nDSIsDucted",
                help_text="No Building cavities used as ducts",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ductsystem",
            name="resnet_test_exemption",
            field=models.BooleanField(
                blank=True, db_column="nDSRESNETEx", help_text="RESNET 2019", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energystar",
            name="passes_energy_star_v1p0_mf",
            field=models.BooleanField(
                blank=True,
                db_column="bESTARV10MF",
                null=True,
                verbose_name="Meets Energy Star v1.0 Multi-Family NC",
            ),
        ),
        migrations.AlterField(
            model_name="energystar",
            name="passes_energy_star_v1p1_mf",
            field=models.BooleanField(
                blank=True,
                db_column="BESTARV11MF",
                null=True,
                verbose_name="Meets Energy Star v1.1 Multi-Family NC",
            ),
        ),
        migrations.AlterField(
            model_name="energystar",
            name="passes_energy_star_v1p2_mf",
            field=models.BooleanField(
                blank=True,
                db_column="BESTARV12MF",
                null=True,
                verbose_name="Meets Energy Star v1.2 Multi-Family NC",
            ),
        ),
        migrations.AlterField(
            model_name="iecc",
            name="passes_iecc15_consumption_compliance",
            field=models.BooleanField(blank=True, db_column="b15IECC", null=True),
        ),
        migrations.AlterField(
            model_name="iecc",
            name="passes_iecc15_ducts_overall_u0",
            field=models.BooleanField(blank=True, db_column="b15IECCDuP", null=True),
        ),
        migrations.AlterField(
            model_name="iecc",
            name="passes_iecc15_overall_ua_compliance",
            field=models.BooleanField(blank=True, db_column="b15IECCuAP", null=True),
        ),
        migrations.AlterField(
            model_name="iecc",
            name="passes_iecc18_consumption_compliance",
            field=models.BooleanField(blank=True, db_column="b18IECC", null=True),
        ),
        migrations.AlterField(
            model_name="iecc",
            name="passes_iecc18_ducts_overall_u0",
            field=models.BooleanField(blank=True, db_column="b18IECCDuP", null=True),
        ),
        migrations.AlterField(
            model_name="iecc",
            name="passes_iecc18_overall_ua_compliance",
            field=models.BooleanField(blank=True, db_column="b18IECCuAP", null=True),
        ),
        migrations.AlterField(
            model_name="infiltration",
            name="no_mechanical_vent_measured",
            field=models.BooleanField(
                blank=True, db_column="NINNOMVMSRD", null=True, verbose_name="No Mech Vent Measured"
            ),
        ),
        migrations.AlterField(
            model_name="infiltration",
            name="use_fan_watts_defaults",
            field=models.BooleanField(
                blank=True,
                db_column="NINWATTDFLT",
                null=True,
                verbose_name="Fan Watts Use Defaults",
            ),
        ),
        migrations.AlterField(
            model_name="mandatoryrequirements",
            name="verified_iecc15",
            field=models.BooleanField(blank=True, db_column="NMRIECC15", null=True),
        ),
        migrations.AlterField(
            model_name="mandatoryrequirements",
            name="verified_iecc15_mi",
            field=models.BooleanField(blank=True, db_column="NMRIECCMI", null=True),
        ),
        migrations.AlterField(
            model_name="mandatoryrequirements",
            name="verified_iecc18",
            field=models.BooleanField(blank=True, db_column="NMRIECC18", null=True),
        ),
        migrations.AlterField(
            model_name="mandatoryrequirements",
            name="verified_iecc18_nc",
            field=models.BooleanField(blank=True, db_column="NMRIECCNC", null=True),
        ),
        migrations.AlterField(
            model_name="regionalcode",
            name="ny_eccc_2016_passing_ducts",
            field=models.BooleanField(blank=True, db_column="BNYDCTPASS", default=False, null=True),
        ),
        migrations.AlterField(
            model_name="regionalcode",
            name="passes_ny_eccc_2016_code",
            field=models.BooleanField(blank=True, db_column="BNYPASS", default=False, null=True),
        ),
        migrations.AlterField(
            model_name="regionalcode",
            name="passes_ny_eccc_2016_cost_compliance",
            field=models.BooleanField(blank=True, db_column="BNYMEETCT", default=False, null=True),
        ),
        migrations.AlterField(
            model_name="regionalcode",
            name="passes_ny_eccc_2016_overall_ua_compliance",
            field=models.BooleanField(blank=True, db_column="BNYUAPASS", default=False, null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_1",
            field=models.BooleanField(blank=True, db_column="nRDQ1", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_2a",
            field=models.BooleanField(blank=True, db_column="nRDQ2A", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_2b",
            field=models.BooleanField(blank=True, db_column="nRDQ2B", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_2c",
            field=models.BooleanField(blank=True, db_column="nRDQ2C", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_2d",
            field=models.BooleanField(blank=True, db_column="nRDQ2D", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_2e",
            field=models.BooleanField(blank=True, db_column="nRDQ2E", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_3a",
            field=models.BooleanField(blank=True, db_column="nRDQ3A", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_3b",
            field=models.BooleanField(blank=True, db_column="nRDQ3B", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_3c",
            field=models.BooleanField(blank=True, db_column="nRDQ3C", null=True),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="question_5_sampling",
            field=models.BooleanField(blank=True, db_column="NRDQ5", default=False, null=True),
        ),
    ]
