# Generated by Django 3.2.5 on 2021-07-23 19:10
import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0016_remrate_16p1"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedequipment",
            name="ground_source_heat_pump",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="remrate_data.groundsourceheatpump",
            ),
        ),
        migrations.AddField(
            model_name="sharedequipment",
            name="water_loop_heat_pump",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="remrate_data.waterloopheatpump",
            ),
        ),
        migrations.AlterField(
            model_name="sharedequipment",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="remrate_data.simulation"
            ),
        ),
        migrations.AlterField(
            model_name="ventilation",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="remrate_data.simulation"
            ),
        ),
        migrations.AlterField(
            model_name="waterloopheatpump",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="remrate_data.simulation"
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="co2_hers_emission_savings",
            field=models.FloatField(
                db_column="FEMHERSCO2",
                null=True,
                verbose_name="HERS Emission Savings - Carbon Dioxide (Not in REM/Design)",
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="nox_hers_emission_savings",
            field=models.FloatField(
                db_column="FEMHERSNOX",
                null=True,
                verbose_name="HERSEmission Savings - Nitrogen Oxides (Not in REM/Design)",
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="so2_hers_emission_savings",
            field=models.FloatField(
                db_column="FEMHERSSO2",
                null=True,
                verbose_name="HERS Emission Savings - Sulfur Dioxide (Not in REM/Design)",
            ),
        ),
        migrations.AlterField(
            model_name="framefloor",
            name="location",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (201, "Between conditioned space and ambient conditions"),
                    (202, "Between conditioned space and garage"),
                    (203, "Between conditioned space and open crawl space"),
                    (205, "Between conditioned space and unconditioned basement"),
                    (206, "Between conditioned space and enclosed crawl space"),
                    (213, "Between conditioned space and another (adiabatic)"),
                ],
                db_column="nFFLoc",
            ),
        ),
        migrations.AlterField(
            model_name="installedequipment",
            name="location",
            field=models.IntegerField(
                choices=[
                    (1, "Conditioned area"),
                    (6, "Conditioned Crawlspace"),
                    (2, "Uncond bsmnt/enclosed crawl"),
                    (3, "Garage or open crawl space"),
                    (4, "Vented Attic"),
                    (7, "Sealed Attic"),
                    (5, "Ambient"),
                    (8, "Garage"),
                    (9, "MF unrated conditioned"),
                    (10, "MF unrated heated"),
                    (11, "MF buffer space"),
                    (12, "MF nonfreezing space"),
                    (0, "None"),
                ],
                db_column="nEILoc",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="installedequipment",
            name="system_type",
            field=models.IntegerField(
                choices=[
                    (1, "Space Heating"),
                    (2, "Space Cooling"),
                    (3, "Water Heating"),
                    (4, "Air-Source Heat Pump"),
                    (5, "Ground Source Heat Pump"),
                    (6, "Dual Fuel Heat Pump"),
                    (7, "Integrated Space/Water Heating"),
                    (8, "Shared Equipment"),
                    (9, "Dehumidifier Equipment"),
                ],
                db_column="nEISysType",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="installedlightsandappliances",
            name="location",
            field=models.IntegerField(
                choices=[
                    (1, "Conditioned area"),
                    (6, "Conditioned Crawlspace"),
                    (2, "Uncond bsmnt/enclosed crawl"),
                    (3, "Garage or open crawl space"),
                    (4, "Vented Attic"),
                    (7, "Sealed Attic"),
                    (5, "Ambient"),
                    (8, "Garage"),
                    (9, "MF unrated conditioned"),
                    (10, "MF unrated heated"),
                    (11, "MF buffer space"),
                    (12, "MF nonfreezing space"),
                    (0, "None"),
                ],
                db_column="NLAILOC",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsimulation",
            name="simulation_date",
            field=models.DateTimeField(
                db_column="sBRDate",
                default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc),
                max_length=93,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="simulation_date",
            field=models.DateTimeField(
                db_column="sBRDate",
                default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc),
                max_length=93,
                null=True,
            ),
        ),
    ]
