# Generated by Django 3.2.5 on 2021-07-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0017_auto_20210723_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatracker",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="remrate_data.building",
            ),
        ),
    ]
