# Generated by Django 3.2.13 on 2022-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0020_remrate_16p3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infiltration",
            name="hours_per_day",
            field=models.FloatField(db_column="nINHrsDay", null=True),
        ),
    ]
