# Generated by Django 4.0.7 on 2022-09-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0022_auto_20220720_2313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceilingtype",
            name="simulation",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="remrate_data.simulation"
            ),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="building",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="remrate_data.building"
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="similar",
            field=models.ManyToManyField(to="remrate_data.simulation"),
        ),
        migrations.AlterField(
            model_name="solarsystem",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="remrate_data.building"
            ),
        ),
        migrations.AlterField(
            model_name="solarsystem",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="remrate_data.simulation"
            ),
        ),
    ]
