# Generated by Django 4.0.7 on 2022-09-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0023_alter_ceilingtype_simulation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceilingtype",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="remrate_data.simulation"
            ),
        ),
        migrations.AlterField(
            model_name="resnetdisc",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="remrate_data.building"
            ),
        ),
    ]
