# Generated by Django 4.0.8 on 2022-10-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0025_alter_solarsystem_building_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildinginfo",
            name="total_number_of_stories",
            field=models.IntegerField(db_column="nBITotalStories", null=True),
        ),
    ]
