# Generated by Django 4.0.8 on 2022-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0026_buildinginfo_total_number_of_stories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infiltration",
            name="hours_per_day",
            field=models.IntegerField(db_column="nINHrsDay", null=True),
        ),
    ]
