# Generated by Django 4.1.7 on 2023-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remrate_data", "0027_alter_infiltration_hours_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotwaterdistribution",
            name="compactness_factor",
            field=models.FloatField(blank=True, db_column="fCompactFactor", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_cooling_cost",
            field=models.FloatField(blank=True, db_column="f21IEDCCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_heating_cost",
            field=models.FloatField(blank=True, db_column="f21IEDHCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_hot_water_cost",
            field=models.FloatField(blank=True, db_column="f21IEDDCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_lights_appliance_cost",
            field=models.FloatField(blank=True, db_column="f21IEDLACT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_mv_cost",
            field=models.FloatField(blank=True, db_column="f21IEDMVCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_overall_u0",
            field=models.FloatField(blank=True, db_column="f21IECCDUA", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_photo_voltaic_cost",
            field=models.FloatField(blank=True, db_column="f21IEDPVCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_service_cost",
            field=models.FloatField(blank=True, db_column="f21IEDSVCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_designed_total_cost",
            field=models.FloatField(blank=True, db_column="f21IEDTCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_cooling_cost",
            field=models.FloatField(blank=True, db_column="f21IERCCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_heating_cost",
            field=models.FloatField(blank=True, db_column="f21IERHCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_hot_water_cost",
            field=models.FloatField(blank=True, db_column="f21IERDCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_lights_appliance_cost",
            field=models.FloatField(blank=True, db_column="f21IERLACT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_mv_cost",
            field=models.FloatField(blank=True, db_column="f21IERMVCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_overall_u0",
            field=models.FloatField(blank=True, db_column="f21IECCRUA", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_photo_voltaic_cost",
            field=models.FloatField(blank=True, db_column="f21IERPVCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_service_cost",
            field=models.FloatField(blank=True, db_column="f21IERSVCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="iecc21_reference_total_cost",
            field=models.FloatField(blank=True, db_column="f21IERTCT", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="passes_iecc21_code",
            field=models.BooleanField(db_column="bPass21IECC", default=False, null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="passes_iecc21_consumption_compliance",
            field=models.BooleanField(blank=True, db_column="b21IECC", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="passes_iecc21_ducts_overall_u0",
            field=models.BooleanField(blank=True, db_column="b21IECCDuP", null=True),
        ),
        migrations.AddField(
            model_name="iecc",
            name="passes_iecc21_overall_ua_compliance",
            field=models.BooleanField(blank=True, db_column="b21IECCuAP", null=True),
        ),
        migrations.AddField(
            model_name="mandatoryrequirements",
            name="verified_iecc21",
            field=models.BooleanField(blank=True, db_column="NMRIECC21", null=True),
        ),
    ]
