# Generated by Django 3.1.6 on 2021-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0003_auto_20210304_2215"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoiceitem",
            name="protected",
            field=models.BooleanField(
                default=False, help_text="Item can not be edited by User after creation"
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="protected",
            field=models.BooleanField(
                default=False, help_text="Item can not be edited by User after creation"
            ),
        ),
    ]
