# Generated by Django 3.2.4 on 2021-06-26 20:02

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0007_auto_20210626_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoice",
            name="id",
            field=models.IntegerField(blank=True, db_index=True, default=100000),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                default=100000,
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemtransaction",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="invoicing.invoiceitem",
            ),
        ),
    ]
