# Generated by Django 3.2.4 on 2021-06-26 20:06

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0008_auto_20210626_2002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoice",
            name="id",
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
