# Generated by Django 3.2.4 on 2021-07-07 19:11

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0009_auto_20210626_2006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="INV",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemgroup",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemtransaction",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
