# Generated by Django 3.2.13 on 2022-06-15 17:13

from django.db import migrations, transaction


@transaction.atomic
def migrate_invoice_dynamic_totals_to_static(apps, schema_editor):
    print("Migrate invoice dynamic totals to static")
    invoice_item_class = apps.get_model("invoicing", "InvoiceItem")

    invoice_items = invoice_item_class.objects.all()

    for invoice_item in invoice_items:
        # call post_save signal to update totals
        print(invoice_item)
        invoice_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0012_auto_20220615_1546"),
    ]

    operations = [
        migrations.RunPython(migrate_invoice_dynamic_totals_to_static),
    ]
