# Generated by Django 4.0.7 on 2022-09-14 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0030_alter_company_city_alter_company_group_and_more"),
        ("invoicing", "0013_update_invoice_totals"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalinvoice",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Invoice",
                "verbose_name_plural": "historical Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalinvoiceitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Invoice Item",
                "verbose_name_plural": "historical Invoice Items",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalinvoiceitemgroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Invoice Group",
                "verbose_name_plural": "historical Invoice Groups",
            },
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoiceitem",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoiceitemgroup",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="If None this means that Invoice has been created automatically",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_created_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Company who will pay Invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_invoices",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_issued_invoices",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="If None this means that Invoice Item has been created automatically",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_invoice_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="If None this means that Invoice Item Group has been created automatically",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_invoice_item_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemtransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="If None this means that Invoice Transaction has been created automatically",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_invoice_item_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
