# Generated by Django 4.0.8 on 2022-11-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0014_alter_historicalinvoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoiceitemgroup",
            name="label",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitemgroup",
            name="label",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
