# Generated by Django 4.0.8 on 2022-12-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0015_historicalinvoiceitemgroup_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinvoiceitemgroup",
            name="label",
        ),
        migrations.RemoveField(
            model_name="invoiceitemgroup",
            name="label",
        ),
        migrations.AddField(
            model_name="historicalinvoiceitemgroup",
            name="category",
            field=models.CharField(
                choices=[("appeals_fees", "Appeals Fees")], max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitemgroup",
            name="category",
            field=models.CharField(
                choices=[("appeals_fees", "Appeals Fees")], max_length=255, null=True
            ),
        ),
    ]
