# Generated by Django 4.0.8 on 2022-12-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0017_alter_historicalinvoiceitemgroup_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoiceitemgroup",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("", "Any"), ("appeals_fees", "Appeals Fees")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemgroup",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("", "Any"), ("appeals_fees", "Appeals Fees")],
                default="",
                max_length=255,
            ),
        ),
    ]
