# Generated by Django 1.11.26 on 2020-04-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_auto_20190826_2024"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="inspection_grade_type",
            field=models.IntegerField(
                choices=[(1, "Letter grades"), (2, "Numeric grades")], default=1
            ),
        ),
    ]
