# Generated by Django 1.11.26 on 2020-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0008_auto_20200513_0909"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderorganization",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalcompany",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicaleeporganization",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalgeneralorganization",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalhvacorganization",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalproviderorganization",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalqaorganization",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalraterorganization",
            name="insurance_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalutilityorganization",
            name="insurance_certificate",
        ),
        migrations.AddField(
            model_name="company",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="worker_compensation_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Worker Compensation insurance is not required in the state(s) that this company operates in",
            ),
        ),
    ]
