# Generated by Django 1.11.26 on 2020-06-03 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0010_auto_20200603_1817"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalbuilderorganization",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalcompany",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicaleeporganization",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalgeneralorganization",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalhvacorganization",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalproviderorganization",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalqaorganization",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalraterorganization",
            name="mailing_geocode",
        ),
        migrations.RemoveField(
            model_name="historicalutilityorganization",
            name="mailing_geocode",
        ),
    ]
