# Generated by Django 1.11.26 on 2020-07-15 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0013_auto_20200713_2026"),
        ("company", "0013_auto_20200708_0838"),
    ]

    operations = []
