# Generated by Django 2.2 on 2020-11-25 18:31

import axis.company.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0016_auto_20201112_1154"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=axis.company.models.company.logo_image_upload_to,
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Logo"),
        ),
    ]
