# Generated by Django 3.1.3 on 2020-12-30 12:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0003_usstate"),
        (
            "company",
            "0018_communityarchitectsorganization_communitydeveloperownerorganization_communityownerorganization_histo",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="counties",
            field=models.ManyToManyField(
                blank=True,
                help_text='Click on a county from the box below to add it to the list of Counties of Operation for this company represented in the box to the below-right.  To remove counties from the list of Counties of Operation, click on a county in the box to the below-right.  Click on "Submit" when finished.',
                related_name="companies",
                to="geographic.County",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunityarchitectsorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunityarchitectsorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunitydeveloperownerorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunitydeveloperownerorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunityownerorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunityownerorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicaleeporganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicaleeporganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeneralorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeneralorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhvacorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhvacorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproviderorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproviderorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalqaorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalqaorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalraterorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalraterorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalutilityorganization",
            name="office_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter the main company phone number in the format XXX-XXX-XXXX.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalutilityorganization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Enter the 5-digit ZIP Code of home.",
                max_length=15,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
    ]
