# Generated by Django 3.1.3 on 2021-01-04 18:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0003_usstate"),
        ("ekotrope", "0006_auto_20200427_1422"),
        ("core", "0031_auto_20201230_1218"),
        ("qa", "0010_merge_20200811_1942"),
        ("filehandling", "0010_merge_20200701_0829"),
        ("home", "0014_auto_20201230_1218"),
        ("eep_program", "0018_auto_20200805_0937"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geocoder", "0011_merge_20200701_0829"),
        ("remrate", "0003_auto_20200423_1257"),
        ("floorplan", "0014_auto_20210104_1851"),
        ("customer_hirl", "0117_auto_20210104_1851"),
        ("user_management", "0034_remove_accreditation_eep_program"),
        ("customer_eto", "0012_merge_20200811_1942"),
        ("scheduling", "0012_auto_20200415_1540"),
        ("subdivision", "0006_auto_20200128_1940"),
        ("equipment", "0015_equipment_assignees"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sampleset", "0003_auto_20190725_1619"),
        (
            "incentive_payment",
            "0002_historicalincentivedistribution_history_change_reason_foo",
        ),
        ("relationship", "0002_historicalrelationship_history_change_reason_foo"),
        ("resnet", "0003_remove_resnetcompany_is_hesp_provider"),
        ("hes", "0006_auto_20201230_1218"),
        ("remrate_data", "0014_auto_20201230_1218"),
        ("certification", "0014_auto_20201230_1218"),
        ("builder_agreement", "0012_merge_20200811_1942"),
        ("customer_aps", "0012_auto_20201230_1218"),
        ("company", "0019_auto_20201230_1215"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CommunityArchitectsOrganization",
            new_name="ArchitectOrganization",
        ),
        migrations.RenameModel(
            old_name="CommunityDeveloperOwnerOrganization",
            new_name="DeveloperOrganization",
        ),
        migrations.RenameModel(
            old_name="HistoricalCommunityArchitectsOrganization",
            new_name="HistoricalArchitectOrganization",
        ),
        migrations.RenameModel(
            old_name="HistoricalCommunityDeveloperOwnerOrganization",
            new_name="HistoricalDeveloperOrganization",
        ),
        migrations.AlterModelOptions(
            name="historicalarchitectorganization",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical architect organization",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldeveloperorganization",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical developer organization",
            },
        ),
    ]
