# Generated by Django 3.2.4 on 2021-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0022_auto_20210115_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="altname",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="companydocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="contact_special",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalaltname",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchitectorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchitectorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchitectorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbuilderorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunityownerorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunityownerorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcommunityownerorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompanydocument",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeveloperorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeveloperorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeveloperorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicaleeporganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicaleeporganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleeporganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeneralorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeneralorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeneralorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhvacorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhvacorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhvacorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproviderorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproviderorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproviderorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalqaorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalqaorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalqaorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalraterorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalraterorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalraterorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalutilityorganization",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("eep", "Program Sponsor"),
                    ("provider", "Certification Organization"),
                    ("rater", "Rating/Verification Company"),
                    ("utility", "Utility Company"),
                    ("hvac", "HVAC Contractor"),
                    ("qa", "QA/QC Company"),
                    ("architect", "Architect Company"),
                    ("developer", "Developer Company"),
                    ("communityowner", "Owner Company"),
                    ("general", "General Company"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalutilityorganization",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalutilityorganization",
            name="street_line1",
            field=models.CharField(
                blank=True,
                help_text="Enter the street number and street name of the project (e.g. 123 Main St).",
                max_length=100,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorpreferences",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="utilitysettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
