# Generated by Django 3.2.14 on 2022-07-19 16:40

import axis.company.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0005_auto_20211021_1932"),
        ("company", "0023_auto_20210719_1332"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalaltname",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Alternative Name",
                "verbose_name_plural": "historical Alternative Names",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalarchitectorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical architect organization",
                "verbose_name_plural": "historical Community Architects Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbuilderorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Builder",
                "verbose_name_plural": "historical Builders",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcommunityownerorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical community owner organization",
                "verbose_name_plural": "historical Community Developer Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcompany",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical company",
                "verbose_name_plural": "historical Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcompanydocument",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical company document",
                "verbose_name_plural": "historical company documents",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldeveloperorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical developer organization",
                "verbose_name_plural": "historical Community Developer Owner Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaleeporganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Program Sponsor",
                "verbose_name_plural": "historical Program Sponsors",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalgeneralorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical general organization",
                "verbose_name_plural": "historical General Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhvacorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical HVAC Company",
                "verbose_name_plural": "historical HVAC Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproviderorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Provider",
                "verbose_name_plural": "historical Providers",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqaorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical qa organization",
                "verbose_name_plural": "historical QA/QC Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalraterorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Rating Company",
                "verbose_name_plural": "historical Rating Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalutilityorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Utility Company",
                "verbose_name_plural": "historical Utility Companies",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="temp_certification_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="company",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalarchitectorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalarchitectorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalarchitectorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalarchitectorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalarchitectorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalarchitectorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalarchitectorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchitectorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilderorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcommunityownerorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunityownerorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalcommunityownerorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcommunityownerorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcommunityownerorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunityownerorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcommunityownerorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalcommunityownerorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldeveloperorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicaldeveloperorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicaldeveloperorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldeveloperorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldeveloperorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldeveloperorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldeveloperorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeveloperorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicaleeporganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalgeneralorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalhvacorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalproviderorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalqaorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalraterorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="temp_auto_submit_to_registry",
            field=models.BooleanField(
                default=False, help_text="Auto Submit home to RESNET Registry upon certification."
            ),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="temp_certification_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="temp_electricity_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="temp_gas_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="temp_hquito_accredited",
            field=models.BooleanField(
                choices=[(None, "Unknown"), (True, "Accredited"), (False, "Not Accredited")],
                default=None,
                help_text="Set the H-QUITO accredited status based on EPA or Advanced Energy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="temp_is_sample_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="temp_provider_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[axis.company.validators.validate_provider_id],
                verbose_name="Provider ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalutilityorganization",
            name="temp_water_provider",
            field=models.BooleanField(default=False),
        ),
    ]
