# Generated by Django 4.0.6 on 2022-07-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("geographic", "0006_auto_20220719_1459"),
        ("company", "0026_auto_20220719_1914"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                help_text='Click on a country from the box below to add it to the list\nof Countries of Operation for this company represented in the box to the below-right.  To remove\ncounties from the list of Countries of Operation, click on a country in the box to the\nbelow-right.  Click on "Submit" when finished.',
                related_name="companies",
                to="geographic.country",
            ),
        ),
    ]
