# Generated by Django 4.0.6 on 2022-07-26 19:08

from django.db import migrations


def add_countries(apps, schema_editor):
    from axis.geographic.utils.country import resolve_country

    usa = resolve_country("US")
    Company = apps.get_model("company", "Company")
    ModelObj = apps.get_model("company", "Company").countries.through

    ModelObj.objects.bulk_create(
        [
            ModelObj(
                **{
                    "company_id": company.pk,
                    "country_id": usa.pk,
                }
            )
            for company in Company.objects.all()
        ]
    )


def update_company_countries(apps, schema_editor):
    from axis.geographic.utils.country import resolve_country
    from axis.company.models import Company
    from axis.home.models import Home

    # Home = apps.get_model("home", "Home")
    ModelObj = apps.get_model("company", "Company").countries.through

    for country in ["PR", "VI"]:
        print(f"Working on {country}")
        company_ids = set()
        for home in Home.objects.filter(city__country__abbr=country):
            company_ids.update(home.relationships.all().values_list("company_id", flat=True))

        company_ids.update(
            Company.objects.filter(city__country__abbr=country).values_list("id", flat=True)
        )

        country_model = resolve_country(country)
        ModelObj.objects.bulk_create(
            [
                ModelObj(
                    **{
                        "company_id": company.pk,
                        "country_id": country_model.pk,
                    }
                )
                for company in Company.objects.filter(id__in=list(company_ids))
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0027_company_countries_alter_company_city_and_more"),
    ]

    operations = [
        migrations.RunPython(add_countries),
        migrations.RunPython(update_company_countries),
    ]
