# Generated by Django 4.1.5 on 2023-02-22 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0031_companyrole_companyaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyaccess",
            name="roles",
            field=models.ManyToManyField(blank=True, to="company.companyrole"),
        ),
        migrations.AlterUniqueTogether(
            name="companyaccess",
            unique_together={("company", "user")},
        ),
    ]
