# Generated by Django 4.1.5 on 2023-02-24 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0032_alter_companyaccess_roles_and_more"),
    ]

    operations = []
