# Generated by Django 4.1.7 on 2023-04-18 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0034_company_shipping_geocode_response_and_more"),
    ]

    operations = []
