"""RemRate Models suitable for use by Axis """


import logging

from django.db import models

__author__ = "Steven Klass"
__date__ = "06/10/2019 11:03"
__copyright__ = "Copyright 2011-2023 Pivotal Energy Solutions. All rights reserved."
__credits__ = [
    "Steven Klass",
]

log = logging.getLogger(__name__)


class Compliance(models.Model):
    """Compliance - Describes the compliance of the simulation"""

    simulation = models.OneToOneField("Simulation", on_delete=models.CASCADE)
    _result_number = models.IntegerField(db_column="lBldgRunNo")

    hers_index = models.FloatField(db_column="fHERSScor")
    hers_total_cost = models.FloatField(db_column="fHERSCost")
    hers_stars = models.FloatField(db_column="fHERSStars")
    hers_reference_heating_consumption = models.FloatField(db_column="fHERSRHCn")
    hers_reference_cooling_consumption = models.FloatField(db_column="fHERSRCCn")
    hers_reference_hot_water_consumption = models.FloatField(db_column="fHERSRDCN")
    hers_reference_lights_appliance_consumption = models.FloatField(db_column="fHERSRLACn")
    hers_reference_photo_voltaic_consumption = models.FloatField(db_column="fHERSRPVCn")
    hers_reference_total_consumption = models.FloatField(db_column="fHERSRTCn")
    hers_designed_heating_consumption = models.FloatField(db_column="fHERSDHCn")
    hers_designed_cooling_consumption = models.FloatField(db_column="fHERSDCCn")
    hers_designed_hot_water_consumption = models.FloatField(db_column="fHERSDDCN")
    hers_designed_lights_appliance_consumption = models.FloatField(db_column="fHERSDLACn")
    hers_designed_photo_voltaic_consumption = models.FloatField(db_column="fHERSDPVCn")
    hers_designed_total_consumption = models.FloatField(db_column="fHERSDTCn")

    iecc98_reference_heating_consumption = models.FloatField(db_column="f98IERHCn")
    iecc98_reference_cooling_consumption = models.FloatField(db_column="f98IERCCn")
    iecc98_reference_hot_water_consumption = models.FloatField(db_column="f98IERDCN")
    iecc98_reference_lights_appliance_consumption = models.FloatField(db_column="f98IERLACn")
    iecc98_reference_photo_voltaic_consumption = models.FloatField(db_column="f98IERPVCn")
    iecc98_reference_total_consumption = models.FloatField(db_column="f98IERTCn")
    iecc98_designed_heating_consumption = models.FloatField(db_column="f98IEDHCn")
    iecc98_designed_cooling_consumption = models.FloatField(db_column="f98IEDCCn")
    iecc98_designed_hot_water_consumption = models.FloatField(db_column="f98IEDDCN")
    iecc98_designed_lights_appliance_consumption = models.FloatField(db_column="f98IEDLACn")
    iecc98_designed_photo_voltaic_consumption = models.FloatField(db_column="f98IEDPVCn")
    iecc98_designed_total_consumption = models.FloatField(db_column="f98IEDTCn")
    meets_iecc98_consumption_compliance = models.BooleanField(default=False, db_column="b98IECC")

    iecc00_reference_heating_consumption = models.FloatField(db_column="f00IERHCn")
    iecc00_reference_cooling_consumption = models.FloatField(db_column="f00IERCCn")
    iecc00_reference_hot_water_consumption = models.FloatField(db_column="f00IERDCN")
    iecc00_reference_lights_appliance_consumption = models.FloatField(db_column="f00IERLACn")
    iecc00_reference_photo_voltaic_consumption = models.FloatField(db_column="f00IERPVCn")
    iecc00_reference_total_consumption = models.FloatField(db_column="f00IERTCn")
    iecc00_designed_heating_consumption = models.FloatField(db_column="f00IEDHCn")
    iecc00_designed_cooling_consumption = models.FloatField(db_column="f00IEDCCn")
    iecc00_designed_hot_water_consumption = models.FloatField(db_column="f00IEDDCN")
    iecc00_designed_lights_appliance_consumption = models.FloatField(db_column="f00IEDLACn")
    iecc00_designed_photo_voltaic_consumption = models.FloatField(db_column="f00IEDPVCn")
    iecc00_designed_total_consumption = models.FloatField(db_column="f00IEDTCn")
    meets_iecc00_consumption_compliance = models.BooleanField(default=False, db_column="b00IECC")

    iecc01_reference_heating_consumption = models.FloatField(db_column="f01IERHCn")
    iecc01_reference_cooling_consumption = models.FloatField(db_column="f01IERCCn")
    iecc01_reference_hot_water_consumption = models.FloatField(db_column="f01IERDCN")
    iecc01_reference_lights_appliance_consumption = models.FloatField(db_column="f01IERLACn")
    iecc01_reference_photo_voltaic_consumption = models.FloatField(db_column="f01IERPVCn")
    iecc01_reference_total_consumption = models.FloatField(db_column="f01IERTCn")
    iecc01_designed_heating_consumption = models.FloatField(db_column="f01IEDHCn")
    iecc01_designed_cooling_consumption = models.FloatField(db_column="f01IEDCCn")
    iecc01_designed_hot_water_consumption = models.FloatField(db_column="f01IEDDCN")
    iecc01_designed_lights_appliance_consumption = models.FloatField(db_column="f01IEDLACn")
    iecc01_designed_photo_voltaic_consumption = models.FloatField(db_column="f01IEDPVCn")
    iecc01_designed_total_consumption = models.FloatField(db_column="f01IEDTCn")
    meets_iecc01_consumption_compliance = models.BooleanField(default=False, db_column="b01IECC")

    iecc03_reference_heating_consumption = models.FloatField(db_column="f03IERHCn")
    iecc03_reference_cooling_consumption = models.FloatField(db_column="f03IERCCn")
    iecc03_reference_hot_water_consumption = models.FloatField(db_column="f03IERDCN")
    iecc03_reference_lights_appliance_consumption = models.FloatField(db_column="f03IERLACn")
    iecc03_reference_photo_voltaic_consumption = models.FloatField(db_column="f03IERPVCn")
    iecc03_reference_total_consumption = models.FloatField(db_column="f03IERTCn")
    iecc03_designed_heating_consumption = models.FloatField(db_column="f03IEDHCn")
    iecc03_designed_cooling_consumption = models.FloatField(db_column="f03IEDCCn")
    iecc03_designed_hot_water_consumption = models.FloatField(db_column="f03IEDDCN")
    iecc03_designed_lights_appliance_consumption = models.FloatField(db_column="f03IEDLACn")
    iecc03_designed_photo_voltaic_consumption = models.FloatField(db_column="f03IEDPVCn")
    iecc03_designed_total_consumption = models.FloatField(db_column="f03IEDTCn")
    passes_iecc03_consumption_compliance = models.BooleanField(default=False, db_column="b03IECC")

    iecc04_reference_heating_cost = models.FloatField(db_column="f04IERHCT")
    iecc04_reference_cooling_cost = models.FloatField(db_column="f04IERCCT")
    iecc04_reference_hot_water_cost = models.FloatField(db_column="f04IERDCT")
    iecc04_reference_lights_appliance_cost = models.FloatField(db_column="f04IERLACT")
    iecc04_reference_photo_voltaic_cost = models.FloatField(db_column="f04IERPVCT")
    iecc04_reference_service_cost = models.FloatField(db_column="f04IERSVCT")
    iecc04_reference_total_cost = models.FloatField(db_column="f04IERTCT")
    iecc04_designed_heating_cost = models.FloatField(db_column="f04IEDHCT")
    iecc04_designed_cooling_cost = models.FloatField(db_column="f04IEDCCT")
    iecc04_designed_hot_water_cost = models.FloatField(db_column="f04IEDDCT")
    iecc04_designed_lights_appliance_cost = models.FloatField(db_column="f04IEDLACT")
    iecc04_designed_photo_voltaic_cost = models.FloatField(db_column="f04IEDPVCT")
    iecc04_designed_service_cost = models.FloatField(db_column="f04IEDSVCT")
    iecc04_designed_total_cost = models.FloatField(db_column="f04IEDTCT")
    passes_iecc04_consumption_compliance = models.BooleanField(default=False, db_column="b04IECC")

    iecc06_reference_heating_cost = models.FloatField(db_column="f06IERHCT")
    iecc06_reference_cooling_cost = models.FloatField(db_column="f06IERCCT")
    iecc06_reference_hot_water_cost = models.FloatField(db_column="f06IERDCT")
    iecc06_reference_lights_appliance_cost = models.FloatField(db_column="f06IERLACT")
    iecc06_reference_photo_voltaic_cost = models.FloatField(db_column="f06IERPVCT")
    iecc06_reference_service_cost = models.FloatField(db_column="f06IERSVCT")
    iecc06_reference_total_cost = models.FloatField(db_column="f06IERTCT")
    iecc06_designed_heating_cost = models.FloatField(db_column="f06IEDHCT")
    iecc06_designed_cooling_cost = models.FloatField(db_column="f06IEDCCT")
    iecc06_designed_hot_water_cost = models.FloatField(db_column="f06IEDDCT")
    iecc06_designed_lights_appliance_cost = models.FloatField(db_column="f06IEDLACT")
    iecc06_designed_photo_voltaic_cost = models.FloatField(db_column="f06IEDPVCT")
    iecc06_designed_service_cost = models.FloatField(db_column="f06IEDSVCT")
    iecc06_designed_total_cost = models.FloatField(db_column="f06IEDTCT")
    passes_iecc06_consumption_compliance = models.BooleanField(default=False, db_column="b06IECC")

    ny_ecc_reference_heating_consumption = models.FloatField(db_column="fNYECRHCn")
    ny_ecc_reference_cooling_consumption = models.FloatField(db_column="fNYECRCCn")
    ny_ecc_reference_hot_water_consumption = models.FloatField(db_column="fNYECRDCN")
    ny_ecc_reference_lights_appliance_consumption = models.FloatField(db_column="fNYECRLACn")
    ny_ecc_reference_photo_voltaic_consumption = models.FloatField(db_column="fNYECRPVCn")
    ny_ecc_reference_total_consumption = models.FloatField(db_column="fNYECRTCn")
    ny_ecc_designed_heating_consumption = models.FloatField(db_column="fNYECDHCn")
    ny_ecc_designed_cooling_consumption = models.FloatField(db_column="fNYECDCCn")
    ny_ecc_designed_hot_water_consumption = models.FloatField(db_column="fNYECDDCN")
    ny_ecc_designed_lights_appliance_consumption = models.FloatField(db_column="fNYECDLACn")
    ny_ecc_designed_photo_voltaic_consumption = models.FloatField(db_column="fNYECDPVCn")
    ny_ecc_designed_total_consumption = models.FloatField(db_column="fNYECDTCn")
    passes_ny_ecc_consumption_compliance = models.BooleanField(default=False, db_column="bNYECC")

    nv_ecc_reference_heating_consumption = models.FloatField(db_column="fNVECRHCn")
    nv_ecc_reference_cooling_consumption = models.FloatField(db_column="fNVECRCCn")
    nv_ecc_reference_hot_water_consumption = models.FloatField(db_column="fNVECRDCN")
    nv_ecc_reference_lights_appliance_consumption = models.FloatField(db_column="fNVECRLACn")
    nv_ecc_reference_photo_voltaic_consumption = models.FloatField(db_column="fNVECRPVCn")
    nv_ecc_reference_total_consumption = models.FloatField(db_column="fNVECRTCn")
    nv_ecc_designed_heating_consumption = models.FloatField(db_column="fNVECDHCn")
    nv_ecc_designed_cooling_consumption = models.FloatField(db_column="fNVECDCCn")
    nv_ecc_designed_hot_water_consumption = models.FloatField(db_column="fNVECDDCN")
    nv_ecc_designed_lights_appliance_consumption = models.FloatField(db_column="fNVECDLACn")
    nv_ecc_designed_photo_voltaic_consumption = models.FloatField(db_column="fNVECDPVCn")
    nv_ecc_designed_total_consumption = models.FloatField(db_column="fNVECDTCn")
    passes_nv_ecc_consumption_compliance = models.BooleanField(default=False, db_column="bNVECC")

    mec92_reference_overall_u0 = models.FloatField(db_column="f92MECReUo")
    mec92_as_designed_overall_u0 = models.FloatField(db_column="f92MECADUo")
    passes_mec92_ducts_u0 = models.BooleanField(default=False, db_column="b92MECDuP")
    passes_mec92_overall_u0 = models.BooleanField(default=False, db_column="b92MECuoP")
    mec93_reference_overall_u0 = models.FloatField(db_column="f93MECReUo")
    mec93_as_designed_overall_u0 = models.FloatField(db_column="f93MECADUo")
    passes_mec93_ducts_u0 = models.BooleanField(default=False, db_column="b93MECDuP")
    passes_mec93_overall_u0 = models.BooleanField(default=False, db_column="b93MECuoP")
    mec95_reference_overall_u0 = models.FloatField(db_column="f95MECReUo")
    mec95_as_designed_overall_u0 = models.FloatField(db_column="f95MECADUo")
    passes_mec95_ducts_u0 = models.BooleanField(default=False, db_column="b95MECDuP")
    passes_mec95_overall_u0 = models.BooleanField(default=False, db_column="b95MECuoP")

    iecc98_reference_overall_u0 = models.FloatField(db_column="f98IECCRUo")
    iecc98_designed_overall_u0 = models.FloatField(db_column="f98IECCDUo")
    passes_iecc98_ducts_overall_u0 = models.BooleanField(default=False, db_column="b98IECCDuP")
    passes_iecc98_overall_u0 = models.BooleanField(default=False, db_column="b98IECCuoP")
    iecc00_reference_overall_u0 = models.FloatField(db_column="f00IECCRUo")
    iecc00_designed_overall_u0 = models.FloatField(db_column="f00IECCDUo")
    passes_iecc00_ducts_overall_u0 = models.BooleanField(default=False, db_column="b00IECCDuP")
    passes_iecc00_overall_u0 = models.BooleanField(default=False, db_column="b00IECCuoP")
    iecc01_reference_overall_u0 = models.FloatField(db_column="f01IECCRUo")
    iecc01_designed_overall_u0 = models.FloatField(db_column="f01IECCDUo")
    passes_iecc01_ducts_overall_u0 = models.BooleanField(default=False, db_column="b01IECCDuP")
    passes_iecc01_overall_u0 = models.BooleanField(default=False, db_column="b01IECCuoP")
    iecc03_reference_overall_u0 = models.FloatField(db_column="f03IECCRUo")
    iecc03_designed_overall_u0 = models.FloatField(db_column="f03IECCDUo")
    passes_iecc03_ducts_overall_u0 = models.BooleanField(default=False, db_column="b03IECCDuP")
    passes_iecc03_overall_u0 = models.BooleanField(default=False, db_column="b03IECCuoP")
    iecc04_reference_overall_u0 = models.FloatField(db_column="f04IECCRUA")
    iecc04_designed_overall_u0 = models.FloatField(db_column="f04IECCDUA")
    passes_iecc04_ducts_overall_u0 = models.BooleanField(default=False, db_column="b04IECCDuP")
    passes_iecc04_overall_ua_compliance = models.BooleanField(default=False, db_column="b04IECCuAP")
    iecc06_reference_overall_u0 = models.FloatField(db_column="f06IECCRUA")
    iecc06_designed_overall_u0 = models.FloatField(db_column="f06IECCDUA")
    passes_iecc06_ducts_overall_u0 = models.BooleanField(default=False, db_column="b06IECCDuP")
    passes_iecc06_overall_ua_compliance = models.BooleanField(default=False, db_column="b06IECCuAP")

    mec92_reference_heating_consumption = models.FloatField(db_column="f92MECRHCn")
    mec92_reference_cooling_consumption = models.FloatField(db_column="f92MECRCCn")
    mec92_reference_hot_water_consumption = models.FloatField(db_column="f92MECRDCn")
    mec92_reference_lights_appliance_consumption = models.FloatField(db_column="f92MECRLCn")
    mec92_reference_photo_voltaic_consumption = models.FloatField(db_column="f92MECRPCn")
    mec92_reference_total_consumption = models.FloatField(db_column="f92MECRTCn")
    mec92_designed_heating_consumption = models.FloatField(db_column="f92MECDHCn")
    mec92_designed_cooling_consumption = models.FloatField(db_column="f92MECDCCn")
    mec92_designed_hot_water_consumption = models.FloatField(db_column="f92MECDDCn")
    mec92_designed_lights_appliance_consumption = models.FloatField(db_column="f92MECDLCn")
    mec92_designed_photo_voltaic_consumption = models.FloatField(db_column="f92MECDPCn")
    mec92_designed_total_consumption = models.FloatField(db_column="f92MECDTCn")
    passes_mec92_consumption_compliance = models.BooleanField(default=False, db_column="b92MECCC")

    mec93_reference_heating_consumption = models.FloatField(db_column="f93MECRHCn")
    mec93_reference_cooling_consumption = models.FloatField(db_column="f93MECRCCn")
    mec93_reference_hot_water_consumption = models.FloatField(db_column="f93MECRDCn")
    mec93_reference_lights_appliance_consumption = models.FloatField(db_column="f93MECRLCn")
    mec93_reference_photo_voltaic_consumption = models.FloatField(db_column="f93MECRPCn")
    mec93_reference_total_consumption = models.FloatField(db_column="f93MECRTCn")
    mec93_designed_heating_consumption = models.FloatField(db_column="f93MECDHCn")
    mec93_designed_cooling_consumption = models.FloatField(db_column="f93MECDCCn")
    mec93_designed_hot_water_consumption = models.FloatField(db_column="f93MECDDCn")
    mec93_designed_lights_appliance_consumption = models.FloatField(db_column="f93MECDLCn")
    mec93_designed_photo_voltaic_consumption = models.FloatField(db_column="f93MECDPCn")
    mec93_designed_total_consumption = models.FloatField(db_column="f93MECDTCn")
    passes_mec93_consumption_compliance = models.BooleanField(default=False, db_column="b93MECCC")

    mec95_reference_heating_consumption = models.FloatField(db_column="f95MECRHCn")
    mec95_reference_cooling_consumption = models.FloatField(db_column="f95MECRCCn")
    mec95_reference_hot_water_consumption = models.FloatField(db_column="f95MECRDCN")
    mec95_reference_lights_appliance_consumption = models.FloatField(db_column="f95MECRLCn")
    mec95_reference_photo_voltaic_consumption = models.FloatField(db_column="f95MECRPCn")
    mec95_reference_total_consumption = models.FloatField(db_column="f95MECRTCn")
    mec95_designed_heating_consumption = models.FloatField(db_column="f95MECDHCn")
    mec95_designed_cooling_consumption = models.FloatField(db_column="f95MECDCCn")
    mec95_designed_hot_water_consumption = models.FloatField(db_column="f95MECDDCN")
    mec95_designed_lights_appliance_consumption = models.FloatField(db_column="f95MECDLCn")
    mec95_designed_photo_voltaic_consumption = models.FloatField(db_column="f95MECDPCn")
    mec95_designed_total_consumption = models.FloatField(db_column="f95MECDTCn")
    passes_mec95_consumption_compliance = models.BooleanField(default=False, db_column="b95MECCC")

    ashrae_90p2_load_change = models.FloatField(db_column="f90_2ASLC")
    meets_ashrae_90p2_envelope_compliance = models.BooleanField(
        default=False, db_column="b90_2ASECP"
    )
    ashrae_90p2_reference_consumption = models.FloatField(db_column="f90_2ASRCn")
    ashrae_90p2_reference_cost = models.FloatField(db_column="f90_2ASRCt")
    ashrae_90p2_designed_consumption = models.FloatField(db_column="f90_2ASDCn")
    ashrae_90p2_designed_cost = models.FloatField(db_column="f90_2ASDCt")
    meets_ashrae_90p2_cost_compliance = models.BooleanField(default=False, db_column="b90_2ASCCP")

    passes_epact_tax_credit = models.BooleanField(null=True, default=False, db_column="bTaxCredit")
    ny_hers_score = models.FloatField(db_column="FNYHERS")
    passes_energy_star_v2 = models.BooleanField(default=False, db_column="bEStarv2")
    rating_number = models.CharField(null=True, max_length=93, db_column="sRateNo", blank=True)

    iecc09_reference_heating_cost = models.FloatField(db_column="f09IERHCT")
    iecc09_reference_cooling_cost = models.FloatField(db_column="f09IERCCT")
    iecc09_reference_hot_water_cost = models.FloatField(db_column="f09IERDCT")
    iecc09_reference_lights_appliance_cost = models.FloatField(db_column="f09IERLACT")
    iecc09_reference_photo_voltaic_cost = models.FloatField(db_column="f09IERPVCT")
    iecc09_reference_service_cost = models.FloatField(db_column="f09IERSVCT")
    iecc09_reference_total_cost = models.FloatField(db_column="f09IERTCT")
    iecc09_designed_heating_cost = models.FloatField(db_column="f09IEDHCT")
    iecc09_designed_cooling_cost = models.FloatField(db_column="f09IEDCCT")
    iecc09_designed_hot_water_cost = models.FloatField(db_column="f09IEDDCT")
    iecc09_designed_lights_appliance_cost = models.FloatField(db_column="f09IEDLACT")
    iecc09_designed_photo_voltaic_cost = models.FloatField(db_column="f09IEDPVCT")
    iecc09_designed_service_cost = models.FloatField(db_column="f09IEDSVCT")
    iecc09_designed_total_cost = models.FloatField(db_column="f09IEDTCT")
    passes_iecc09_consumption_compliance = models.BooleanField(default=False, db_column="b09IECC")
    iecc09_reference_overall_u0 = models.FloatField(db_column="f09IECCRUA")
    iecc09_designed_overall_u0 = models.FloatField(db_column="f09IECCDUA")
    passes_iecc09_ducts_overall_u0 = models.BooleanField(default=False, db_column="b09IECCDuP")
    passes_iecc09_overall_ua_compliance = models.BooleanField(default=False, db_column="b09IECCuAP")

    hers_photo_voltaic_adjusted_score = models.FloatField(db_column="fHERS_PV")
    energy_star_hers_score = models.FloatField(db_column="fES_HERS")
    energy_star_hers_saf_score = models.FloatField(db_column="fES_HERSSA")
    passes_energy_star_v2p5 = models.BooleanField(default=False, db_column="bEStarv25")
    passes_energy_star_v3 = models.BooleanField(default=False, db_column="bEStarv3")
    nv_energy_plus_rebate = models.FloatField(db_column="fNVRebate")
    passes_iecc04_code = models.BooleanField(default=False, db_column="bPass04IECC")
    passes_iecc06_code = models.BooleanField(default=False, db_column="bPass06IECC")
    passes_iecc09_code = models.BooleanField(default=False, db_column="bPass09IECC")
    passes_iecc12_code = models.BooleanField(null=True, default=False, db_column="bPass12IECC")
    passes_doe_challenge_home = models.BooleanField(null=True, db_column="bDOECHALL")
    hers_130 = models.FloatField(null=True, db_column="FHERS130", blank=True)
    size_adjustment_factor = models.FloatField(null=True, db_column="FES_SZADJF", blank=True)
    doe_hers = models.FloatField(null=True, db_column="FDOE_Hers", blank=True)
    doe_hers_saf_adjusted = models.FloatField(null=True, db_column="FDOE_HersSA", blank=True)

    pass_energy_star_v3p1 = models.BooleanField(null=True, db_column="bESTARV31", blank=True)
    pass_energy_star_v3HI = models.BooleanField(null=True, db_column="bESTARV3HI", blank=True)
