# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geocode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("raw_address", models.CharField(max_length=250)),
                ("timeout", models.DecimalField(decimal_places=1, default=1.5, max_digits=4)),
                ("entity_type", models.CharField(default="street_address", max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("immediate", models.BooleanField(default=False)),
                ("raw_street_line1", models.CharField(blank=True, max_length=100)),
                ("raw_street_line2", models.CharField(blank=True, max_length=100)),
                ("raw_zipcode", models.CharField(blank=True, max_length=15)),
                ("raw_cross_roads", models.CharField(blank=True, max_length=128)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="GeocodeResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[("Bing", "Bing"), ("Google", "Google")], max_length=32
                    ),
                ),
                ("place", models.TextField(blank=True, default=dict)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "geocode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="geocoder.Geocode",
                    ),
                ),
            ],
            options={"ordering": ["-engine"]},
        ),
    ]
