# Generated by Django 1.11.17 on 2019-07-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0004_auto_20181130_1905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocode",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="geocode",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="geocoderesponse",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
