# Generated by Django 1.11.26 on 2020-01-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0005_auto_20190725_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocoderesponse",
            name="engine",
            field=models.CharField(choices=[("Google", "Google"), ("Bing", "Bing")], max_length=32),
        ),
    ]
