# Generated by Django 1.11.26 on 2020-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0006_auto_20200128_1940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocoderesponse",
            name="engine",
            field=models.CharField(choices=[("Bing", "Bing"), ("Google", "Google")], max_length=32),
        ),
    ]
