# Generated by Django 1.11.26 on 2020-04-27 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0007_auto_20200415_1542"),
        ("geocoder", "0007_auto_20200420_1704"),
    ]

    operations = []
