# Generated by Django 1.11.26 on 2020-06-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0008_merge_20200427_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocoderesponse",
            name="engine",
            field=models.CharField(choices=[("Google", "Google"), ("Bing", "Bing")], max_length=32),
        ),
    ]
