# Generated by Django 3.1.8 on 2021-05-20 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geocoder", "0011_merge_20200701_0829"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geocode",
            name="timeout",
        ),
    ]
