# Generated by Django 3.2.7 on 2021-10-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geographic", "0005_auto_20211021_1932"),
        ("geocoder", "0012_remove_geocode_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="geocode",
            name="raw_county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geographic.county",
            ),
        ),
        migrations.AddField(
            model_name="geocode",
            name="raw_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geographic.usstate",
            ),
        ),
        migrations.AlterField(
            model_name="geocode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="geocoderesponse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
