# Generated by Django 1.11.16 on 2018-10-08 18:15

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("remrate_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GEEAData",
            fields=[],
            options={"indexes": [], "proxy": True},
            bases=("remrate_data.simulation",),
        ),
    ]
